"""ADVERSARIAL VERIFICATION of attempt 014 (theta-tape x zeros of zeta').

Independent re-derivation, NOT a re-run of their scripts.

STAGE 1.  The Dirichlet coefficients a_lambda of -zeta''/zeta'.
   THEY did: geometric-series expansion log2*(1+Y)*sum_k (-X)^k, truncated.
   I do   : direct Dirichlet-convolution recursion  F*H = G  with F = -zeta', G = zeta'',
            solved by peeling the n=2 term.  Different algorithm, same object.
            Gate against mpmath -zeta''/zeta' at several s.
STAGE 2.  Recompute their headline H1/H2 tape numbers from THEIR root sets with MY code,
            and -- crucially -- report the ABSOLUTE K values against the Exp(1) floor,
            which their table reports only as a ratio to a prediction.
STAGE 3.  (separate file/stage) fresh zeta' zeros at a NEW height with pure mpmath.
"""
import numpy as np, math, sys
from fractions import Fraction

def P(*a): print(*a); sys.stdout.flush()
TWOPI = 2*math.pi

# ----------------------------------------------------------------- STAGE 1
def coeffs_recursive(lam_max=2.4):
    """h_r with  -zeta''/zeta'(s) = sum_r h_r r^{-s}.
    From F*H = G,  F = -zeta' = sum_{n>=2} (log n) n^{-s},  G = zeta'' = sum_{n>=2}(log n)^2 n^{-s}.
    Coefficient of v^{-s}:  sum_{n>=2} c_n h_{v/n} = d_v (d_v=0 unless v is an integer >=2).
    Peel n=2:   h_{v/2} = ( d_v - sum_{n>=3} c_n h_{v/n} ) / log 2 .
    r ranges over rationals with 2-power denominator; enumerate v = 2r in increasing order."""
    R = math.exp(lam_max)
    l2 = math.log(2)
    # candidate r values: the multiplicative semigroup generated by {n/2 : n>=3} (plus 1)
    cand = {Fraction(1, 1)}
    frontier = {Fraction(1, 1)}
    gens = [Fraction(n, 2) for n in range(3, int(2*R)+2)]
    while frontier:
        nxt = set()
        for a in frontier:
            for g in gens:
                b = a*g
                if float(b) <= R + 1e-9 and b not in cand:
                    cand.add(b); nxt.add(b)
        frontier = nxt
    h = {}
    for r in sorted(cand, key=float):
        v = 2*r                       # v = n * r' summation variable
        d = (math.log(float(v)))**2 if (v.denominator == 1 and v.numerator >= 2) else 0.0
        acc = 0.0
        n = 3
        while True:
            q = v/n
            if float(q) < 1.0 - 1e-12:
                break
            if q in h:
                acc += math.log(n)*h[q]
            n += 1
            if n > int(float(v)) + 2:
                break
        h[r] = (d - acc)/l2
    return h

def zeta_lambda(lam_max=2.4):
    R = int(math.exp(lam_max)) + 1
    d = {}
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97):
        k = 1
        while p**k <= R:
            d[p**k] = math.log(p); k += 1
    return d

def stage1():
    P("="*100)
    P("STAGE 1 -- independent recursion for the Dirichlet coefficients of -zeta''/zeta'")
    H = coeffs_recursive(2.4)
    P(f"  a_0 (r=1)          = {H[Fraction(1,1)]:.12f}    log 2 = {math.log(2):.12f}   "
      f"diff {abs(H[Fraction(1,1)]-math.log(2)):.2e}")
    for r in (Fraction(3,2), Fraction(2,1), Fraction(5,2), Fraction(3,1), Fraction(4,1), Fraction(5,1)):
        P(f"  a(r={str(r):>4})          = {H[r]:+.8f}   amp^2 = a^2/r = {H[r]**2/float(r):.6f}")
    P("")
    P("  ratios zeta'/zeta of the line strength a^2 e^{-lam} (their claim: 4.000, 0.342, 4.000, 1.747)")
    Z = zeta_lambda(2.4)
    for n in (2, 3, 4, 5, 7, 8, 9):
        r = Fraction(n, 1)
        az = Z[n]**2/n if n in Z else 0.0
        ap = H[r]**2/n
        P(f"    n={n}: zeta' {ap:.5f}   zeta {az:.5f}   ratio {ap/az if az else float('nan'):.4f}")
    P("")
    # numeric gate against mpmath
    import mpmath as mp
    mp.mp.dps = 30
    P("  GATE: series vs mpmath -zeta''/zeta'(s)")
    for (sig, t) in ((4.0, 0.0), (5.0, 2.0), (6.0, 1.0), (8.0, 0.0)):
        s = mp.mpc(sig, t)
        lhs = -mp.zeta(s, derivative=2)/mp.zeta(s, derivative=1)
        rhs = sum(a*mp.mpf(r.numerator)**(-s)*mp.mpf(r.denominator)**(s) for r, a in H.items())
        P(f"    s={sig}+{t}i   exact {complex(lhs):.10f}   series {complex(rhs):.10f}   "
          f"|diff| {abs(complex(lhs-rhs)):.3e}")
    return H

# ----------------------------------------------------------------- STAGE 2
def theta_f(t):
    t = np.asarray(t, float)
    return t/2*np.log(t/TWOPI) - t/2 - math.pi/8 + 1/(48*t) + 7/(5760*t**3)

def stage2(H):
    P("")
    P("="*100)
    P("STAGE 2 -- my own tape arithmetic on THEIR root sets; ABSOLUTE K vs the Exp(1) floor")
    Z = zeta_lambda(2.4)
    LAM = []
    for r in sorted(H, key=float):
        lam = math.log(float(r))
        if 0.2 < lam <= 1.65:
            LAM.append((lam, str(r), H[r]**2*math.exp(-lam)))
    ZL = {round(math.log(n), 12): (n, L*L/n) for n, L in Z.items()}
    for tag, zf, pf in (("1e5", "att010_zeros_1e+05.npy", "att014_zpz_1e+05.npy"),
                        ("1e6", "att010_zeros_1e+06.npy", "att014_zpz_1e+06.npy"),
                        ("1e7", "att010_zeros_1e+07.npy", "att014_zpz_1e+07.npy")):
        g = np.load(zf); r = np.load(pf)
        t0, t1 = float(g[0]), float(g[-1]); tc = (t0+t1)/2; W = t1-t0
        L = math.log(tc/TWOPI)
        o = np.argsort(r.imag); gp = r.imag[o]; bp = r.real[o]-0.5
        uz = theta_f(g)/np.pi; uz -= uz[0]; Uz = uz[-1]
        up = theta_f(gp)/np.pi; up -= up[0]; Up = up[-1]
        P("")
        P(f"  T={tag}  W={W:.1f}  L={L:.5f}  n_zeta={len(g)} n_zp={len(r)} ratio {len(r)/len(g):.5f} "
          f"vs rho=log(T/4pi)/log(T/2pi)={math.log(tc/(4*math.pi))/L:.5f}")
        P(f"    beta'-1/2: median {np.median(bp):.4f} mean {bp.mean():.4f} max {bp.max():.4f} "
          f"min {bp.min():.4f}  #(<0)={int((bp<0).sum())}")
        P(f"    {'lam':>8}{'r':>7} | {'K_H1':>8}{'K_H2':>9}{'pred':>9} | {'H1 o/p':>8}{'H2 o/p':>8} | "
          f"{'K_zeta':>8}{'predz':>8}")
        r1, r2, k1 = [], [], []
        for lam, rs, A in LAM:
            tau = lam/L
            E = np.exp(2j*np.pi*tau*up)
            kp = abs(E.sum())**2/len(up)
            kw = abs((E*np.exp(lam*bp)).sum())**2/len(up)
            kz = abs(np.exp(2j*np.pi*tau*uz).sum())**2/len(uz)
            pred = Up*Up*A/(L*L*len(up))
            zz = ZL.get(round(lam, 12))
            predz = Uz*Uz*zz[1]/(L*L*len(uz)) if zz else float('nan')
            r1.append(kp/pred); r2.append(kw/pred); k1.append(kp)
            P(f"    {lam:>8.5f}{rs:>7} | {kp:>8.2f}{kw:>9.2f}{pred:>9.2f} | {kp/pred:>8.3f}{kw/pred:>8.3f} | "
              f"{kz:>8.2f}{predz:>8.2f}")
        r1 = np.array(r1); r2 = np.array(r2); k1 = np.array(k1)
        P(f"    -> H1 median {np.median(r1):.3f}  IQR {np.percentile(r1,25):.3f}-{np.percentile(r1,75):.3f}")
        P(f"    -> H2 median {np.median(r2):.3f}  IQR {np.percentile(r2,25):.3f}-{np.percentile(r2,75):.3f}")
        # THE KEY ADVERSARIAL LINE: absolute H1 K values vs the Exp(1) floor
        rng = np.random.default_rng(7)
        lam_rand = rng.uniform(0.25, 1.65, 400)
        Kfloor = np.array([abs(np.exp(2j*np.pi*(l/L)*up).sum())**2/len(up) for l in lam_rand])
        P(f"    ABSOLUTE H1 K at the 12 arithmetic freqs: median {np.median(k1):.3f} "
          f"mean {k1.mean():.3f} max {k1.max():.3f}")
        P(f"    EMPIRICAL FLOOR (400 random lam, same tape): median {np.median(Kfloor):.3f} "
          f"mean {Kfloor.mean():.3f} 90pct {np.percentile(Kfloor,90):.3f} 99pct {np.percentile(Kfloor,99):.3f}")
        from scipy import stats
        u_, p_ = stats.mannwhitneyu(k1, Kfloor, alternative='greater')
        P(f"    Mann-Whitney (H1 arithmetic freqs > floor)?  p = {p_:.3f}   "
          f"[if p ~ 0.5 the unweighted tape sees NOTHING = NULL-B CONFIRMED for H1]")
        # weight/phase decomposition: how much of A_w comes from the weight deviation
        lam2 = math.log(2.0); tau2 = lam2/L
        E = np.exp(2j*np.pi*tau2*up); w = np.exp(lam2*bp)
        Au = E.sum(); Aw = (E*w).sum(); Ad = (E*(w-1)).sum()
        P(f"    x=2 decomposition: |A_u|={abs(Au):.1f}  |A_w|={abs(Aw):.1f}  |A_dev|={abs(Ad):.1f}  "
          f"sum(w-1)={np.sum(w-1):.1f}  sqrt(n)={math.sqrt(len(up)):.1f}")

if __name__ == "__main__":
    H = stage1()
    stage2(H)
