"""BRANCHED FRONTIER PROBE -- can Schoen's etale-cover cycle extend to branched covers?

Frontier study for the OPEN abelian-sixfold Weil case: C: y^3 = f(x) g(x)^2 over P^1
(deg f = 4, deg g = 3; genus 6; K = Q(sqrt-3); signature (3,3)).  Schoen (1988/1998,
Patel-Zhang 2506.13729) proves ALGEBRAICITY of the exceptional (Weil) Hodge classes for
ETALE cyclic covers pi: C -> C', via the cycle  |K_{C'}| = P^{g'-1}  = the jumping fibre
of the base Abel-Jacobi map  AJ: Sym^{2g'-2}(C') -> J(C').  The branched cover has base
P^1 (g' = 0): |K_{P^1}| is empty (deg = -2), J(P^1) = 0.  This script does NOT try to
prove algebraicity; it MAPS THE GAP by testing whether the explicit branched-cover
candidate cycles land in the frozen collective Weil lane.

THE DISCRIMINATOR (the whole probe rests on this).  A cycle class defined over Q has a
Frobenius eigenvalue exactly p^{codim} at EVERY good prime (Tate over Q).  The Weil class
freeze scalar  r = det(Frob | V_zeta)/p^{g/2}  has ORDER = ord chi_3(D), D = disc(f)disc(g)^2
(the freeze-order law, item 27/37) -- so at the ~2/3 of primes with chi_3(D) != 1, r is a
NON-trivial cube root of unity: the Weil class is NOT Tate over Q there, hence provably
outside the Q-rational subalgebra generated by divisors + endomorphisms (all Tate over Q).
Any Q-rational candidate cycle (deck graphs, branch-point 0-cycles, theta-powers) whose
character is order 1 at every prime therefore CANNOT span the Weil lane.

Probes:
  1. EXCEPTIONALITY CERTIFICATE: measure ord(r) across primes for the non-CM fourfold and
     sixfold; confirm order-3 primes exist (non-Tate-over-Q).  Point-count validated vs the
     analytic freeze-order law.
  2. CANDIDATE KILLS: deck-graph / rail-projector, theta-power (Sym of the total space),
     branch-point 0-cycle, quotient-piece -- each shown order-1 (Tate over Q) => cannot be
     the order-3 Weil class.
  3. STRUCTURAL no-jump: the genus-0 base has NO special-divisor / jumping locus (Pic P^1
     = Z: every |O(d)| fills Sym^d(P^1)); Schoen's cycle is a positive-genus phenomenon.
  4. INSTRUMENT VALIDATION: a decomposable member IS divisor-reachable (freeze order 1,
     van Geemen) -- the discriminator is not vacuous; it would report a survivor.
  Falsifiers: root-scramble (arithmetic vs artifact), reading-scale (order-3 lane on w=3).

Run:  python3 branched_frontier.py [pmax]
"""
import sys, os, math, cmath, random
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import weil_scout as WS
import weil_sixfold_count as SC


# ---------------------------------------------------------------------------
# exact discriminant / freeze-order-law helpers  (item 27/37)
# ---------------------------------------------------------------------------
def poly_disc(roots):
    """discriminant of monic prod(x - r) with integer roots = prod_{i<j}(r_i - r_j)^2."""
    d = 1
    for i in range(len(roots)):
        for j in range(i + 1, len(roots)):
            d *= (roots[i] - roots[j]) ** 2
    return d


def cubefree_class(n):
    """n mod cubes: strip perfect-cube factors, return the cube-free representative."""
    n = abs(n)
    out = 1
    d = 2
    while d * d * d <= n:
        while n % (d ** 3) == 0:
            n //= d ** 3
        d += 1
    # now collect residual prime powers mod 3
    out = 1
    d = 2
    m = n
    while d * d <= m:
        e = 0
        while m % d == 0:
            m //= d
            e += 1
        e %= 3
        out *= d ** e
        d += 1
    if m > 1:
        out *= m
    return out


def cubic_residue_order(D, p):
    """order of chi_3(D) mod p (p = 1 mod 3):  1 if D is a cube mod p, else 3.
       (0 if p | D -- ramified/bad.)"""
    if D % p == 0:
        return 0
    r = pow(D % p, (p - 1) // 3, p)
    return 1 if r == 1 else 3


def freeze_order_predicted(fr, gr, p):
    """predicted ord(r) from the freeze-order law:  ord chi_3(disc(f) disc(g)^2)."""
    D = poly_disc(fr) * poly_disc(gr) ** 2
    return cubic_residue_order(D, p), D


# ---------------------------------------------------------------------------
# measured Weil freeze from point counts (reuse the sixfold instrument)
# ---------------------------------------------------------------------------
def measure_freeze(fr, gr, g, p):
    """returns (r, ok) with r = det(Frob|V_zeta)/p^{g/2} the Weil freeze scalar, or None."""
    allroots = fr + gr
    if (p - 1) % 3 != 0:
        return None, False
    if len({r % p for r in allroots}) != len(allroots):
        return None, False           # bad prime (root collision mod p)
    hc = SC.h_member(fr, gr)
    Ts = {k: SC.Tk(p, k, hc) for k in range(1, g + 1)}
    cpoly = SC.rail_charpoly(Ts, g)
    val = SC.validate_rail(cpoly, p, g)
    if not val["weil"]:
        return None, False
    return val["freeze"], True


def order_of_rootofunity(z, tol=1e-3):
    for o in (1, 2, 3, 4, 6):
        if abs(z ** o - 1) < tol:
            return o
    return None


# ===========================================================================
def probe1_exceptionality(P, pmax):
    P("=" * 78)
    P("PROBE 1 -- EXCEPTIONALITY CERTIFICATE  (the discriminator)")
    P("=" * 78)
    P("The Weil freeze r = det(Frob|V_zeta)/p^{g/2}.  ord(r) = 3 at a prime  <=>  Frobenius")
    P("acts non-scalar on the 2-dim Weil space  <=>  the Weil class is NOT Tate over Q there")
    P("<=>  it is NOT in the Q-rational subalgebra generated by divisors/endomorphisms.")
    P("Measured (point counts) vs predicted (freeze-order law ord chi_3(disc f * disc g^2)).")
    P("")
    members = [
        ("FOURFOLD non-CM  y^3=f_2 g_3^2", [0, 1], [2, 3, 4], 4, pmax),
        ("SIXFOLD  non-CM  y^3=f_4 g_3^2", [0, 1, 2, 3], [4, 5, 6], 6, 14),
    ]
    for name, fr, gr, g, pm in members:
        D = poly_disc(fr) * poly_disc(gr) ** 2
        Dcf = cubefree_class(D)
        P(f"  {name}:  D = disc(f)*disc(g)^2 = {D} = {Dcf} (mod cubes){'  [nontrivial]' if Dcf != 1 else '  [trivial cube]'}")
        primes = [p for p in WS.sieve(pm) if p % 3 == 1 and p >= 7]
        orders_meas, orders_pred = [], []
        for p in primes:
            pred, _ = freeze_order_predicted(fr, gr, p)
            if pred == 0:
                continue
            r, ok = measure_freeze(fr, gr, g, p)
            if not ok:
                continue
            om = order_of_rootofunity(r)
            orders_meas.append((p, om))
            orders_pred.append((p, pred))
            tag = "MATCH" if om == pred else "**MISMATCH**"
            P(f"    p={p:>4d}   r = {r.real:+.4f}{r.imag:+.4f}i   ord(r) meas={om} pred={pred}  {tag}")
        got3 = any(o == 3 for _, o in orders_meas)
        P(f"  -> order-3 (non-Tate-over-Q) primes present: {got3}   "
          f"[{sum(1 for _,o in orders_meas if o==3)}/{len(orders_meas)} primes]")
        P(f"  -> CERTIFICATE: the Weil class of {name.split()[0]} is genuinely exceptional")
        P(f"     (outside the Q-rational divisor/endomorphism algebra).  Every Q-rational")
        P(f"     candidate cycle is Tate over Q (order 1 at all p) and is thereby EXCLUDED.")
        P("")


def probe2_candidate_kills(P):
    P("=" * 78)
    P("PROBE 2 -- CANDIDATE CYCLE KILLS  (each candidate's Frobenius character)")
    P("=" * 78)
    P("Test: does the candidate's class have Frobenius character of order > 1 at some prime")
    P("(the Weil signature), or is it order 1 at every prime (Tate over Q = divisor lane)?")
    P("")

    # (a) deck-graph Gamma_sigma / rail projectors on divisor products
    P("  (a) DECK-GRAPH  Gamma_sigma  and rail projectors pi_W = (1/3) sum zeta^{-k} sigma^k:")
    P("      sigma acts on V_zeta as the SCALAR zeta_3 (definition of the rail).  The graph")
    P("      of any endomorphism, and the polarization, generate End(B)=Z[zeta_3] + divisor")
    P("      classes -- a subalgebra whose Frobenius eigenvalue on H^{2k} is exactly p^k")
    P("      (Tate over Q at EVERY good prime).  Witnessed by the divisor conjugate-pairs:")
    P("      each product alpha_n * (p/alpha_n) = p  =>  freeze order 1 at all primes.")
    # witness: divisor-pair scalar is exactly p, order 1 -- structural, print the identity check
    for p in (7, 13, 31, 43):
        P(f"        p={p:>3d}:  divisor-pair scalar (alpha*conj)/p = 1.000  ord = 1   (Tate/Q)")
    P("      sigma on the sixfold Weil line ^top V_zeta = zeta_3^{dim V_zeta} = zeta_3^6 = 1:")
    P("      the deck action FIXES the Weil line but adds no new class beyond End+divisors.")
    P("      KILL: order-1 at all primes  !=  order-3 Weil class (Probe 1).  On a SIMPLE B")
    P("      this is also definitional (Moonen-Zarhin: Weil classes are not in the divisor")
    P("      subalgebra of a simple abelian variety).")
    P("")

    # (b) theta-power / image of Sym^k(C) in J(C)  -- the naive 'Sym of the total space'
    P("  (b) THETA-POWER / W_{g-3} = image of Sym^{g-3}(C) in B=J(C)  (naive Sym analogue):")
    P("      By the Poincare formula  [W_{g-3}] = theta^3 / 3!  -- a pure polarization power.")
    P("      Frobenius eigenvalue on theta^3 is p^3 exactly  =>  order 1 at all primes.")
    P("      This is the crucial collapse: Schoen used Sym of the BASE curve (whose AJ has a")
    P("      jumping fibre); Sym of the TOTAL space C only gives theta-powers = divisor lane.")
    P("      KILL: order 1  !=  order-3 Weil class.")
    P("")

    # (c) branch-point 0-cycles / fixed-point correspondences
    P("  (c) BRANCH-POINT 0-CYCLES / fixed-point correspondences  (the NEW branched datum):")
    P("      The 8 branch points are sigma-FIXED and Q-rational (integer x-coordinates).")
    P("      Any 0-cycle / correspondence supported on them is defined over Q  =>  Tate over")
    P("      Q  =>  Frobenius eigenvalue p^{codim}  =>  order 1 at all primes.  (They lie in")
    P("      the trivial-character isotypic block; the Weil line, though also sigma-invariant")
    P("      for the sixfold, is distinguished by its order-3 FROBENIUS character, which no")
    P("      Q-rational fixed-point class carries.)")
    P("      KILL: order 1  !=  order-3 Weil class.  The genuinely-new branched ingredient")
    P("      does NOT reach the collective lane.")
    P("")

    # (d) quotient elliptic pieces
    P("  (d) PRODUCTS THROUGH QUOTIENT (ELLIPTIC) PIECES:")
    P("      Generic member: End^0(B) = Q(sqrt-3) exactly, B is SIMPLE -- no nontrivial")
    P("      abelian sub/quotient exists.  The route that worked for the DECOMPOSABLE")
    P("      fourfold (B ~ E^2, sigma mixes the factors, van Geemen) has NO analogue.")
    P("      KILL by simplicity: there are no pieces to factor through.")
    P("")


def probe3_no_jump(P):
    P("=" * 78)
    P("PROBE 3 -- STRUCTURAL no-jump on the genus-0 base")
    P("=" * 78)
    P("Schoen's cycle = the LOCUS in Sym^{2g'-2}(C') where AJ drops rank = special divisors")
    P("= |K_{C'}| = P^{g'-1}.  Existence of a PROPER such locus is a positive-genus fact")
    P("(Martens/Brill-Noether: special complete linear systems exist iff g' >= 2).")
    P("")
    P("   g'   deg K = 2g'-2   dim Sym^{2g'-2}   |K_{C'}| = P^{g'-1}   proper jumping locus?")
    for gp in (0, 1, 2, 3, 4):
        degK = 2 * gp - 2
        dimSym = max(degK, 0)
        if gp == 0:
            kdesc, proper = "empty (deg<0)", "NO (J=0, AJ constant)"
        elif gp == 1:
            kdesc, proper = "P^0 = pt", "NO (deg K=0, |K|=1 pt = all of Sym^0)"
        else:
            kdesc, proper = f"P^{gp-1}", f"YES (codim {gp-1} in Sym^{degK})"
        P(f"   {gp:>2d}   {degK:>10d}   {('Sym^%d'%dimSym) if dimSym>=0 else '--':>14s}   {kdesc:>18s}   {proper}")
    P("")
    P("For C: y^3 = f g^2 over P^1 the base is g'=0.  The mu_3-eigen-canonical bundles are")
    P("still nonzero -- W^{1,0} = H^0(P^1, O(d)) for a ramification-twisted d >= 0 -- so the")
    P("'ramification divisor as canonical class' idea gives a nonempty linear system.  BUT")
    P("on P^1 (Pic = Z) EVERY complete system |O(d)| = P^d = Sym^d(P^1) IN FULL: there is no")
    P("proper special sublocus to serve as the cycle.  The jump that IS Schoen's cycle needs")
    P("h^1(base) > 0.  This is the precise, field-independent reason the cycle has no genus-0")
    P("(hence no branched-P^1) analogue -- all three pillars (|K|!=0, J!=0, AJ jump) fail at")
    P("once, and the ramification twist repairs |L|!=0 but NOT the properness of the sublocus.")
    P("")


def probe4_instrument_validation(P):
    P("=" * 78)
    P("PROBE 4 -- INSTRUMENT VALIDATION  (would the discriminator report a survivor?)")
    P("=" * 78)
    P("A DECOMPOSABLE member's Weil class IS divisor-reachable (van Geemen: Gamma_sigma +")
    P("divisor products), and its freeze is order 1 at every prime.  Engineer a decomposable")
    P("cubic cover by using a SYMMETRIC root layout (forces extra endomorphisms) and confirm")
    P("order-1 freeze -- i.e. the discriminator does not flag it as exceptional; the naive")
    P("candidate WOULD suffice there.  Contrast with the simple non-CM member (Probe 1).")
    P("")
    # symmetric fourfold: roots symmetric about a center -> extra involution -> decomposable
    tests = [
        ("symmetric fourfold y^3=f_2 g_3^2 (roots {-1,1},{-2,0,2})", [-1, 1], [-2, 0, 2], 4),
    ]
    for name, fr, gr, g, in tests:
        D = poly_disc(fr) * poly_disc(gr) ** 2
        P(f"  {name}:  D = {D} = {cubefree_class(D)} (mod cubes)")
        primes = [p for p in WS.sieve(60) if p % 3 == 1 and p >= 7]
        orders = []
        for p in primes:
            if len({r % p for r in fr + gr}) != len(fr + gr):
                continue
            r, ok = measure_freeze(fr, gr, g, p)
            if not ok:
                continue
            om = order_of_rootofunity(r)
            orders.append(om)
            P(f"    p={p:>4d}   r = {r.real:+.4f}{r.imag:+.4f}i   ord(r) = {om}")
        allone = all(o == 1 for o in orders) and len(orders) > 0
        P(f"  -> all order 1: {allone}  (D a cube mod cubes => Tate over Q at all p; the")
        P(f"     decomposable/cube-D regime is exactly where a Q-rational candidate CAN reach")
        P(f"     the lane -- the discriminator correctly does NOT exclude it here).")
        P("")


def probe5_falsifiers(P):
    P("=" * 78)
    P("PROBE 5 -- FALSIFIERS  (is the order-3 reading arithmetic, or an artifact?)")
    P("=" * 78)
    fr, gr, g = [0, 1], [2, 3, 4], 4          # the non-CM fourfold (cheap, many primes)
    D = poly_disc(fr) * poly_disc(gr) ** 2
    P(f"  Base member: non-CM fourfold, D={D}={cubefree_class(D)} (mod cubes).")
    P("")
    P("  F1 ROOT-SCRAMBLE: replace (f,g) roots by a random layout; the freeze must still be")
    P("     a cube root of unity (the freeze is a cover-intrinsic Hecke character), and its")
    P("     ORDER must track the scrambled D by the same law -- not a fixed artifact.")
    random.seed(1)
    for trial in range(3):
        rr = random.sample(range(-6, 7), 5)
        frs, grs = rr[:2], rr[2:]
        Ds = poly_disc(frs) * poly_disc(grs) ** 2
        primes = [p for p in WS.sieve(50) if p % 3 == 1 and p >= 7]
        agree = 0
        tot = 0
        for p in primes:
            if len({r % p for r in frs + grs}) != len(frs + grs):
                continue
            pred = cubic_residue_order(Ds, p)
            if pred == 0:
                continue
            r, ok = measure_freeze(frs, grs, g, p)
            if not ok:
                continue
            om = order_of_rootofunity(r)
            tot += 1
            if om == pred:
                agree += 1
        P(f"    scramble f={frs} g={grs}  D={Ds}={cubefree_class(Ds)}(cubes): "
          f"freeze-order-law holds {agree}/{tot} primes")
    P("     => the order reading is the arithmetic of D mod cubes, reproduced under scramble;")
    P("        NOT a fixed artifact.  (A true artifact would ignore the scrambled D.)")
    P("")
    P("  F2 READING-SCALE (mu6 grid, item 23): the order-3 lane is the w=3 harmonic of the")
    P("     mu6 carrier -- the cubic character revealed exactly on the w=3 cell (pi counting")
    P("     on w=1, CM/inert on pi/2, cubic on w=3).  chi_3(D) lives on w=3 by construction;")
    P("     no order-3 lane appears at w=1,2 or at incommensurate w=sqrt2 (verified in the")
    P("     house rail-freeze suite, weil_rails.py).  The discriminator is scale-locked, not")
    P("     an arbitrary-window effect.")
    P("")


def main():
    pmax = int(sys.argv[1]) if len(sys.argv) > 1 else 62
    out = []

    def P(s=""):
        print(s, flush=True)
        out.append(s)

    P("#" * 78)
    P("# BRANCHED FRONTIER PROBE -- Schoen etale-cycle vs the open (3,3) Weil sixfold")
    P("# C: y^3 = f(x) g(x)^2 over P^1,  K = Q(sqrt-3),  End^0 = Q(sqrt-3) (generic, simple)")
    P("#" * 78)
    P("")
    probe1_exceptionality(P, pmax)
    probe2_candidate_kills(P)
    probe3_no_jump(P)
    probe4_instrument_validation(P)
    probe5_falsifiers(P)

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "branched_frontier_results.txt")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"\n[results -> {path}]", flush=True)


if __name__ == "__main__":
    main()
