

# This file was *autogenerated* from the file chain_occupancy.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_16 = Integer(16); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_20 = Integer(20); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_500 = Integer(500)# W1-final probe v2: rail occupancy of twisted limit canonicals on the mu_3 chain.
# Chain: R_0 - E_1 - R_1 - ... - E_g - R_g (tree; bridges = copies of E0,
# eps_i = [T - O] exact order 3; attachment points P_i, Q_i in E0(F_p) vary).
# omega_0|E_i = O(P_i + Q_i); twist j: O(P_i + Q_i + jT - jO); rationals untwisted.
# Sections: per-component + residue matching at nodes (dualizing sheaf, tree =>
# eps glues trivially).  v2 fix: L(D) pool = x^a y^b / ((x - xP)(x - xQ)) so
# sections HAVE poles at the attachment points; conditions at conjugates + T/T'/O.

p = _sage_const_7 
F = GF(p)
S = LaurentSeriesRing(F, default_prec=_sage_const_16 , names=('s',)); (s,) = S._first_ngens(1)
Tpt, Tppt = (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))


def conj(pt):
    x0, y0 = pt
    return (x0, -y0 - _sage_const_2 *x0 - _sage_const_1 )


def series_at(pl):
    """(x(s), y(s)) at the place pl ('O' or affine point)."""
    if pl == 'O':
        xO = s**-_sage_const_2 
        for _ in range(_sage_const_20 ):
            xO = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xO*s)
        return (xO, xO/s)
    x0, y0 = pl
    xs = x0 + s
    ys = y0 + _sage_const_0 *s
    for _ in range(_sage_const_20 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return (xs, ys)


POOL = [(a, b) for a in range(-_sage_const_2 , _sage_const_4 ) for b in range(_sage_const_0 , _sage_const_2 )]


def LD(P, Q, j):
    """L(P + Q + jT - jO) on E0.  Returns (K, resP, resQ): kernel basis matrix
    over the 12-monomial pool /D(x), and residue vectors (of f*omega0) at P, Q."""
    xP, xQ = P[_sage_const_0 ], Q[_sage_const_0 ]
    allow = {P: _sage_const_1 , Q: _sage_const_1 }
    for pt in (conj(P), conj(Q), Tpt, Tppt):
        if pt not in allow:
            allow[pt] = _sage_const_0 
    allow[Tpt] = max(allow.get(Tpt, _sage_const_0 ), _sage_const_0 ) + j   # jT pole allowance
    allow['O'] = -j                              # forced vanishing order j at O
    rows, sers_at = [], {}
    for pl, a in allow.items():
        xs, ys = series_at(pl)
        den = (xs - xP) * (xs - xQ)
        sers = [xs**aa * ys**bb / den for (aa, bb) in POOL]
        sers_at[pl] = (xs, ys, sers)
        minv = min(t.valuation() for t in sers)
        for order in range(minv, -a):
            rows.append([t[order] for t in sers])
    M = matrix(F, rows)
    K = M.right_kernel().basis_matrix()
    res = {}
    for pl in (P, Q):
        xs, ys, sers = sers_at[pl]
        w = xs.derivative() / (_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
        res[pl] = [sum(c * t for c, t in zip(K.row(r), sers)) * w
                   for r in range(K.nrows())]
        res[pl] = [t[-_sage_const_1 ] for t in res[pl]]
    # T-valuation fingerprint per basis vector (rail occupancy datum)
    xs, ys, sers = sers_at[Tpt]
    vT = []
    for r in range(K.nrows()):
        f = sum(c * t for c, t in zip(K.row(r), sers))
        vT.append(f.valuation() if f != _sage_const_0  else 'inf')
    return K, res[P], res[Q], vT


def chain_occupancy(g, att, j):
    bridge = []
    nvars = _sage_const_0 
    offs = []
    for (P, Q) in att:
        K, rP, rQ, vT = LD(P, Q, j)
        offs.append(nvars)
        bridge.append((K.nrows(), rP, rQ, vT))
        nvars += K.nrows()
    N = nvars + (g - _sage_const_1 )
    rows = []
    for i in range(g):
        nb, rP, rQ, vT = bridge[i]
        row = [F(_sage_const_0 )] * N                       # node E_i|P_i <-> R_{i-1}
        for r in range(nb):
            row[offs[i] + r] = rP[r]
        if i >= _sage_const_1 :
            row[nvars + i - _sage_const_1 ] += F(-_sage_const_1 )
        rows.append(row)
        row = [F(_sage_const_0 )] * N                       # node E_i|Q_i <-> R_i
        for r in range(nb):
            row[offs[i] + r] = rQ[r]
        if i <= g - _sage_const_2 :
            row[nvars + i] += F(_sage_const_1 )
        rows.append(row)
    M = matrix(F, rows)
    Kg = M.right_kernel().basis_matrix()
    dims = [b[_sage_const_0 ] for b in bridge]
    support = []
    for r in range(Kg.nrows()):
        v = Kg.row(r)
        bs = [i for i in range(g)
              if any(v[offs[i] + t] for t in range(bridge[i][_sage_const_0 ]))]
        rs = [k for k in range(g - _sage_const_1 ) if v[nvars + k]]
        support.append((bs, rs))
    return Kg.nrows(), dims, support, [b[_sage_const_3 ] for b in bridge]


E0pts = [(x0, y0) for x0 in F for y0 in F
         if (y0**_sage_const_2  + _sage_const_2 *x0*y0 + y0 - x0**_sage_const_3 ) == _sage_const_0 ]
aff = [pt for pt in E0pts if pt[_sage_const_0 ] != _sage_const_0 ]
print(f"E0(F_{p}) usable affine points (x != 0): {len(aff)}", flush=True)

import random
for g in (_sage_const_2 , _sage_const_3 ):
    print(f"=== chain g={g} ===", flush=True)
    for trial in range(_sage_const_4 ):
        random.seed(int(_sage_const_100 *g + trial))
        att = [tuple(random.sample(aff, _sage_const_2 )) for _ in range(g)]
        for j in range(_sage_const_3 ):
            dim, dims, supp, vTs = chain_occupancy(g, att, j)
            print(f"  t{trial} j={j}: dim={dim} (exp {g if j==_sage_const_0  else g-_sage_const_1 }) "
                  f"perbridge-h0={dims} vT={vTs}", flush=True)
            for (bs, rs) in supp:
                print(f"      section: bridges {bs}, interior rationals {rs}",
                      flush=True)


def add_pts(P1, P2):
    """Group law on y^2 + 2xy + y = x^3 (a1=2, a3=1)."""
    x1, y1 = P1
    x2, y2 = P2
    if x1 == x2 and (y1 + y2 + _sage_const_2 *x1 + _sage_const_1 ) == _sage_const_0 :
        return 'O'
    if P1 == P2:
        lam = (_sage_const_3 *x1**_sage_const_2  - _sage_const_2 *y1) / (_sage_const_2 *y1 + _sage_const_2 *x1 + _sage_const_1 )
    else:
        lam = (y2 - y1) / (x2 - x1)
    x3 = lam**_sage_const_2  + _sage_const_2 *lam - x1 - x2
    y3 = lam*(x1 - x3) - y1 - _sage_const_2 *x3 - _sage_const_1 
    return (x3, y3)


print("=== EXCLUSION probe: Q = P (+) T  (attachment difference in <eps>) ===",
      flush=True)
for g in (_sage_const_2 ,):
    for trial in range(_sage_const_4 ):
        random.seed(int(_sage_const_500  + trial))
        att = []
        for _ in range(g):
            while True:
                P = random.choice(aff)
                Q = add_pts(P, Tpt)
                if Q != 'O' and Q[_sage_const_0 ] != _sage_const_0  and Q != P:
                    break
            att.append((P, Q))
        for j in range(_sage_const_3 ):
            dim, dims, supp, vTs = chain_occupancy(g, att, j)
            print(f"  t{trial} j={j}: dim={dim} (smooth-val {g if j==_sage_const_0  else g-_sage_const_1 })"
                  f" perbridge-h0={dims} vT={vTs}", flush=True)
            for (bs, rs) in supp:
                print(f"      section: bridges {bs}, interior rationals {rs}",
                      flush=True)

