

# This file was *autogenerated* from the file tmp/dim8b_lpoly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_11 = Integer(11); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_8 = Integer(8); _sage_const_17 = Integer(17)# Dim-8 re-roll verdict tower.  Usage: sage tmp/dim8b_lpoly.sage al be ga a_num a_den
# C' : u^3 + al*x^2*u + (x*y + be*y + ga*x + a) = 0 over E0;  C : t^3 = y.
# Stage 1: p=7 k=1..6: genus-5 certificate with the CORRECT overdetermination
#   (power-sum recurrence: p_k = e1 p_{k-1} - ... , NOT roots of the printed poly).
# Stage 2: p=7 k=7,8: deg-16 P_Prym via Newton+FE; purity; factor over ZZ ==>
#   SIMPLICITY verdict.  O-fiber: unramified, n_u(O) = 1 + 2*[-al is a QR];
#   n_t per O-branch = gcd(3, q-1)-style (y-leading -1 = cube).

import sys
args = sys.argv[_sage_const_1 :]
AL, BE, GA = ZZ(args[_sage_const_0 ]), ZZ(args[_sage_const_1 ]), ZZ(args[_sage_const_2 ])
A_ = QQ(args[_sage_const_3 ]) / QQ(args[_sage_const_4 ])
print(f"family: al={AL} be={BE} ga={GA} a={A_}")


def counts(p, k):
    q = p ** k
    F = GF(q, 'g')
    R = PolynomialRing(F, 'U')
    U = R.gen()
    one_third = _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_1 
    third = (q - _sage_const_1 ) // _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_0 
    al, be, ga, aa = F(AL), F(BE), F(GA), F(A_)
    nCp = nC = _sage_const_0 
    for x0 in F:
        b = _sage_const_2  * x0 + _sage_const_1 
        D = b * b + _sage_const_4  * x0 ** _sage_const_3 
        if D == _sage_const_0 :
            ys = [-b / _sage_const_2 ]
        elif D.is_square():
            s = D.sqrt()
            ys = [(-b + s) / _sage_const_2 , (-b - s) / _sage_const_2 ]
        else:
            ys = []
        for y0 in ys:
            f = U ** _sage_const_3  + al * x0 ** _sage_const_2  * U + (x0 * y0 + be * y0 + ga * x0 + aa)
            nu = len(f.roots(multiplicities=False))
            if y0 == _sage_const_0 :
                nt = one_third
            elif q % _sage_const_3  == _sage_const_1 :
                nt = _sage_const_3  if y0 ** third == _sage_const_1  else _sage_const_0 
            else:
                nt = _sage_const_1 
            nCp += nu
            nC += nu * nt
    nuO = _sage_const_1  + (_sage_const_2  if (-al).is_square() else _sage_const_0 )
    nCp += nuO
    nC += nuO * one_third
    return nCp, nC


def newton_e(tpow, g):
    e = [QQ(_sage_const_1 )] + [QQ(_sage_const_0 )] * g
    for k in range(_sage_const_1 , g + _sage_const_1 ):
        acc = QQ(_sage_const_0 )
        for i in range(_sage_const_1 , k + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e[k - i] * tpow[i - _sage_const_1 ]
        e[k] = acc / k
    return e


def fe_extend(e, p, g):
    # full elementary symmetric list e_0..e_{2g} via FE c_{2g-j} = p^{g-j} c_j,
    # c_j = (-1)^j e_j
    c = [(-_sage_const_1 ) ** j * e[j] for j in range(g + _sage_const_1 )] + [_sage_const_0 ] * g
    for j in range(g):
        c[_sage_const_2  * g - j] = p ** (g - j) * c[j]
    return [(-_sage_const_1 ) ** j * c[j] for j in range(_sage_const_2  * g + _sage_const_1 )], c


def powersum_extend(e_full, tpow, upto):
    # p_k = sum_{i<k} (-1)^{i-1} e_i p_{k-i} + (-1)^{k-1} k e_k  (k <= deg)
    ps = list(tpow)
    n = len(e_full) - _sage_const_1 
    for k in range(len(ps) + _sage_const_1 , upto + _sage_const_1 ):
        acc = QQ(_sage_const_0 )
        for i in range(_sage_const_1 , min(k, n) + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e_full[i] * (ps[k - i - _sage_const_1 ] if k - i >= _sage_const_1  else _sage_const_0 )
        if k <= n:
            acc += (-_sage_const_1 ) ** (k - _sage_const_1 ) * k * e_full[k]
        ps.append(acc)
    return ps


p = _sage_const_7 
NsCp, NsC = [], []
for k in range(_sage_const_1 , _sage_const_9 ):
    nCp, nC = counts(p, k)
    NsCp.append(nCp)
    NsC.append(nC)
    print(f"k={k} q={p**k}: #C'={nCp} #C={nC} s_k={nCp - nC}")
    sys.stdout.flush()
    if k == _sage_const_6 :
        t5 = [p ** j + _sage_const_1  - NsCp[j - _sage_const_1 ] for j in range(_sage_const_1 , _sage_const_6 )]
        e5 = newton_e(t5, _sage_const_5 )
        eF, cF = fe_extend(e5, p, _sage_const_5 )
        ps = powersum_extend(eF, t5, _sage_const_6 )
        pred = p ** _sage_const_6  + _sage_const_1  - ps[_sage_const_5 ]
        ok = (pred == NsCp[_sage_const_5 ])
        print(f"GENUS 5 CERTIFICATE: predicted #C'(7^6) = {pred}, actual = "
              f"{NsCp[_sage_const_5 ]} -> {'PASS' if ok else 'FAIL'}")
        S = PolynomialRing(QQ, 'T')
        T = S.gen()
        P5 = sum(QQ(cF[j]) * T ** j for j in range(_sage_const_11 ))
        rts = P5.change_ring(CDF).roots(multiplicities=False)
        print("purity:", "PASS" if all(abs(abs(r) ** _sage_const_2  * p - _sage_const_1 ) < _sage_const_1en6  for r in rts)
              else "FAIL")
        sys.stdout.flush()

sPrym = [NsCp[j] - NsC[j] for j in range(_sage_const_8 )]
print("Prym power sums:", sPrym)
e8 = newton_e(sPrym, _sage_const_8 )
eF, cF = fe_extend(e8, p, _sage_const_8 )
S = PolynomialRing(QQ, 'T')
T = S.gen()
PP = sum(QQ(cF[j]) * T ** j for j in range(_sage_const_17 ))
print("P_Prym:", PP)
rts = PP.change_ring(CDF).roots(multiplicities=False)
print("purity:", "PASS" if all(abs(abs(r) ** _sage_const_2  * p - _sage_const_1 ) < _sage_const_1en6  for r in rts) else "FAIL")
fac = factor(PP)
print("factor over ZZ:", fac)
irr = len(list(fac)) == _sage_const_1  and fac[_sage_const_0 ][_sage_const_1 ] == _sage_const_1 
print("SIMPLICITY:", "PASS -- SIMPLE ABELIAN EIGHTFOLD, the pipeline inherits"
      if irr else "NOT SIMPLE -- decomposition, diagnose correspondence")

