

# This file was *autogenerated* from the file tmp/eightfold_end_analysis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_7 = Integer(7); _sage_const_1en6 = RealNumber('1e-6')# End/MT analysis for the eightfold, run once tmp/eightfold_lpoly.log carries P_Prym.
# Parses the deg-16 Prym char poly at p = 7 and runs the sixfold-proven battery:
#   (1) irreducibility over Q  ==> SIMPLICITY (split prime: Frob_p = Frob_frak-p)
#   (2) subfield lattice of Q(pi_7): must contain Q(sqrt-3) = K; the OTHER subfields
#       are the End-candidate fingerprint (compare with a second prime when available)
#   (3) power stability: minpoly degree of pi^n for n in {2,3,4,6,8,12,16} -- degree
#       drop would signal extra endomorphisms appearing over an extension
#   (4) purity recheck exact: constant term = p^8, |roots|^2 p = 1
import re

with open('tmp/eightfold_lpoly.log') as fh:
    txt = fh.read()
m = re.search(r'P_Prym\(T\) deg 16 : (.*)', txt)
if not m:
    print("P_Prym not in log yet -- tower still running")
    sys.exit(_sage_const_0 )

S = PolynomialRing(QQ, 'T')
T = S.gen()
P = S(sage_eval(m.group(_sage_const_1 ), locals={'T': T}))
print("P_Prym =", P)
assert P.degree() == _sage_const_16 

fac = P.factor()
print("factorization over Q:", fac)
irr = len(list(fac)) == _sage_const_1  and fac[_sage_const_0 ][_sage_const_1 ] == _sage_const_1 
print("(1) SIMPLICITY:", "PASS -- simple abelian eightfold" if irr else "FAIL/inspect")

if irr:
    # normalize to monic integral: reciprocal poly of Frobenius eigenvalues
    Pm = (T ** _sage_const_16  * P(_sage_const_1  / T) / P(_sage_const_0 ) * P.leading_coefficient()).numerator()
    Pm = S(P.reverse() / P.leading_coefficient()) if False else S(list(reversed(P.list())))
    Pm = Pm / Pm.leading_coefficient()
    L = NumberField(Pm, 'pi')
    pi = L.gen()
    print("Q(pi_7) degree:", L.degree())
    subs = L.subfields()
    print("(2) subfield degrees:", sorted(set(F[_sage_const_0 ].degree() for F in subs)))
    for F, emb, _ in subs:
        if F.degree() == _sage_const_2 :
            print("    quadratic subfield:", F.defining_polynomial(),
                  " disc:", F.discriminant())
    has_K = any(F[_sage_const_0 ].degree() == _sage_const_2  and F[_sage_const_0 ].discriminant() == -_sage_const_3  for F in subs)
    print("    contains K = Q(sqrt-3):", "PASS" if has_K else
          "NOT FOUND (check normalization)")
    print("(3) power stability (minpoly degree of pi^n):")
    stable = True
    for n in [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_6 , _sage_const_8 , _sage_const_12 , _sage_const_16 ]:
        d = (pi ** n).minpoly().degree()
        stable = stable and (d == _sage_const_16 )
        print(f"    n={n}: degree {d}")
    print("    STABLE (no degree drop):", "PASS -- End constraints geometric"
          if stable else "DROP -- extension endomorphisms, inspect")
    print("(4) constant/leading:", P.list()[_sage_const_0 ], P.list()[-_sage_const_1 ],
          " (expect 1 and 7^8 =", _sage_const_7  ** _sage_const_8 , ")")
    rts = P.change_ring(CDF).roots(multiplicities=False)
    print("    purity:", "PASS" if all(abs(abs(r) ** _sage_const_2  * _sage_const_7  - _sage_const_1 ) < _sage_const_1en6  for r in rts)
          else "FAIL")

