

# This file was *autogenerated* from the file tmp/endo.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100)
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface
R = QQ['x, y']; (x, y,) = R._first_ngens(2)

cases = {
 'generic   y^3=(x-1)(x-2)(x-3)(x-5)': y**_sage_const_3  - (x-_sage_const_1 )*(x-_sage_const_2 )*(x-_sage_const_3 )*(x-_sage_const_5 ),
 'symmetric y^3 = x^4 - 1  (CM)':      y**_sage_const_3  - (x**_sage_const_4  - _sage_const_1 ),
 'Klein-ish y^3 = x^4 - x  ':          y**_sage_const_3  - (x**_sage_const_4  - x),
}
print("Endomorphism algebra of the Jacobian (dim over Q = # independent Hodge classes")
print("on Jac x Jac beyond the trivial ones).  Picard curves all carry Z[zeta_3], so")
print("dim >= 2; genuine EXTRA structure (CM) shows a strictly larger algebra.\n")
for name, f in cases.items():
    S = RiemannSurface(f, prec=_sage_const_100 )
    E = S.endomorphism_basis()
    print(f"  {name:38}  End(Jac)⊗Q dim = {len(E)}")

