

# This file was *autogenerated* from the file tmp/explore.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_80 = Integer(80); _sage_const_0 = Integer(0)
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface
R = QQ['x, y']; (x, y,) = R._first_ngens(2)
S = RiemannSurface(y**_sage_const_3  - (x**_sage_const_4  - _sage_const_1 ), prec=_sage_const_80 )
meths = [m for m in dir(S) if not m.startswith('__')]
want = ['homology','period','riemann','abel','jacobi','endo','cohom','differ','monodromy','tangent','cycle','intersection','paths']
print("relevant RiemannSurface methods:")
for m in meths:
    if any(w in m.lower() for w in want):
        print("   ", m)
print()
# what does homology basis look like?
try:
    print("homology_basis type:", type(S.homology_basis()))
    hb = S.homology_basis()
    print("num cycles:", len(hb), " first cycle (paths) length:", len(hb[_sage_const_0 ]) if hb else _sage_const_0 )
except Exception as ex:
    print("homology_basis:", ex)

