

# This file was *autogenerated* from the file hw_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_719 = Integer(719); _sage_const_6 = Integer(6); _sage_const_300 = Integer(300)# h^0(O(W)) for the constructed failing W on the mu_3 tower.
# W = (2 of 3 t-preimages) over each point of the u-fiber {u=c} on C.
# L(W) = (1/(u-c)) * { g in L(D9) : g(v_i) = 0, i=1..3 }, where D9 = the nine
# O-places of C~ with pole <= 1, and v_i = the EXCLUDED preimages.
# Predictions: dim L(D9) = 4 ({1,u} + {t} + {x/t} isotypics); kernel = 1
# (contains u-c) => h^0(O(W)) = 1 => literal h^0=1 counterexample on the
# thetanull curve.

load('petri_t1.sage')   # F, E0S, UB, TB, MONS machinery; zeta3 = 2 in F_7

ZETA = F(_sage_const_2 )
assert ZETA**_sage_const_3  == _sage_const_1  and ZETA != _sage_const_1 

# pool: x^p y^q u^i t^j
def build_pool(PMIN, PMAX):
    return [(p, q, i, j) for p in range(PMIN, PMAX+_sage_const_1 ) for q in (_sage_const_0 , _sage_const_1 )
            for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def L_D9(pool):
    rows = []
    for pl in ('T', 'Tp', 'O'):
        xs, ys = E0S[pl]
        tb = TB[pl]
        allow = _sage_const_1  if pl == 'O' else _sage_const_0 
        for ub in UB[pl]:
            for k in range(_sage_const_3 ):
                tser = ZETA**k * tb
                sers = [xs**p * ys**q * ub**i * tser**j for (p, q, i, j) in pool]
                minv = min(t.valuation() for t in sers)
                for order in range(minv, -allow):
                    rows.append([t[order] for t in sers])
    M = matrix(F, rows)
    return M.right_kernel().basis_matrix()


for (pmin, pmax) in ((-_sage_const_2 , _sage_const_3 ), (-_sage_const_3 , _sage_const_4 )):
    pool = build_pool(pmin, pmax)
    K9 = L_D9(pool)
    print(f"pool p in [{pmin},{pmax}] ({len(pool)} monomials): "
          f"dim L(D9) = {K9.nrows()} (predict 4)", flush=True)

pool = build_pool(-_sage_const_3 , _sage_const_4 )
K9 = L_D9(pool)

# --- excluded points: pick a u-fiber, for each of its 3 base points pick ONE
# t-preimage to exclude (W = the other two).  Try several fibers and choices.
import random
random.seed(int(_sage_const_719 ))
P = PolynomialRing(F, names=('z',)); (z,) = P._first_ngens(1)
Rx = PolynomialRing(F, names=('xx',)); (xx,) = Rx._first_ngens(1)


def eval_g(vec, pt):
    x0, y0, u0, t0 = pt
    v = F(_sage_const_0 )
    for ccoef, (p, q, i, j) in zip(vec, pool):
        if ccoef:
            v += ccoef * x0**p * y0**q * u0**i * t0**j
    return v


tested = _sage_const_0 
ci = _sage_const_0 
while tested < _sage_const_6  and ci < _sage_const_300 :
    ci += _sage_const_1 
    c = F.random_element()
    if c == _sage_const_0 :
        continue
    yy = -(c**_sage_const_3  + c*xx + _sage_const_1 )
    rts = (yy**_sage_const_2  + _sage_const_2 *xx*yy + yy - xx**_sage_const_3 ).roots()
    if len(rts) != _sage_const_3 :
        continue
    base = []
    ok = True
    for (x0, _) in rts:
        y0 = -(c**_sage_const_3  + c*x0 + _sage_const_1 )
        if x0 == _sage_const_0  or y0 == _sage_const_0  or _sage_const_3 *c**_sage_const_2  + x0 == _sage_const_0 :
            ok = False
            break
        trs = (z**_sage_const_3  - y0).roots()
        if len(trs) != _sage_const_3 :
            ok = False
            break
        base.append((x0, y0, [r for r, _ in trs]))
    if not ok:
        continue
    # two exclusion patterns: random choice, and "aligned" choice (first root)
    for tag in ('random', 'aligned'):
        excl = []
        for (x0, y0, trs) in base:
            t0 = random.choice(trs) if tag == 'random' else trs[_sage_const_0 ]
            excl.append((x0, y0, c, t0))
        rows = [[eval_g(K9.row(r), pt) for r in range(K9.nrows())]
                for pt in excl]
        M = matrix(F, rows)
        h0W = K9.nrows() - M.rank()
        print(f"  fiber c={c} [{tag}]: h^0(O(W)) = {h0W} "
              f"({'LITERAL h^0=1 counterexample' if h0W == _sage_const_1  else 'h>=2 point'})",
              flush=True)
    tested += _sage_const_1 

