

# This file was *autogenerated* from the file tmp/inspect_iter.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_30 = Integer(30); _sage_const_1600 = Integer(1600)
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface
import inspect
S = RiemannSurface(QQ['x,y'].gen(0)**_sage_const_0 *_sage_const_0  + _sage_const_0 , prec=_sage_const_30 ) if False else None
from sage.schemes.riemann_surfaces import riemann_surface as rs
m = rs.RiemannSurface._integrate_differentials_iteratively
print("SIGNATURE:", inspect.signature(m))
doc = (m.__doc__ or "")
print("DOC (first 1600 chars):")
print(doc[:_sage_const_1600 ])

