

# This file was *autogenerated* from the file integral_model_s3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8)# beyond-playbook direction 2 (2026-07-28): the NON-ABELIAN cut-glue integral
# model. H1 of an etale G-cover of a genus-g curve = Z[G]^{2(g-1)} (+) Z^2 with
# the standard G-symplectic form (same skeleton the cyclic model used and
# validated against Lange-Ortega). Compute the rho(x)omega isotypic lattice for
# G = S3 x Z/3 (the 2-dim irrep packet - OUTSIDE Patel-Zhang), restrict to a
# transposition-invariant half (= the Prym of the degree-3 non-Galois quotient
# tower, multiplicity-1 copy of B), and read the polarization type / Pfaffian.
# THE QUESTION: does the 2-dim irrep break the uniform-rescale law? Odd
# 2-valuation of the Pfaffian => det has odd valuation at the K-inert prime 2
# => disc not a norm => NON-SPLIT => the first beyond-playbook specimen CLASS.
# GATE first: G = Z/3 must reproduce the Lange-Ortega type (1^{g-1}, 3^{g-1}).
from sage.all import (matrix, identity_matrix, ZZ, QQ, block_matrix, vector)
import itertools, json

def s3_elements():
    # permutations of (0,1,2) as tuples; id first
    return [(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]

def s3_mul(p, q):  # (p*q)(i) = p(q(i))
    return tuple(p[q[i]] for i in range(_sage_const_3 ))

def s3_chi_rho(p):
    fix = sum(_sage_const_1  for i in range(_sage_const_3 ) if p[i] == i)
    return {_sage_const_3 : _sage_const_2 , _sage_const_1 : _sage_const_0 , _sage_const_0 : -_sage_const_1 }[fix]   # id:2, transposition:0, 3-cycle:-1

def build_group(kind):
    """returns (elements, mul, inv, psi) for the rational packet character."""
    if kind == "Z3":
        els = [_sage_const_0 , _sage_const_1 , _sage_const_2 ]
        mul = lambda a, b: (a + b) % _sage_const_3 
        inv = lambda a: (-a) % _sage_const_3 
        psi = lambda a: _sage_const_2  if a == _sage_const_0  else -_sage_const_1         # omega + omegabar packet
        dimchi = _sage_const_1 
    elif kind == "Z6":
        els = list(range(_sage_const_6 ))
        mul = lambda a, b: (a + b) % _sage_const_6 
        inv = lambda a: (-a) % _sage_const_6 
        psi = lambda a: [_sage_const_2 , _sage_const_1 , -_sage_const_1 , -_sage_const_2 , -_sage_const_1 , _sage_const_1 ][a]   # primitive zeta6 packet
        dimchi = _sage_const_1 
    else:  # S3 x Z3
        S = s3_elements()
        els = [(s, j) for s in S for j in range(_sage_const_3 )]
        mul = lambda a, b: (s3_mul(a[_sage_const_0 ], b[_sage_const_0 ]), (a[_sage_const_1 ] + b[_sage_const_1 ]) % _sage_const_3 )
        inv = lambda a: (tuple(sorted(range(_sage_const_3 ), key=lambda i: a[_sage_const_0 ][i])), (-a[_sage_const_1 ]) % _sage_const_3 )
        psi = lambda a: s3_chi_rho(a[_sage_const_0 ]) * (_sage_const_2  if a[_sage_const_1 ] == _sage_const_0  else -_sage_const_1 )
        dimchi = _sage_const_2 
    return els, mul, inv, psi, dimchi

def model(kind, g):
    els, mul, inv, psi, dimchi = build_group(kind)
    n = len(els)
    idx = {e: i for i, e in enumerate(els)}
    H = g - _sage_const_1                       # handle blocks
    N = _sage_const_2  * H * n + _sage_const_2               # + central (atilde, beta)
    # basis: for h in range(H): e-block [h*2n .. h*2n+n), f-block [.. +2n)
    E = matrix(ZZ, N, N)
    for h in range(H):
        base = _sage_const_2  * n * h
        for i in range(n):
            E[base + i, base + n + i] = _sage_const_1 
            E[base + n + i, base + i] = -_sage_const_1 
    E[N-_sage_const_2 , N-_sage_const_1 ] = _sage_const_1 ; E[N-_sage_const_1 , N-_sage_const_2 ] = -_sage_const_1 
    assert abs(E.det()) == _sage_const_1 , "unimodularity gate FAIL"
    def act(k):
        M = matrix(ZZ, N, N)
        for h in range(H):
            base = _sage_const_2  * n * h
            for gi, ge in enumerate(els):
                t = idx[mul(k, ge)]
                M[base + t, base + gi] = _sage_const_1 
                M[base + n + t, base + n + gi] = _sage_const_1 
        M[N-_sage_const_2 , N-_sage_const_2 ] = _sage_const_1 ; M[N-_sage_const_1 , N-_sage_const_1 ] = _sage_const_1 
        return M
    # G-invariance spot check
    k0 = els[_sage_const_1 ]
    A0 = act(k0)
    assert A0.T * E * A0 == E, "G-symplectic gate FAIL"
    # packet projector P = (dimchi/|G|) sum psi(k^{-1}) act(k); psi(k^{-1})=psi(k)
    Pnum = sum(psi(k) * act(k) for k in els)   # = (|G|/dimchi) P, integer matrix
    scale = n // dimchi                        # P = Pnum/scale... check: e = (dim/|G|) sum
    # e_packet = (dimchi/n) * sum psi(k^{-1}) k  => P = (dimchi/n) Pnum
    M_iso = scale * identity_matrix(ZZ, N) - Pnum   # kernel = isotypic lattice (saturated)
    Lam = M_iso.right_kernel().basis_matrix()
    r_iso = Lam.nrows()
    out = {"kind": kind, "g": int(g), "rank_iso": int(r_iso)}
    if kind in ("Z3", "Z6"):
        B = Lam
        expect = _sage_const_4  * (g - _sage_const_1 )
    else:
        # multiplicity-1 copy: intersect with ker(act(tau) - 1), tau = transposition
        tau = ((_sage_const_1 , _sage_const_0 , _sage_const_2 ), _sage_const_0 )
        Mtau = act(tau) - identity_matrix(ZZ, N)
        stack = block_matrix(ZZ, [[M_iso], [Mtau]])
        B = stack.right_kernel().basis_matrix()
        out["rank_tauinv"] = int(B.nrows())
        expect = _sage_const_8  * (g - _sage_const_1 )
    Gram = B * E * B.T
    eds = [d for d in Gram.elementary_divisors() if d != _sage_const_0 ]
    # alternating: divisors in pairs
    pairs = eds[::_sage_const_2 ]
    assert eds[_sage_const_1 ::_sage_const_2 ] == pairs, f"SNF pairing anomaly: {eds}"
    pf = _sage_const_1 
    for d in pairs:
        pf *= d
    out.update({"rank_used": int(B.nrows()), "expected": int(expect),
                "type": [int(d) for d in pairs], "Pf": int(pf),
                "v2": int(ZZ(pf).valuation(_sage_const_2 )) if pf != _sage_const_0  else None,
                "v3": int(ZZ(pf).valuation(_sage_const_3 )) if pf != _sage_const_0  else None})
    return out

results = []
# GATE: cyclic law (1^{g-1}, 3^{g-1}) at base genus 4 (house-verified) and 2
for g in (_sage_const_2 , _sage_const_4 ):
    r = model("Z3", g)
    r["gate_LO"] = (r["type"] == [_sage_const_1 ]*(g-_sage_const_1 ) + [_sage_const_3 ]*(g-_sage_const_1 ))
    results.append(r)
    print(r, flush=True)
# GATE 2: Z6 primitive packet at base genus 4 must reproduce the house mu6
# verdict (2,2,2,6,6,6)
r = model("Z6", _sage_const_4 )
r["gate_mu6"] = (r["type"] == [_sage_const_2 ,_sage_const_2 ,_sage_const_2 ,_sage_const_6 ,_sage_const_6 ,_sage_const_6 ])
results.append(r); print(r, flush=True)
# THE VERDICT: S3 x Z3, base genus 2 (fourfold) and 3 (eightfold)
for g in (_sage_const_2 , _sage_const_3 ):
    r = model("S3xZ3", g)
    results.append(r)
    print(r, flush=True)
with open("integral_model_s3.json", "w") as fh:
    json.dump(results, fh, default=int)
print("S3 MODEL DONE", flush=True)

