

# This file was *autogenerated* from the file tmp/mu6_lpoly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_2000 = Integer(2000); _sage_const_200 = Integer(200); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_64 = Integer(64)# mu_6 tower: full k<=6 tower at p=7 with SIX-BIN DFT -> three rail systems.
#   E = 20a1: y^2 = x^3 + x^2 + 4x + 4;  P6 = (4,10) order 6;  h = f3^2 (x - x(3P6))
#   C' : u^3 + x*u + (y + 1) = 0   (v2 design: fiber LINEAR in (x,y) => u-map degree 3
#        PRIME => no intermediate covers, the v1/flex disease excluded BY DESIGN)
#   C  : t^6 = h∘pi  (etale, connected).  g' = 4, g_C = 19.
# Pieces: B6 = (V_chi + V_chi^5)/  [dim 6, K = Q(sqrt-3) Weil, glue | 6: NON-SPLIT
# candidate], B3 = (V_chi^2 + V_chi^4) [dim 6, mu_3 control], B2 = V_chi^3 [dim 3].
# kappa(P) = h(P)^((q-1)/6) is the descent homomorphism; special points by
# kappa(R+S) = kappa(R)kappa(S).  zeta_6 = 3 mod 7 (3^2 - 3 + 1 = 7): consistent
# across k since 3 in F_7 c F_{7^k}.
# DFT: S_m(k) = q^k + 1 - #C_m -> T_j = (1/6) sum_m zeta6^{-mj} S_m in Q(zeta_3)
# (zeta6 = -w^2).  Newton -> rail polys f_1, f_2, f_3 (deg 6 each).
# Pieces: P_B6 = f_1 * conj(f_1), P_B3 = f_2 * conj(f_2), P_B2 = f_3 (self-conj).
# Verdicts: purity each rail; freezes e_6/p^3 per rail; simplicity of each piece.

E = EllipticCurve('20a1')
P6 = E(_sage_const_4 , _sage_const_10 )
assert P6.order() == _sage_const_6 
a1, a2, a3, a4, a6 = E.a_invariants()
xP, yP = P6.xy()
P2, P3 = _sage_const_2  * P6, _sage_const_3  * P6
x2, y2 = P2.xy()
x3, y3 = P3.xy()
lam1 = (_sage_const_3  * xP ** _sage_const_2  + _sage_const_2  * a2 * xP + a4 - a1 * yP) / (_sage_const_2  * yP + a1 * xP + a3)
lam2 = (y2 - yP) / (x2 - xP)

K = CyclotomicField(_sage_const_3 , 'w')
w = K.gen()
z6 = -w ** _sage_const_2                       # primitive 6th root in K
A_PARAM = _sage_const_1 
p = _sage_const_7 
Z6INT = _sage_const_3                         # 3 is a primitive 6th root of unity mod 7


def h_eval(F, X, Y):
    l1 = Y - F(yP) - F(lam1) * (X - F(xP))
    v2 = X - F(x2)
    l2 = Y - F(y2) - F(lam2) * (X - F(x2))
    v3 = X - F(x3)
    num = l1 * l2
    den = v2 * v3
    if den == _sage_const_0  or num == _sage_const_0 :
        return None
    return (num / den) ** _sage_const_2  * (X - F(x3))


def twisted_counts(k):
    q = p ** k
    F = GF(q, 'g')
    Ep = E.change_ring(F)
    R = PolynomialRing(F, 'U')
    U = R.gen()
    z = F(Z6INT)
    zpow = [z ** i for i in range(_sage_const_6 )]
    e6 = (q - _sage_const_1 ) // _sage_const_6 

    def kap(pt):
        if pt.is_zero():
            return _sage_const_0 
        v = h_eval(F, pt[_sage_const_0 ], pt[_sage_const_1 ])
        if v is None:
            return None
        return zpow.index(v ** e6)

    # kappa at the divisor support: leading-coefficient regularization at P6
    # (well-defined mod 6th powers).  Hand derivation: tangent second-order coeff
    # y''/2 = 1/5, chord leading 1, v2(P6) = 4, v3(P6) = 5 => c3 = 1/100,
    # c6 = (x(P6) - x3) * c3^2 = 5/10000 = 1/2000.  Extend by the homomorphism.
    C6_LEAD = QQ(_sage_const_1 ) / _sage_const_2000 
    c6 = F(C6_LEAD.numerator()) / F(C6_LEAD.denominator())
    mP6 = zpow.index(c6 ** e6)
    P6b = Ep(P6)
    special = {}
    for j in range(_sage_const_1 , _sage_const_6 ):
        S = j * P6b
        if S.is_zero():
            continue
        special[(S[_sage_const_0 ], S[_sage_const_1 ])] = (j * mP6) % _sage_const_6 
        # cross-validate the homomorphism extension against generic pairs when
        # the field has non-torsion points (k >= 2)
        m2 = None
        for _ in range(_sage_const_200 ):
            Rp = Ep.random_point()
            mR, mRS = kap(Rp), kap(Rp + S)
            if mR is not None and mRS is not None:
                m2 = (mRS - mR) % _sage_const_6 
                break
        if m2 is not None and m2 != (j * mP6) % _sage_const_6 :
            print(f"  WARNING k={k}: hom-extension bin {(j * mP6) % _sage_const_6 } != "
                  f"pair-calibrated {m2} at {j}*P6 -- convention broken")

    nCp = _sage_const_0 
    Cm = [_sage_const_0 ] * _sage_const_6 
    for pt in Ep:
        if pt.is_zero():
            continue
        X, Y = pt[_sage_const_0 ], pt[_sage_const_1 ]
        f = U ** _sage_const_3  + X * U + (Y + A_PARAM)
        nu = len(f.roots(multiplicities=False))
        m = kap(pt)
        if m is None:
            m = special.get((X, Y))
        nCp += nu
        Cm[m] += _sage_const_6  * nu
    nuO = len((U ** _sage_const_3  + U + _sage_const_1 ).roots(multiplicities=False))
    nCp += nuO
    Cm[_sage_const_0 ] += _sage_const_6  * nuO             # kappa(O) = 1: all six t-branches in bin 0
    return nCp, Cm


def newton_charpoly(T1, d):
    e = [K(_sage_const_1 )] + [K(_sage_const_0 )] * d
    for kk in range(_sage_const_1 , d + _sage_const_1 ):
        acc = K(_sage_const_0 )
        for i in range(_sage_const_1 , kk + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e[kk - i] * T1[i - _sage_const_1 ]
        e[kk] = acc / kk
    S = PolynomialRing(K, 'T')
    T = S.gen()
    return sum((-_sage_const_1 ) ** j * e[j] * T ** (d - j) for j in range(d + _sage_const_1 )), e


print("MU6 TOWER  p = 7, k = 1..6  (three rails)")
T = {_sage_const_1 : [], _sage_const_2 : [], _sage_const_3 : []}
convOK = True
for k in range(_sage_const_1 , _sage_const_7 ):
    nCp, Cm = twisted_counts(k)
    q = p ** k
    S = [q + _sage_const_1  - Cm[m] for m in range(_sage_const_6 )]
    okSum = (sum(Cm) == _sage_const_6  * nCp)
    t0 = sum(S) / _sage_const_6 
    convOK = convOK and okSum and (t0 == q + _sage_const_1  - nCp)
    for j in (_sage_const_1 , _sage_const_2 , _sage_const_3 ):
        tj = sum(z6 ** (-m * j) * S[m] for m in range(_sage_const_6 )) / _sage_const_6 
        T[j].append(tj)
    print(f"k={k}: #C'={nCp} C_m={Cm} sum={'OK' if okSum else 'FAIL'} "
          f"T0={t0} (C': {q + _sage_const_1  - nCp})")
    sys.stdout.flush()
print("conventions:", "PASS" if convOK else "FAIL")

SQ = PolynomialRing(QQ, 'T')
units = {K(_sage_const_1 ): "+1", K(-_sage_const_1 ): "-1", w: "+w", -w: "-w", w ** _sage_const_2 : "+w^2", -w ** _sage_const_2 : "-w^2"}
pieces = {}
for j, name, dim in [(_sage_const_1 , "B6 (chi-primitive, NON-SPLIT candidate)", _sage_const_6 ),
                     (_sage_const_2 , "B3 (mu_3 control)", _sage_const_6 ),
                     (_sage_const_3 , "B2 (Z/2-Prym)", _sage_const_6 )]:
    f, e = newton_charpoly(T[j], _sage_const_6 )
    integral = all(c.is_integral() for c in f.coefficients())
    fbar = f.map_coefficients(lambda c: c.conjugate())
    rts = [CDF(rr[_sage_const_0 ]) for rr in f.change_ring(CDF).roots()]
    pure = all(abs(abs(r0) ** _sage_const_2  / p - _sage_const_1 ) < _sage_const_1en6  for r0 in rts)
    print("=" * _sage_const_64 )
    print(f"rail j={j}: {name}")
    print("f =", f)
    print("integral:", "PASS" if integral else "FAIL", "| purity:",
          "PASS" if pure else "FAIL")
    e6c = e[_sage_const_6 ]
    r = e6c / p ** _sage_const_3 
    if r in units:
        print(f"*** FREEZE: r = e_6/p^3 = {units[K(r)]}")
    else:
        rn = CDF(K(r).complex_embedding())
        print(f"no mu_6 freeze: |r| = {abs(rn):.6f}, arg/(pi/3) = "
              f"{rn.arg() / (pi / _sage_const_3 ).n():.4f}")
    if j == _sage_const_3 :
        selfc = (f == fbar)
        print("self-conjugate (rational):", "PASS" if selfc else "FAIL")
        PB = SQ([QQ(c) for c in f.list()]) if selfc else None
    else:
        PB = SQ([QQ(c) for c in (f * fbar).list()])
    if PB is not None:
        fac = PB.factor()
        irr = len(list(fac)) == _sage_const_1  and fac[_sage_const_0 ][_sage_const_1 ] == _sage_const_1 
        print(f"P_piece deg {PB.degree()}: factor = {fac}")
        print("SIMPLE:", "YES (irreducible at split p=7)" if irr else "no/inspect")
    pieces[j] = PB
    sys.stdout.flush()

