

# This file was *autogenerated* from the file tmp/petri_t1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_24 = Integer(24); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9)# T1 stage 1: section-space engine for the v2 tower + THE DIMENSION GATE.
#
# Tower: E0: y^2+2xy+y = x^3;  C: u^3 + x*u + (y+1) = 0 (genus 4);  C~: t^3 = y
# (etale mu_3, genus 10).  sigma: t -> zeta t.
#
# H^0(omega_C~) = (+)_j t^j * (g/F_u) * pi^*omega0, F_u = 3u^2+x, omega0 = the
# invariant differential of E0 (div pi^* omega0 = R = ramification divisor of C/E0;
# div((1/F_u) pi^*omega0) = 2*(O-fiber) as computed: conditions at O/T/T' fibers ONLY).
# Eigenspace j condition: div(g) + 2*(O-fiber) + j*(T-fiber) - j*(O-fiber... sign:
#   eta_j = t^j (g/F_u) omega0 regular <=> for each C~-place P over base place Q:
#   e*v_series(g at Q-branch) + [shift(P; i-grade of monomial, j)] >= 0,
#   with shift = i*v(u) + j*v(t) + v(1/F_u * omega0) at that branch.
# GATE: dims must land 4 / 3 / 3 (total 10 = 2*10 - 2... = g~).
#
# Series engine: exact Laurent expansions over F_{7^6} (all branch residues rational)
# to order NTRUNC; u-branches by Hensel on the cubic; t-branches by cube roots.

F = GF(_sage_const_7 **_sage_const_6 , 'g')
NTRUNC = _sage_const_24 
R = LaurentSeriesRing(F, default_prec=NTRUNC, names=('s',)); (s,) = R._first_ngens(1)


def e0_series():
    """Laurent series of (x, y) at the E0-places O, T, T' with uniformizer s."""
    out = {}
    # T = (0,0): uniformizer x = s; y = s^3*(series): y(y+2x+1) = x^3 =>
    # y = x^3/(1+2x+y): iterate.
    y = s**_sage_const_3 
    for _ in range(NTRUNC + _sage_const_2 ):
        y = s**_sage_const_3  / (_sage_const_1  + _sage_const_2 *s + y)
    out['T'] = (s + O(s**NTRUNC), y + O(s**NTRUNC))
    # T' = (0,-1): x = s; y = -1 + w, w(w-1+2s... ) solve G: (w-1)^2+2s(w-1)+(w-1)
    # -s^3 = 0 -> w^2 - w + 2sw - 2s - s^3 = 0 => w = (2s + s^3 + w^2 + 2sw... )
    # iterate w = 2s + s^3 - 2*s*w + ... from w^2 - (1-2s) w + ... rearranged:
    # w = (2s + s^3 + w^2)/(1 - 2s)?? derive: G(x,-1+w) = (-1+w)^2 + 2x(-1+w)
    # + (-1+w) - x^3 = 1 - 2w + w^2 - 2x + 2xw - 1 + w - x^3 = w^2 + w(2x - 1)
    # - 2x - x^3. So w = (2x + x^3 - w^2)/(2x - 1)*(-1)... w(2x-1) = 2x + x^3 - w^2
    # => w = (2x + x^3 - w^2)/(2x - 1).
    w = _sage_const_0 *s
    for _ in range(NTRUNC + _sage_const_2 ):
        w = (_sage_const_2 *s + s**_sage_const_3  - w**_sage_const_2 ) / (_sage_const_2 *s - _sage_const_1 )
    out['Tp'] = (s + O(s**NTRUNC), -_sage_const_1  + w + O(s**NTRUNC))
    # O: x = s^-2 * X, y = s^-3 * Y with X,Y units; standard: set x = 1/s^2 + a1/s
    # + ...: iterate curve for y ~ -? choose y-leading: y^2 ~ x^3 => y = ±s^-3(1+..).
    # Parametrize by z = x/y (uniformizer at O): x = z^-2*(series in z)?? Use:
    # w = -x/y => y = -x/w; plug: x^2/w^2 - 2x^2/w - x/w = x^3 =>
    # x/w^2 - 2x/w - 1/w = x^2 => x^2 - x(1/w^2 - 2/w) + 1/w = 0... messy; instead
    # iterate directly: y = -x/w with w = s (the uniformizer), and curve gives
    # x = (y^2 + 2xy + y)/x^2 ... choose the classical: at O, u0 = x/y has a simple
    # zero; x = u0^{-2}*h, y = u0^{-3}*h for SOME common h: from y = x/u0:
    # x^2/u0^2 + 2x^2/u0 + x/u0 = x^3 => 1/u0^2 + 2x/u0... divide x^2:
    # (1/u0^2) + (2/u0)x/x... redo: y = x/u0: G: x^2/u0^2 + 2x*x/u0 + x/u0 - x^3 = 0
    # divide by x: x/u0^2 + 2x/u0*... => x/u0^2 + 2x^2/u0 + 1/u0 = x^2?? checking:
    # (x/u0)^2 = x^2/u0^2: G = x^2/u0^2 + 2x^2/u0 + x/u0 - x^3 = 0; divide x^2:
    # 1/u0^2 + 2/u0 + 1/(x u0) = x. So x = 1/u0^2 + 2/u0 + 1/(x*u0): iterate x.
    xO = s**-_sage_const_2 
    for _ in range(NTRUNC + _sage_const_4 ):
        xO = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xO*s)
    yO = xO/s
    out['O'] = (xO + O(s**(NTRUNC-_sage_const_4 )), yO + O(s**(NTRUNC-_sage_const_5 )))
    return out


def cubic_branches(xs, ys):
    """Branches of u^3 + x*u + (y+1) = 0 over a base place, as Laurent series:
    Newton-polygon slopes, leading equation solved over F, then Hensel."""
    B = ys + _sage_const_1 
    vx, vB = xs.valuation(), B.valuation()
    ax = xs.coefficients()[_sage_const_0 ]
    aB = B.coefficients()[_sage_const_0 ]
    branches = []
    for v in range(-_sage_const_6 , _sage_const_7 ):
        vals = [_sage_const_3 *v, v + vx, vB]
        m = min(vals)
        idx = [k for k in range(_sage_const_3 ) if vals[k] == m]
        if len(idx) < _sage_const_2 :
            continue
        P = PolynomialRing(F, names=('cc',)); (cc,) = P._first_ngens(1)
        poly = P(_sage_const_0 )
        if _sage_const_0  in idx:
            poly += cc**_sage_const_3 
        if _sage_const_1  in idx:
            poly += ax*cc
        if _sage_const_2  in idx:
            poly += aB
        for c, _ in poly.roots():
            if c == _sage_const_0 :
                continue
            u = c * s**v
            for _ in range(NTRUNC + _sage_const_4 ):
                fu = u**_sage_const_3  + xs*u + B
                if fu == _sage_const_0 :
                    break
                dfu = _sage_const_3 *u**_sage_const_2  + xs
                u = u - fu/dfu
            res = u**_sage_const_3  + xs*u + B
            if res != _sage_const_0  and res.valuation() < NTRUNC - _sage_const_8 :
                continue
            new = True
            for b in branches:
                d = u - b
                if d == _sage_const_0  or d.valuation() >= NTRUNC//_sage_const_2 :
                    new = False
            if new:
                branches.append(u)
    return branches


def cube_root_series(ys):
    """One cube root of the series ys over F (leading coeff root via polynomial)."""
    v = ys.valuation()
    assert v % _sage_const_3  == _sage_const_0 
    lead = ys.coefficients()[_sage_const_0 ]
    P = PolynomialRing(F, names=('z',)); (z,) = P._first_ngens(1)
    rts = (z**_sage_const_3  - lead).roots()
    if not rts:
        return None
    t = rts[_sage_const_0 ][_sage_const_0 ] * s**(v//_sage_const_3 )
    for _ in range(NTRUNC + _sage_const_4 ):
        ft = t**_sage_const_3  - ys
        if ft == _sage_const_0 :
            break
        t = t - ft/(_sage_const_3 *t**_sage_const_2 )
    return t


print("building E0 series...", flush=True)
E0S = e0_series()
for pl in ('T', 'Tp', 'O'):
    xs, ys = E0S[pl]
    res = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
    rv = 'exact0' if res == _sage_const_0  else res.valuation()
    print(f"  {pl}: v(x)={xs.valuation()} v(y)={ys.valuation()} "
          f"v(y+1)={(ys+_sage_const_1 ).valuation()} curve-residual v={rv}", flush=True)

print("u-branches per place (T' via ramified substitution s = sigma^3):", flush=True)
UB, RAMD = {}, {}
for pl in ('T', 'Tp', 'O'):
    xs, ys = E0S[pl]
    br = cubic_branches(xs, ys)
    e = _sage_const_1 
    if len(br) == _sage_const_0 :            # fractional slopes: ramified place, re-expand
        xs, ys = xs.V(_sage_const_3 ), ys.V(_sage_const_3 )
        br = cubic_branches(xs, ys)
        e = _sage_const_3 
        E0S[pl] = (xs, ys)      # store sigma-level series for this place
    UB[pl] = br
    RAMD[pl] = e
    print(f"  {pl}: e={e}, {len(br)} branch series, v(u) = "
          f"{[b.valuation() for b in br]}", flush=True)

print("t-branches (cube roots of y):", flush=True)
TB = {}
for pl in ('T', 'Tp', 'O'):
    xs, ys = E0S[pl]
    tb = cube_root_series(ys)
    TB[pl] = tb
    print(f"  {pl}: v(t) = {tb.valuation() if tb is not None else 'IRR'}", flush=True)

# ---------------- stage 2: the dimension gate for H^0(omega_C~) ----------------
# eta_j = t^j * (g / F_u) * pi^* omega0,  g = sum_i a_i(x,y) u^i.
# Regularity per branch:  v(g-expansion) >= j*v(t) ... rearranged:
#   v(g) + j*v(t) - v(F_u) + v(omega0) >= 0.
# omega0 = dx/(2y+2x+1): v = 0 at T/O-branches; v_sigma = 2 at the ramified T'.
# function-field basis discipline: K(E0) = span{x^p, y x^p} -- q in {0,1} ONLY
# (q = 2 monomials reduce via the curve relation and pollute the kernel).
MONS = [(p, q) for p in range(-_sage_const_3 , _sage_const_5 ) for q in range(_sage_const_0 , _sage_const_2 )]


def omega0_val_and_series(pl):
    xs, ys = E0S[pl]
    dx = xs.derivative()
    den = _sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 
    return dx/den


def gate_dimension(j):
    rows = []
    ncols = _sage_const_3 *len(MONS)
    for pl in ('T', 'Tp', 'O'):
        xs, ys = E0S[pl]
        w0 = omega0_val_and_series(pl)
        tb = TB[pl]
        for ub in UB[pl]:
            Fu = _sage_const_3 *ub**_sage_const_2  + xs
            pref = (tb**j) * w0 / Fu
            # eta = g * pref must be regular: expansion coefficients of negative
            # orders vanish.  Collect condition rows down to order -1.
            colblocks = []
            minv = _sage_const_10 **_sage_const_9 
            series_list = []
            for i in range(_sage_const_3 ):
                for (p, q) in MONS:
                    ser = (xs**p) * (ys**q) * (ub**i) * pref
                    series_list.append(ser)
                    minv = min(minv, ser.valuation())
            if minv >= _sage_const_0 :
                continue
            for order in range(minv, _sage_const_0 ):
                row = [ser[order] for ser in series_list]
                rows.append(row)
    M = matrix(F, rows)
    return ncols - M.rank()


for j in range(_sage_const_3 ):
    d = gate_dimension(j)
    print(f"GATE: dim eigenspace j={j}: {d} (expect {_sage_const_4  if j == _sage_const_0  else _sage_const_3 })",
          flush=True)

