

# This file was *autogenerated* from the file psl27_verdict.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_168 = Integer(168); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13)# THE PSL(2,7) VERDICT (2026-07-28): etale PSL(2,7)-cover of a genus-2 curve;
# the 3-dim irrep packet (char field EXACTLY Q(sqrt-7)) gives a Weil-type
# SIXFOLD B, signature (3,3)/Q(sqrt-7) (Chevalley-Weil balance, etale), from a
# SIMPLE group -- outside Patel-Zhang entirely. K = Q(sqrt-7): 2 SPLITS,
# 3 and 5 are INERT. Verdict: Pfaffian of the multiplicity-one slice lattice
# (H = Z/3: dim chi^H = 1); ODD v_3 or v_5 => disc not a norm => NON-SPLIT
# Weil sixfold class = the beyond-everything frontier object.
# Model: triple-gated cut-glue (Lange-Ortega x2 + house mu6).
from sage.all import matrix, identity_matrix, ZZ, block_matrix, libgap
import json

G = libgap.PSL(_sage_const_2 , _sage_const_7 )
els = list(G.Elements())
n = len(els)
assert n == _sage_const_168 
idx = {str(e): i for i, e in enumerate(els)}
tbl = G.CharacterTable()
irr = tbl.Irr()
classes = tbl.ConjugacyClasses()
elcls = []
for e in els:
    for ci, c in enumerate(classes):
        if e in c.AsList():
            elcls.append(ci)
            break
# the 3-dim packet: the two conjugate degree-3 characters
chi3s = [chi for chi in irr if int(chi[_sage_const_0 ]) == _sage_const_3 ]
assert len(chi3s) == _sage_const_2 
psi = []   # rational packet char values per element
for i in range(n):
    v = chi3s[_sage_const_0 ][elcls[i]] + chi3s[_sage_const_1 ][elcls[i]]
    psi.append(int(v))
print("packet char values (distinct):", sorted(set(psi)), flush=True)

gbase = _sage_const_2 
H = gbase - _sage_const_1 
N = _sage_const_2  * H * n + _sage_const_2 
E = matrix(ZZ, N, N)
for i in range(n):
    E[i, n + i] = _sage_const_1 
    E[n + i, i] = -_sage_const_1 
E[N-_sage_const_2 , N-_sage_const_1 ] = _sage_const_1 ; E[N-_sage_const_1 , N-_sage_const_2 ] = -_sage_const_1 

def act(kk):
    M = matrix(ZZ, N, N)
    for gi, ge in enumerate(els):
        t = idx[str(kk * ge)]
        M[t, gi] = _sage_const_1 
        M[n + t, n + gi] = _sage_const_1 
    M[N-_sage_const_2 , N-_sage_const_2 ] = _sage_const_1 ; M[N-_sage_const_1 , N-_sage_const_1 ] = _sage_const_1 
    return M

print("building projector...", flush=True)
Pnum = matrix(ZZ, N, N)
for gi, ge in enumerate(els):
    if psi[gi] != _sage_const_0 :
        Pnum += psi[gi] * act(ge)
scale = n // _sage_const_3           # e_packet = (3/168) sum psi(g^{-1}) g ; psi symmetric
M_iso = scale * identity_matrix(ZZ, N) - Pnum
print("isotypic kernel...", flush=True)
Lam = M_iso.right_kernel().basis_matrix()
print("iso rank:", Lam.nrows(), "(expect 36 = H1(B^3))", flush=True)

# multiplicity-one slice: H0 = Z/3 (chi3 restricted = 1 + omega + omegabar)
z3gen = None
for e in els:
    if int(libgap.Order(e)) == _sage_const_3 :
        z3gen = e
        break
Mz = act(z3gen) - identity_matrix(ZZ, N)
stack = block_matrix(ZZ, [[M_iso], [Mz]])
B = stack.right_kernel().basis_matrix()
print("slice rank:", B.nrows(), "(expect 12 = H1 of the sixfold)", flush=True)
Gram = B * E * B.T
eds = [x for x in Gram.elementary_divisors() if x != _sage_const_0 ]
pairs = eds[::_sage_const_2 ]
assert eds[_sage_const_1 ::_sage_const_2 ] == pairs, f"SNF pairing anomaly {eds}"
pf = ZZ(_sage_const_1 )
for x in pairs:
    pf *= x
vals = {str(p): int(pf.valuation(p)) for p in (_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 ) if pf % p == _sage_const_0 }
odd_inert = {p: v for p, v in [("3", pf.valuation(_sage_const_3 )), ("5", pf.valuation(_sage_const_5 ))]
             if v % _sage_const_2  == _sage_const_1 }
rec = {"group": "PSL(2,7)", "g": _sage_const_2 , "packet": "3+3bar (field Q(sqrt-7))",
       "slice": "Z/3-invariants", "rank": int(B.nrows()),
       "type": [int(x) for x in pairs], "Pf": int(pf), "valuations": vals,
       "odd_at_K_inert(3,5)": {k: int(v) for k, v in odd_inert.items()}}
print(rec, flush=True)
verdict = "NON-SPLIT CLASS FOUND" if odd_inert else "split again (null)"
print("VERDICT:", verdict, flush=True)
with open("psl27_verdict.json", "w") as fh:
    json.dump(rec, fh)
print("PSL27 DONE", flush=True)

