

# This file was *autogenerated* from the file radial_torelli_g2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_120 = Integer(120); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_14 = Integer(14); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12)# Radial-Torelli rung, genus 2: periods -> FIREWALL(tau) -> theta constants
# -> branch-point invariants, gated exactly against the curve.
# Convention-free design: the gate invariants are Sp4(Z)-invariant sign-free
# theta functionals p2/p1^2, p3/p1^3, q10/p1^10 (power sums/product of the
# ten even theta^8's); by Thomae theta_S^8 ~ c^2 * T_S with T_S the SQUARED
# 3+3 partition product of branch differences (signs die in the square, the
# scale dies in ratios, Moebius dies by uniform weight) — so the true side
# computes the same rationals directly from the roots, projectively.

from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface
from itertools import combinations

PREC = _sage_const_120 
C = ComplexField(PREC)
R = QQ['x']; (x,) = R._first_ngens(1)

CURVES = {
    'g2a (rosenhain 2,3,5)': x*(x-_sage_const_1 )*(x-_sage_const_2 )*(x-_sage_const_3 )*(x-_sage_const_5 ),
    'g2b (quintic)':         x**_sage_const_5  - x + _sage_const_1 ,
    'g2c (sextic)':          x**_sage_const_6  + x + _sage_const_3 ,
}


def proj_roots(f):
    """Projective roots (alpha:beta) of the degree-6 binary form; adds
    infinity for quintics."""
    rts = f.roots(ComplexField(PREC + _sage_const_60 ), multiplicities=False)
    pts = [(C(r), C(_sage_const_1 )) for r in rts]
    if f.degree() == _sage_const_5 :
        pts.append((C(_sage_const_1 ), C(_sage_const_0 )))
    assert len(pts) == _sage_const_6 
    return pts


def true_invariants(f):
    pts = proj_roots(f)
    def d(i, j):
        (a1, b1), (a2, b2) = pts[i], pts[j]
        return a1*b2 - a2*b1
    Ts = []
    for S in combinations(range(_sage_const_6 ), _sage_const_3 ):
        if _sage_const_0  not in S:
            continue                      # each partition once (fix 0 in S)
        Sc = tuple(k for k in range(_sage_const_6 ) if k not in S)
        prod = C(_sage_const_1 )
        for (i, j) in combinations(S, _sage_const_2 ):
            prod *= d(i, j)
        for (i, j) in combinations(Sc, _sage_const_2 ):
            prod *= d(i, j)
        Ts.append(prod**_sage_const_2 )
    assert len(Ts) == _sage_const_10 
    p1 = sum(Ts)
    p2 = sum(t**_sage_const_2  for t in Ts)
    p3 = sum(t**_sage_const_3  for t in Ts)
    q  = prod_list(Ts)
    return [p2/p1**_sage_const_2 , p3/p1**_sage_const_3 , q/p1**_sage_const_10 ]


def prod_list(L):
    out = C(_sage_const_1 )
    for t in L:
        out *= t
    return out


def theta_consts(tau):
    """The ten even genus-2 theta constants theta[a,b](0, tau)."""
    N = _sage_const_14 
    out = []
    for a1 in (_sage_const_0 , _sage_const_1 ):
        for a2 in (_sage_const_0 , _sage_const_1 ):
            for b1 in (_sage_const_0 , _sage_const_1 ):
                for b2 in (_sage_const_0 , _sage_const_1 ):
                    if (a1*b1 + a2*b2) % _sage_const_2  != _sage_const_0 :
                        continue          # odd characteristic
                    aa = (C(a1)/_sage_const_2 , C(a2)/_sage_const_2 )
                    bb = (C(b1)/_sage_const_2 , C(b2)/_sage_const_2 )
                    s = C(_sage_const_0 )
                    for n1 in range(-N, N+_sage_const_1 ):
                        for n2 in range(-N, N+_sage_const_1 ):
                            m1, m2 = C(n1) + aa[_sage_const_0 ], C(n2) + aa[_sage_const_1 ]
                            quad = m1*(tau[_sage_const_0 ][_sage_const_0 ]*m1 + tau[_sage_const_0 ][_sage_const_1 ]*m2)                                  + m2*(tau[_sage_const_1 ][_sage_const_0 ]*m1 + tau[_sage_const_1 ][_sage_const_1 ]*m2)
                            lin = m1*bb[_sage_const_0 ] + m2*bb[_sage_const_1 ]
                            s += (C(pi)*C.gen(0)*quad + _sage_const_2 *C(pi)*C.gen(0)*lin).exp()
                    out.append(s)
    assert len(out) == _sage_const_10 
    return out


def reconstructed_invariants(tau):
    th8 = [t**_sage_const_8  for t in theta_consts(tau)]
    p1 = sum(th8)
    p2 = sum(t**_sage_const_2  for t in th8)
    p3 = sum(t**_sage_const_3  for t in th8)
    q = prod_list(th8)
    return [p2/p1**_sage_const_2 , p3/p1**_sage_const_3 , q/p1**_sage_const_10 ]


def recognize(v, den_bound=_sage_const_10 **_sage_const_12 ):
    fr = v.real().nearby_rational(max_denominator=den_bound)
    gate = abs(v.real() - fr) < _sage_const_2 **(-PREC//_sage_const_2 ) and abs(v.imag()) < _sage_const_2 **(-PREC//_sage_const_2 )
    return fr, gate


for name, f in CURVES.items():
    S = RiemannSurface(y**_sage_const_2  - f(x) if False else None) if False else None
    RS = RiemannSurface((x**_sage_const_0 *_sage_const_0 ).parent()(_sage_const_0 )) if False else None
    # build surface
    Rxy = PolynomialRing(QQ, ['x', 'y'])
    xv, yv = Rxy.gens()
    fpoly = sum(QQ(c)*xv**i for i, c in enumerate(f.list()))
    RS = RiemannSurface(yv**_sage_const_2  - fpoly, prec=PREC)
    tau = RS.riemann_matrix()
    # internal gates on tau
    sym = max(abs(C(tau[i][j]) - C(tau[j][i])) for i in range(_sage_const_2 ) for j in range(_sage_const_2 ))
    tauC = [[C(tau[_sage_const_0 ][_sage_const_0 ]), C(tau[_sage_const_0 ][_sage_const_1 ])], [C(tau[_sage_const_1 ][_sage_const_0 ]), C(tau[_sage_const_1 ][_sage_const_1 ])]]
    # ---------------- FIREWALL: only tauC crosses ----------------
    rec = reconstructed_invariants(tauC)
    tru = true_invariants(f)
    ok_all = True
    lines = []
    tol = RealField(PREC)(_sage_const_2 )**(-_sage_const_2 *PREC//_sage_const_3 )
    for k in range(_sage_const_3 ):
        # primary gate: the two arms agree at ~80-bit relative precision
        diff = abs(rec[k] - tru[k]) / (_sage_const_1  + abs(tru[k]))
        match = diff < tol
        ok_all = ok_all and match
        fr_r, g_r = recognize(rec[k])
        tag = f"= {fr_r} (rational)" if g_r else f"(agree to {diff:.1e})"
        lines.append(f"    I{k+_sage_const_1 }: {'MATCH' if match else 'MISMATCH'} {tag}")
    print(f"{name}: tau-sym {sym:.1e}  ->  "
          f"{'EXACT MATCH (all 3 invariants)' if ok_all else 'MISMATCH'}",
          flush=True)
    for ln in lines:
        print(ln, flush=True)

