

# This file was *autogenerated* from the file siegel_corridor.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_200 = Integer(200); _sage_const_30p0 = RealNumber('30.0'); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_3p0 = RealNumber('3.0'); _sage_const_20 = Integer(20); _sage_const_0p999 = RealNumber('0.999'); _sage_const_39 = Integer(39); _sage_const_40 = Integer(40); _sage_const_1p0000001 = RealNumber('1.0000001'); _sage_const_0p01 = RealNumber('0.01'); _sage_const_0p06 = RealNumber('0.06'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_120 = Integer(120)# hunt-spec 2026-07-26, session 18a3f704 — Campaign 1, round-1 driver
# Siegel-corridor audit over real primitive characters chi_d, d fundamental.
#   Arm A (Siegel box): sign changes of L(sigma, chi_d) on the real segment
#     [max(1/2, 1 - 3/log q), 0.999]  — any sign change = EVENT (real zero
#     near s=1, the classical exceptional-zero corridor).
#   Arm B (strip audit): count zeros on the line in (0, T] via lcalc vs the
#     main-term census; |count - main| > 2 = FLAG (possible off-line pair /
#     missed zeros / multiplicity) -> manual ladder.
# Telemetry: L(1, chi) (near-exceptional statistic), min |L| on the box grid.
# Round 2 (separate driver): 3D-locator cross-validation of every flag.
import json, sys
from sage.libs.lcalc.lcalc_Lfunction import Lfunction_from_character

DMAX_FULL = int(sys.argv[_sage_const_1 ]) if len(sys.argv) > _sage_const_1  else _sage_const_200 
T_STRIP = _sage_const_30p0 
OUT = f"/Users/samuellavery/work/helix_frobenius/tmp/siegel_round1_D{DMAX_FULL}.jsonl"

def fundamental_discs(limit):
    for n in range(_sage_const_2 , limit + _sage_const_1 ):
        for d in (n, -n):
            if d % _sage_const_4  in (_sage_const_0 , _sage_const_1 ) and d != _sage_const_1  and Integer(d).is_fundamental_discriminant():
                yield d

def main_term(q, T):
    # (T/pi)(log(qT/(2*pi)) - 1) + 1/4-ish; used only as a +-2 audit anchor
    return float((T / (_sage_const_2  * pi)) * (log(q * T / (_sage_const_2  * pi)) - _sage_const_1 ))

events, flags, done = _sage_const_0 , _sage_const_0 , _sage_const_0 
with open(OUT, "w") as fh:
    for d in fundamental_discs(DMAX_FULL):
        q = abs(d)
        try:
            chi = kronecker_character(d)
            L = Lfunction_from_character(chi.primitive_character())
            # --- Arm A: Siegel box grid
            lo = max(_sage_const_0p5 , _sage_const_1p0  - _sage_const_3p0  / float(log(q))) if q > _sage_const_20  else _sage_const_0p5 
            grid = [lo + (_sage_const_0p999  - lo) * k / _sage_const_39  for k in range(_sage_const_40 )]
            vals = [float(L.value(s).real()) for s in grid]
            L1 = float(L.value(_sage_const_1p0000001 ).real())
            signch = sum(_sage_const_1  for a, b in zip(vals, vals[_sage_const_1 :]) if a * b < _sage_const_0 )
            minabs = min(abs(v) for v in vals)
            # --- Arm B: strip census
            zs = L.find_zeros(_sage_const_0p01 , T_STRIP, _sage_const_0p06 )
            nz = len([z for z in zs if _sage_const_0  < float(z) <= T_STRIP])
            mt = main_term(q, T_STRIP)
            dev = nz - mt
            rec = {"d": int(d), "q": int(q), "signch": int(signch),
                   "minabsL_box": minabs, "L1": L1, "n_zeros": int(nz),
                   "main_term": mt, "dev": float(dev)}
            if signch > _sage_const_0 :
                rec["EVENT"] = "siegel-box-sign-change"; events += _sage_const_1 
            if abs(dev) > _sage_const_2p0 :
                rec["FLAG"] = "strip-count-deviation"; flags += _sage_const_1 
            fh.write(json.dumps(rec) + "\n")
        except Exception as e:
            fh.write(json.dumps({"d": int(d), "error": str(e)[:_sage_const_120 ]}) + "\n")
        done += _sage_const_1 
        if done % _sage_const_200  == _sage_const_0 :
            print(f"[{done}] d={d} events={events} flags={flags}", flush=True)
print(f"DONE chars={done} events={events} flags={flags} -> {OUT}", flush=True)

