

# This file was *autogenerated* from the file siegel_pair_confirm.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2551 = Integer(2551); _sage_const_2999 = Integer(2999); _sage_const_3061 = Integer(3061); _sage_const_3288 = Integer(3288); _sage_const_3289 = Integer(3289); _sage_const_3505 = Integer(3505); _sage_const_4737 = Integer(4737); _sage_const_4920 = Integer(4920); _sage_const_5108 = Integer(5108); _sage_const_7673 = Integer(7673); _sage_const_7691 = Integer(7691); _sage_const_7988 = Integer(7988); _sage_const_8103 = Integer(8103); _sage_const_8113 = Integer(8113); _sage_const_9204 = Integer(9204); _sage_const_0p01 = RealNumber('0.01'); _sage_const_30p0 = RealNumber('30.0'); _sage_const_0 = Integer(0); _sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0p002 = RealNumber('0.002')
import json
from sage.libs.lcalc.lcalc_Lfunction import Lfunction_from_character
targets = [-_sage_const_2551 , -_sage_const_2999 , _sage_const_3061 , -_sage_const_3288 , _sage_const_3289 , _sage_const_3505 , _sage_const_4737 , _sage_const_4920 , -_sage_const_5108 , _sage_const_7673 , -_sage_const_7691 , -_sage_const_7988 , -_sage_const_8103 , _sage_const_8113 , -_sage_const_9204 ]
pairs = []
for d in targets:
    chi = kronecker_character(d)
    L = Lfunction_from_character(chi.primitive_character())
    zs = sorted(float(z) for z in L.find_zeros(_sage_const_0p01 , _sage_const_30p0 , _sage_const_0p01 ) if _sage_const_0  < float(z) <= _sage_const_30 )
    gaps = [(zs[i+_sage_const_1 ]-zs[i], zs[i]) for i in range(len(zs)-_sage_const_1 )]
    g, t = min(gaps)
    pairs.append((d, round(g,_sage_const_4 ), round(t,_sage_const_3 )))
    # stability spot-check on the two worst originals
    if d in (-_sage_const_2999 , _sage_const_8113 ):
        zs3 = [z for z in L.find_zeros(_sage_const_0p01 , _sage_const_30p0 , _sage_const_0p002 ) if _sage_const_0  < float(z) <= _sage_const_30 ]
        print(f"  d={d}: fine={len(zs)} ultrafine={len(zs3)} {'STABLE' if len(zs3)==len(zs) else 'STILL MOVING'}")
print("close-pair sites (d, min gap, at t):")
for p in sorted(pairs, key=lambda x: x[_sage_const_1 ]): print(f"  {p}")

