

# This file was *autogenerated* from the file tmp/sixfold_rails.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_12 = Integer(12); _sage_const_32 = Integer(32); _sage_const_93 = Integer(93); _sage_const_184 = Integer(184); _sage_const_753 = Integer(753); _sage_const_1288 = Integer(1288); _sage_const_4557 = Integer(4557); _sage_const_10976 = Integer(10976); _sage_const_28812 = Integer(28812); _sage_const_33614 = Integer(33614); _sage_const_117649 = Integer(117649); _sage_const_13 = Integer(13); _sage_const_58 = Integer(58); _sage_const_285 = Integer(285); _sage_const_1533 = Integer(1533); _sage_const_6046 = Integer(6046); _sage_const_25393 = Integer(25393); _sage_const_78598 = Integer(78598); _sage_const_259077 = Integer(259077); _sage_const_626145 = Integer(626145); _sage_const_1656538 = Integer(1656538); _sage_const_2599051 = Integer(2599051); _sage_const_4826809 = Integer(4826809); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_64 = Integer(64); _sage_const_6 = Integer(6); _sage_const_1en6 = RealNumber('1e-6')# Rail-native reading for the Prym specimens (weil_rails philosophy on OUR objects).
#
# sigma-twisted point counts: for C : t^3 = y over C', at split p (zeta_3 in F_p),
# a point of C over P in C'(F_q) with y != 0 satisfies t^{q-1} = chi(y) := y^{(q-1)/3},
# so all 3 t's over P lie in the single twisted class m with chi(y) = zeta^m.
#   #C_m(F_{q^k}) = sum over C'-points, binned by chi(y)   (T-points: t = 0 in every bin;
#   O-branches: y-leading = -(cube) => bin 0)
# DFT over m (exact, in Q(zeta_3)) splits H^1(C) = H^1(C') + V_omega + V_omegabar:
#   S_m(k) := q^k + 1 - #C_m(q^k) = sum_j zeta^{mj} T_j(k),  T_j(k) = Tr(Frob^k | V_{omega^j})
# Newton on T_1(1..2d) gives the RAIL CHAR POLY f_omega in Z[zeta_3][T] (integrality =
# convention check; f * fbar = P_B = cross-check against the stored tower L-polys).
# THE FREEZE SCALAR (full-support (1,..,1) lane): r = det(Frob | V_omega)/p^{d/1...}:
#   r = e_d / p^{d/2 * 1}  with |r| = 1;  r in mu_6  <=>  FREEZE (Z[zeta_3] units = mu_6:
#   exact integer test e_d in mu_6 * p^{d/2});  the unit = the ORDER LAW reading.
# Method law: report rail phases on the pi/3 (mu_6) harmonic scale, never unit-1.
#
# Specimen here: the SIXFOLD B_{a=1}: C' : u^3 + x*u + (y+1) = 0, rail dim d = 6,
# r = e_6 / p^3.  (Eightfold version follows once its tower lands.)

P_B_KNOWN = {
    _sage_const_7 : [_sage_const_1 , _sage_const_2 , _sage_const_12 , _sage_const_32 , _sage_const_93 , _sage_const_184 , _sage_const_753 , _sage_const_1288 , _sage_const_4557 , _sage_const_10976 , _sage_const_28812 , _sage_const_33614 , _sage_const_117649 ],
    _sage_const_13 : [_sage_const_1 , _sage_const_7 , _sage_const_58 , _sage_const_285 , _sage_const_1533 , _sage_const_6046 , _sage_const_25393 , _sage_const_78598 , _sage_const_259077 , _sage_const_626145 , _sage_const_1656538 ,
         _sage_const_2599051 , _sage_const_4826809 ],
}  # ascending coefficients, from the stored v2 tower logs

K = CyclotomicField(_sage_const_3 , 'w')
w = K.gen()


def zeta_int(p):
    for z in range(_sage_const_2 , p):
        if (z * z + z + _sage_const_1 ) % p == _sage_const_0 :
            return z
    raise ValueError


def twisted_counts(p, k):
    q = p ** k
    assert q % _sage_const_3  == _sage_const_1 
    F = GF(q, 'g')
    R = PolynomialRing(F, 'U')
    U = R.gen()
    z = F(zeta_int(p))
    zpow = [F(_sage_const_1 ), z, z * z]
    e3 = (q - _sage_const_1 ) // _sage_const_3 
    nCp = _sage_const_0 
    Cm = [_sage_const_0 , _sage_const_0 , _sage_const_0 ]
    for x0 in F:
        b = _sage_const_2  * x0 + _sage_const_1 
        D = b * b + _sage_const_4  * x0 ** _sage_const_3 
        if D == _sage_const_0 :
            ys = [-b / _sage_const_2 ]
        elif D.is_square():
            s = D.sqrt()
            ys = [(-b + s) / _sage_const_2 , (-b - s) / _sage_const_2 ]
        else:
            ys = []
        for y0 in ys:
            f = U ** _sage_const_3  + x0 * U + (y0 + _sage_const_1 )
            nu = len(f.roots(multiplicities=False))
            nCp += nu
            if y0 == _sage_const_0 :
                Cm[_sage_const_0 ] += _sage_const_3  * nu          # SMOOTH model: 3 points over T (tau in mu_3,
                                         # each Frob-fixed, sigma permutes) -> bin 0
            else:
                c = y0 ** e3
                m = zpow.index(c)
                Cm[m] += _sage_const_3  * nu
    # O-branches: residual cubic w^3 + w + 1; y-leading = -1, chi(-1) = 1 => bin 0
    nuO = len((U ** _sage_const_3  + U + _sage_const_1 ).roots(multiplicities=False))
    nCp += nuO
    Cm[_sage_const_0 ] += _sage_const_3  * nuO
    return nCp, Cm


def newton_charpoly(T1, d):
    # T1[k-1] = power sums over K; return monic f(T) = T^d - e1 T^{d-1} + ...
    e = [K(_sage_const_1 )] + [K(_sage_const_0 )] * d
    for k in range(_sage_const_1 , d + _sage_const_1 ):
        acc = K(_sage_const_0 )
        for i in range(_sage_const_1 , k + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e[k - i] * T1[i - _sage_const_1 ]
        e[k] = acc / k
    S = PolynomialRing(K, 'T')
    T = S.gen()
    return sum((-_sage_const_1 ) ** j * e[j] * T ** (d - j) for j in range(d + _sage_const_1 )), e


for p in [_sage_const_7 , _sage_const_13 ]:
    print("=" * _sage_const_64 )
    print(f"SIXFOLD RAILS  p = {p}")
    T1 = []
    T0chk = []
    for k in range(_sage_const_1 , _sage_const_7 ):
        nCp, Cm = twisted_counts(p, k)
        q = p ** k
        S = [q + _sage_const_1  - Cm[m] for m in range(_sage_const_3 )]
        okSum = (sum(Cm) == _sage_const_3  * nCp)
        t0 = (S[_sage_const_0 ] + S[_sage_const_1 ] + S[_sage_const_2 ]) / _sage_const_3 
        t1 = (S[_sage_const_0 ] + w ** (-_sage_const_1 ) * S[_sage_const_1 ] + w ** (-_sage_const_2 ) * S[_sage_const_2 ]) / _sage_const_3 
        T0chk.append((t0, q + _sage_const_1  - nCp))
        T1.append(t1)
        print(f"k={k}: #C'={nCp} C_m={Cm} sumcheck={'OK' if okSum else 'FAIL'} "
              f"T0={t0} (C' gives {q + _sage_const_1  - nCp})")
        sys.stdout.flush()
    conv_ok = all(a == b for (a, b) in T0chk)
    print("T0 == C'-trace at all k:", "PASS" if conv_ok else "FAIL (convention!)")
    f, e = newton_charpoly(T1, _sage_const_6 )
    integral = all(c.is_integral() for c in f.coefficients())
    print("rail char poly f_omega(T) =", f)
    print("coefficients integral in Z[zeta_3]:", "PASS" if integral else "FAIL")
    fbar = f.map_coefficients(lambda c: c.conjugate())
    prod = f * fbar
    SQ = PolynomialRing(QQ, 'T')
    prodQ = SQ([QQ(c) for c in prod.list()])
    known = SQ(P_B_KNOWN[p])
    # stored P_B(T) = prod(1 - a_i T) has ascending coeffs; f*fbar = prod(T - a_i):
    # compare with the reversed/monicized version
    knownrev = SQ(list(reversed(P_B_KNOWN[p])))
    match = (prodQ == knownrev)
    print("f * fbar == stored P_B (reciprocal form):", "PASS" if match else "FAIL")
    e6 = e[_sage_const_6 ]
    r = e6 / p ** _sage_const_3 
    print("det(Frob | V_omega) = e_6 =", e6)
    units = {K(_sage_const_1 ): "+1", K(-_sage_const_1 ): "-1", w: "+w", -w: "-w", w ** _sage_const_2 : "+w^2", -w ** _sage_const_2 : "-w^2"}
    if r in units:
        print(f"*** FREEZE: r = e_6/p^3 = {units[K(r)]}  (mu_6 unit; ORDER LAW reading)")
    else:
        rn = CDF(K(r).complex_embedding())
        print(f"no mu_6 freeze at H^1-det level: r = {r}, |r| = {abs(rn):.6f}, "
              f"arg/(pi/3) = {rn.arg() / (pi / _sage_const_3 ).n():.4f}")
    # rail phase spectrum on the mu_6 scale (method law: pi/3 cells, never unit-1)
    rts = [CDF(rr[_sage_const_0 ]) for rr in f.change_ring(CDF).roots()]
    phases = sorted(((r0.arg()) / (pi / _sage_const_3 ).n()) for r0 in rts)
    print("rail phases in units of pi/3:", [f"{ph:.3f}" for ph in phases])
    purity = [abs(abs(r0) ** _sage_const_2  / p - _sage_const_1 ) < _sage_const_1en6  for r0 in rts]
    print("rail purity:", "PASS" if all(purity) else "FAIL")
    sys.stdout.flush()

