

# This file was *autogenerated* from the file thetanull_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_20260719 = Integer(20260719); _sage_const_60 = Integer(60); _sage_const_4000 = Integer(4000); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_200 = Integer(200)# Lemma C reduced-case check for the tower's genus-4 base curve C:
# C: u^3 + x*u + (y+1) = 0 over E0: y^2+2xy+y = x^3.
# g=4 canonical model lies on a unique quadric in P^3; RANK 4 <=> no vanishing
# thetanull <=> h^0(omega - 2N) = 0 for the trigonal pencils <=> Lemma C
# (reduced case) HOLDS for this curve.  Rank 3 (cone) <=> omega = 2N and a
# failing (L, s) is constructible — either way Lemma A gets tested.

load('petri_t1.sage')   # F = GF(7^6), E0S/UB/TB/MONS + gate machinery

# --- rebuild the j=0 condition matrix and take its kernel (the canonical basis)
rows = []
for pl in ('T', 'Tp', 'O'):
    xs, ys = E0S[pl]
    w0 = omega0_val_and_series(pl)
    tb = TB[pl]
    for ub in UB[pl]:
        Fu = _sage_const_3 *ub**_sage_const_2  + xs
        pref = w0 / Fu
        series_list = []
        minv = _sage_const_10 **_sage_const_9 
        for i in range(_sage_const_3 ):
            for (p, q) in MONS:
                ser = (xs**p) * (ys**q) * (ub**i) * pref
                series_list.append(ser)
                minv = min(minv, ser.valuation())
        for order in range(minv, _sage_const_0 ):
            rows.append([ser[order] for ser in series_list])
M = matrix(F, rows)
K = M.right_kernel().basis_matrix()
print(f"canonical basis: dim = {K.nrows()} (expect 4)", flush=True)

# --- sample points of C over F_{7^6} and evaluate the 4 coordinate functions
import random
random.seed(int(_sage_const_20260719 ))
P = PolynomialRing(F, names=('z',)); (z,) = P._first_ngens(1)
pts = []
tried = _sage_const_0 
while len(pts) < _sage_const_60  and tried < _sage_const_4000 :
    tried += _sage_const_1 
    x0 = F.random_element()
    if x0 == _sage_const_0 :
        continue
    yroots = (z**_sage_const_2  + (_sage_const_2 *x0 + _sage_const_1 )*z - x0**_sage_const_3 ).roots()
    if not yroots:
        continue
    y0 = yroots[random.randrange(len(yroots))][_sage_const_0 ]
    uroots = (z**_sage_const_3  + x0*z + (y0 + _sage_const_1 )).roots()
    if not uroots:
        continue
    u0 = uroots[random.randrange(len(uroots))][_sage_const_0 ]
    if _sage_const_3 *u0**_sage_const_2  + x0 == _sage_const_0 :          # avoid ramification of C -> E0
        continue
    pts.append((x0, y0, u0))
print(f"sampled {len(pts)} points of C", flush=True)


def coord(k, pt):
    x0, y0, u0 = pt
    v = F(_sage_const_0 )
    idx = _sage_const_0 
    for i in range(_sage_const_3 ):
        for (p, q) in MONS:
            v += K[k][idx] * x0**p * y0**q * u0**i
            idx += _sage_const_1 
    return v

# --- fit the quadric through the canonical image
qrows = []
for pt in pts:
    zc = [coord(k, pt) for k in range(_sage_const_4 )]
    qrows.append([zc[a]*zc[b] for a in range(_sage_const_4 ) for b in range(a, _sage_const_4 )])
QM = matrix(F, qrows)
kerQ = QM.right_kernel().basis_matrix()
print(f"quadrics through canonical curve: {kerQ.nrows()} (expect 1)", flush=True)

qv = kerQ.row(_sage_const_0 )
S = matrix(F, _sage_const_4 , _sage_const_4 )
idx = _sage_const_0 
for a in range(_sage_const_4 ):
    for b in range(a, _sage_const_4 ):
        if a == b:
            S[a, a] = qv[idx]
        else:
            S[a, b] += qv[idx] / _sage_const_2 
            S[b, a] += qv[idx] / _sage_const_2 
        idx += _sage_const_1 
r = S.rank()
print(f"QUADRIC RANK = {r}  ({'rank 4: NO vanishing thetanull — Lemma C reduced case HOLDS for tower-C' if r == _sage_const_4  else 'CONE: omega = 2N — failing (L,s) constructible, build it and watch ker jump'})", flush=True)

# --- THE FAILURE TEST.  Trigonal pencil = the u-map (u has 3 poles).
# Lemma A predicts: for W = (2 of 3 preimages) over each point of a u-fiber
# E0(c), the Petri kernel on the s-slice = h^0(omega_C - E0(c)) = h^0(N) = 2,
# i.e. the 3 canonical images of a u-fiber are COLLINEAR (rank 2 = cone
# ruling), while 3 random points of C give rank 3.  Kernel jump 1 -> 2 = the
# constructed mu_3-Prym-Petri failure; rank 3 on random triples = the generic
# no-failure control.

def cond_rank(triple):
    rows = [[coord(k, pt) for k in range(_sage_const_4 )] for pt in triple]
    return matrix(F, rows).rank()

print("u-fiber triples (predict rank 2 => ker jumps to 2 = h^0(N)):", flush=True)
tested = _sage_const_0 
ci = _sage_const_0 
while tested < _sage_const_5  and ci < _sage_const_200 :
    ci += _sage_const_1 
    c = F.random_element()
    if c == _sage_const_0 :
        continue
    # fiber {u = c}: y = -(c^3 + c*x + 1) substituted into E0 -> cubic in x
    Rx = PolynomialRing(F, names=('xx',)); (xx,) = Rx._first_ngens(1)
    yy = -(c**_sage_const_3  + c*xx + _sage_const_1 )
    cub = yy**_sage_const_2  + _sage_const_2 *xx*yy + yy - xx**_sage_const_3 
    rts = cub.roots()
    if len(rts) != _sage_const_3 :
        continue
    triple = []
    ok = True
    for (x0, _) in rts:
        y0 = -(c**_sage_const_3  + c*x0 + _sage_const_1 )
        u0 = c
        if x0 == _sage_const_0  or _sage_const_3 *u0**_sage_const_2  + x0 == _sage_const_0 :
            ok = False
            break
        triple.append((x0, y0, u0))
    if not ok:
        continue
    print(f"  c={c}: rank = {cond_rank(triple)}  (ker dim = {_sage_const_4  - cond_rank(triple)})",
          flush=True)
    tested += _sage_const_1 

print("random non-fiber triples (predict rank 3 => ker stays 1 = T only):",
      flush=True)
for trial in range(_sage_const_5 ):
    triple = random.sample(pts, _sage_const_3 )
    if len({p[_sage_const_2 ] for p in triple}) < _sage_const_3 :
        continue
    print(f"  trial {trial}: rank = {cond_rank(triple)}  "
          f"(ker dim = {_sage_const_4  - cond_rank(triple)})", flush=True)

