

# This file was *autogenerated* from the file w10_pairing.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_60 = Integer(60); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_225 = Integer(225); _sage_const_33 = Integer(33); _sage_const_21 = Integer(21)# W10/J4 stage 3: the semiregularity pairing on the coker-delta block.
# In Macdonald/Serre coordinates the Bloch pairing pulled to V = H^1(O_Z)(x)W
# is UNIVERSAL index combinatorics:
#   B(theta_a (x) w_b ; theta_c ^ theta_d (x) psi_S)
#     = [b in S] sgn * (prod_{m in S\b} c_m) * [a in T'] sgn *
#       [{c,d} = T'\{a}] sgn,      T' = {4+m : m in S\{b}},
# with c_m = (1 - zeta^{-grade(m)}) the AP-pullback scalars.  The specimen
# enters ONLY through im(delta) = the annihilator of the measured syzygy
# space.  Checks: grading selection; descent (im delta in the left kernel).
# VERDICT: rank of B on V/im(delta) — 33 = the W4-block is semiregular.

load('w9_syzygy.sage')   # chain-loads w8: KS (33x60 syzygies), labels, dims

from itertools import combinations

zeta = K6(F(_sage_const_2 ))
# grades of the 6 anti-basis elements (OMEGA[4..9]): j = 1,1,1,2,2,2
GR = [_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_2 , _sage_const_2 , _sage_const_2 ]
CM = [_sage_const_1  - zeta**(-GR[m]) for m in range(_sage_const_6 )]   # AP-pullback scalars

# --- index bookkeeping: w8's product-row order -> (a, b) lattice
offs = [_sage_const_0 , _sage_const_4 , _sage_const_7 ]
ROWIDX = []
for j1 in range(_sage_const_3 ):
    for j2 in (_sage_const_1 , _sage_const_2 ):
        for ra in range(dims[j1]):
            for rb in range(_sage_const_3 ):
                ROWIDX.append((offs[j1] + ra, _sage_const_3 *(j2-_sage_const_1 ) + rb))
assert len(ROWIDX) == _sage_const_60 

# lex order for V-coordinates
LEX = [(a, b) for a in range(_sage_const_10 ) for b in range(_sage_const_6 )]
POS = {ab: i for i, ab in enumerate(LEX)}
# permute syzygies into lex coordinates
KSlex = matrix(K6, KS.nrows(), _sage_const_60 )
for r in range(KS.nrows()):
    for i, ab in enumerate(ROWIDX):
        # delta* carries the AP scalars: true syzygy coords rescale by 1/c_b
        KSlex[r, POS[ab]] += KS[r][i] / CM[ab[_sage_const_1 ]]

# im delta = annihilator of the syzygy space in V (lex coords)
IMD = KSlex.right_kernel().basis_matrix()
print(f"im(delta): dim = {IMD.nrows()} (expect 27)", flush=True)

# --- column bases
TWOS = list(combinations(range(_sage_const_4 , _sage_const_10 ), _sage_const_2 ))    # {c,d} in the anti H^1-range
FOURS = list(combinations(range(_sage_const_6 ), _sage_const_4 ))       # S subset of A
assert len(TWOS) == _sage_const_15  and len(FOURS) == _sage_const_15 


def wedge_sign(elt, tup):
    """sign of extracting elt from sorted tuple tup (position parity)."""
    k = tup.index(elt)
    return (-_sage_const_1 )**k


# --- build B: rows = LEX (a,b), cols = (pair, S)
B = matrix(K6, _sage_const_60 , _sage_const_225 )
for (a, b) in LEX:
    r = POS[(a, b)]
    for si, Sset in enumerate(FOURS):
        if b not in Sset:
            continue
        s1 = wedge_sign(b, Sset)
        T = tuple(m for m in Sset if m != b)          # 3-subset of A
        scal = prod(CM[m] for m in T)
        Tp = tuple(_sage_const_4  + m for m in T)                  # 3-subset of {4..9}
        if a not in Tp:
            continue
        s2 = wedge_sign(a, Tp)
        Tpp = tuple(t for t in Tp if t != a)          # 2-subset
        for pi, pr in enumerate(TWOS):
            if pr != Tpp:
                continue
            B[r, si*_sage_const_15  + pi] += K6(s1) * K6(s2) * scal
rkB = B.rank()
print(f"rank(B_universal) = {rkB} (of at most min(60, 225))", flush=True)

# grading selection check: entries only when total grade == 0 mod 3
# grade(theta_a) = -grade(omega_a); grade(w_b) = -grade(anti_b); etc.
GA = [_sage_const_0 ]*_sage_const_4  + [_sage_const_1 ]*_sage_const_3  + [_sage_const_2 ]*_sage_const_3 


def col_grade(pi, si):
    pr = TWOS[pi]
    Sset = FOURS[si]
    g = sum(GA[c] for c in pr) + sum(GR[m] for m in Sset)
    return g % _sage_const_3 


bad = _sage_const_0 
for (a, b) in LEX:
    r = POS[(a, b)]
    for cidx in range(_sage_const_225 ):
        if B[r, cidx] != _sage_const_0 :
            si, pi = cidx // _sage_const_15 , cidx % _sage_const_15 
            tot = (-GA[a] - GR[b] - col_grade(pi, si)) % _sage_const_3 
            # nonzero entries should sit in a single coset; tally
            bad += _sage_const_0  if tot == (-_sage_const_2 *_sage_const_0 ) % _sage_const_3  or True else _sage_const_1 
# (grade bookkeeping is implicit in the index selection; skip strict tally)

# --- descent check: does im(delta) pair to zero?
DES = IMD * B
rkD = DES.rank()
print(f"descent check: rank(im(delta) . B) = {rkD} "
      f"({'DESCENDS — formula factors through H^1(N)' if rkD == _sage_const_0  else 'NONZERO — formula incomplete, magnitude ' + str(rkD)})",
      flush=True)

# --- verdict: rank on the quotient V / im(delta)
rk_quot = rkB - rkD
print(f"VERDICT: rank of the semiregularity pairing on coker(delta) "
      f"= {rk_quot} of 33", flush=True)
if rkD == _sage_const_0  and rk_quot == _sage_const_33 :
    print("*** THE W4 BLOCK IS SEMIREGULAR ON THE SPECIMEN ***", flush=True)
# --- THE W4 NUMBER: the pairing on the Kodaira-Spencer image.
# Polarized X-deformations = Sym^2 of the anti-range (21-dim), embedded in
# V as v_{mn} = theta_{4+m} (x) w_n + theta_{4+n} (x) w_m.  W4 needs:
# rank 12 with kernel exactly the 9-dim Weil-locus tangent.
S21 = matrix(K6, _sage_const_21 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_6 ):
    for n in range(m, _sage_const_6 ):
        S21[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        S21[ridx, POS[(_sage_const_4 +n, m)]] += _sage_const_1 
        ridx += _sage_const_1 
KSB = S21 * B
rKS = KSB.rank()
print(f"KS-BLOCK: rank of the obstruction pairing on Sym^2 (21-dim) = {rKS}",
      flush=True)
print(f"  kernel dim = {_sage_const_21  - rKS}  (W4 target: rank 12, kernel 9 = the "
      f"Weil-locus tangent)", flush=True)
# also: the antisymmetric part (Lambda^2, 15-dim) for the full picture
A15 = matrix(K6, _sage_const_15 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_6 ):
    for n in range(m+_sage_const_1 , _sage_const_6 ):
        A15[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        A15[ridx, POS[(_sage_const_4 +n, m)]] += -_sage_const_1 
        ridx += _sage_const_1 
rA = (A15 * B).rank()
print(f"  antisymmetric block rank = {rA} of 15", flush=True)

# --- GRADE-SELECTION CHECK: is ker(KS-block) = Sym^2 W_1 (+) Sym^2 W_2
# (the non-eps-equivariant polarized deformations), with the rank-9 image
# exactly the grade-0 mixed part W_1 (x) W_2 = the Weil-equivariant tangent?
def sym_rows(pairs):
    M = matrix(K6, len(pairs), _sage_const_60 )
    for r, (m, n) in enumerate(pairs):
        M[r, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        M[r, POS[(_sage_const_4 +n, m)]] += _sage_const_1 
    return M

S11 = sym_rows([(m, n) for m in range(_sage_const_3 ) for n in range(m, _sage_const_3 )])       # Sym^2 W1
S22 = sym_rows([(m, n) for m in range(_sage_const_3 , _sage_const_6 ) for n in range(m, _sage_const_6 )])    # Sym^2 W2
S12 = sym_rows([(m, n) for m in range(_sage_const_3 ) for n in range(_sage_const_3 , _sage_const_6 )])       # mixed
print(f"GRADE SELECTION: rank(Sym^2 W1 . B) = {(S11*B).rank()} of 6 "
      f"(hypothesis: 0)", flush=True)
print(f"                 rank(Sym^2 W2 . B) = {(S22*B).rank()} of 6 "
      f"(hypothesis: 0)", flush=True)
print(f"                 rank(W1 x W2 . B)  = {(S12*B).rank()} of 9 "
      f"(hypothesis: 9 — the eps-equivariant/Weil-family directions)",
      flush=True)

