

# This file was *autogenerated* from the file w12_intrinsic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_18 = Integer(18); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_21 = Integer(21)# W12: upgrade the r=3 scan hit to an intrinsic law:
#   im(delta) ∩ (mixed KS-span, 18-dim)  =?  the r=3 twisted space (9-dim)
# If dim = 9 exactly, the Weil tangent = im(delta) ∩ mixed — no convention.
load('w10_pairing.sage')
M18 = matrix(K6, _sage_const_18 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_3 ):
    for n in range(_sage_const_3 , _sage_const_6 ):
        M18[ridx, POS[(_sage_const_4 +m, n)]] = _sage_const_1 ; ridx += _sage_const_1 
        M18[ridx + _sage_const_8 , POS[(_sage_const_4 +n, m)]] = _sage_const_1 
for m in range(_sage_const_3 ):          # fix indexing: build cleanly instead
    pass
M18 = matrix(K6, _sage_const_18 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_3 ):
    for n in range(_sage_const_3 , _sage_const_6 ):
        M18[ridx, POS[(_sage_const_4 +m, n)]] = _sage_const_1 ; ridx += _sage_const_1 
for m in range(_sage_const_3 ):
    for n in range(_sage_const_3 , _sage_const_6 ):
        M18[ridx, POS[(_sage_const_4 +n, m)]] = _sage_const_1 ; ridx += _sage_const_1 
rM, rI = M18.rank(), IMD.rank()
rU = M18.stack(IMD).rank()
inter = rM + rI - rU
print(f"dim(mixed span) = {rM}, dim(im delta) = {rI}, dim(union) = {rU}")
print(f"dim(im delta ∩ mixed) = {inter}   (intrinsic Weil tangent; scan said 9)")
# and the full 21-dim polarized-KS space for completeness:
S21 = matrix(K6, _sage_const_21 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_6 ):
    for n in range(m, _sage_const_6 ):
        S21[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        S21[ridx, POS[(_sage_const_4 +n, m)]] += _sage_const_1 
        ridx += _sage_const_1 
print(f"dim(im delta ∩ naive-Sym21) = {S21.rank() + rI - S21.stack(IMD).rank()}")

