

# This file was *autogenerated* from the file w13_thetacube.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_21 = Integer(21); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_15 = Integer(15); _sage_const_9 = Integer(9)# W13: the lambda*Theta^3 closure test.  The universal rigidity law says
# [Z] = lambda Theta^3; Theta stays (1,1) on every POLARIZED deformation,
# so the class-variation pi(ob(v)) must vanish on the ENTIRE true-polarized
# KS-image (twisted-mixed r=3 (+) pure-sym, 21-dim) and be nonzero exactly
# where Theta moves (polarization-breaking Lambda^2 directions).
load('w10_pairing.sage')
r = _sage_const_3 
# true-polarized image: twisted-sym mixed (9) + pure-sym (12)
TP = matrix(K6, _sage_const_21 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_3 ):
    for n in range(_sage_const_3 , _sage_const_6 ):
        TP[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        TP[ridx, POS[(_sage_const_4 +n, m)]] += r
        ridx += _sage_const_1 
for blk in (range(_sage_const_3 ), range(_sage_const_3 , _sage_const_6 )):
    for m in blk:
        for n in blk:
            if n < m: continue
            TP[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
            TP[ridx, POS[(_sage_const_4 +n, m)]] += _sage_const_1 
            ridx += _sage_const_1 
print(f"PREDICTION 1: rank(B on true-polarized 21) = {(TP*B).rank()}  (lambda-Theta^3 law demands 0)")
# polarization-breaking image: twisted-anti mixed (9) + pure-anti (6)
NP = matrix(K6, _sage_const_15 , _sage_const_60 )
ridx = _sage_const_0 
for m in range(_sage_const_3 ):
    for n in range(_sage_const_3 , _sage_const_6 ):
        NP[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
        NP[ridx, POS[(_sage_const_4 +n, m)]] += -r
        ridx += _sage_const_1 
for blk in (range(_sage_const_3 ), range(_sage_const_3 , _sage_const_6 )):
    for m in blk:
        for n in blk:
            if n <= m: continue
            NP[ridx, POS[(_sage_const_4 +m, n)]] += _sage_const_1 
            NP[ridx, POS[(_sage_const_4 +n, m)]] += -_sage_const_1 
            ridx += _sage_const_1 
print(f"PREDICTION 2: rank(B on pol-breaking 15) = {(NP*B).rank()}  (Theta moves everywhere: 15)")
# and obstructedness of pol-breaking pure-anti block (outside im delta?)
PA = NP[_sage_const_9 :, :]
print(f"pure-anti dims outside im(delta): {PA.stack(IMD).rank() - IMD.rank()} of 6")

