

# This file was *autogenerated* from the file w2_battery.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_4719 = Integer(4719); _sage_const_24 = Integer(24)# W2 depth-one Petri battery on the bielliptic specimen.
# Config family: D~ = splittings (a0,a1,a2 | b0,b1,b2), sum 3 per u-branch,
# over the six O-places of C~ (pi~_* D~ = 3O+ + 3O- in |omega_C|).
# Per config, Lemma A predicts EXACTLY:
#   ker(beta on the s-slice) = h^0(omega_C - maxa*O+ - maxb*O-)
#                            = 2 if maxa = maxb = 1 (the bielliptic pencil
#                              E = 2O+ + 2O-), else 1.
# W1-scope: the ker=2 configs should carry h^0(L) >= 2 ({1, t} in L(D~)) —
# the battery decides whether the specimen is depth-one-clean.

load('w2_specimen.sage')   # hpoly, PLACES, gate machinery, K6, S/s, ZETA, F

LPOOL = [(pp, q, i, j) for pp in range(-_sage_const_2 , _sage_const_5 ) for q in (_sage_const_0 , _sage_const_1 )
         for i in (_sage_const_0 , _sage_const_1 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]
print(f"battery pool: {len(LPOOL)} monomials", flush=True)

# ordered place list: (pl, iu, k) -> series tuple
PLIST = []
for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))):
    for idx, tup in enumerate(PLACES[pl]):
        PLIST.append((pl, idx // _sage_const_3 , idx % _sage_const_3 , tup))


def kernel_of(allow_fn, div_by_u):
    """Kernel basis of the pool under valuation conditions: for each place,
    v(monomial-combo [/u]) >= -allow(place)."""
    rows = []
    for (pl, iu, k, (xs, ys, u, t)) in PLIST:
        a = allow_fn(pl, iu, k)
        sers = [xs**pp * ys**q * u**i * t**j for (pp, q, i, j) in LPOOL]
        if div_by_u:
            sers = [ss / u for ss in sers]
        minv = min(ss.valuation() for ss in sers)
        for order in range(minv, -a):
            rows.append([ss[order] for ss in sers])
    M = matrix(K6, rows)
    return M.right_kernel().basis_matrix()


# --- sample points of C~ (with sigma-orbits) for evaluation ranks
import random
random.seed(int(_sage_const_4719 ))
P1w = PolynomialRing(K6, names=('z',)); (z,) = P1w._first_ngens(1)
PTS = []
while len(PTS) < _sage_const_24 :
    x0 = K6.random_element()
    if x0 == _sage_const_0 :
        continue
    yr = (z**_sage_const_2  + (_sage_const_2 *x0 + _sage_const_1 )*z - x0**_sage_const_3 ).roots()
    if not yr:
        continue
    y0 = yr[random.randrange(len(yr))][_sage_const_0 ]
    if y0 == _sage_const_0 :
        continue
    h0 = hpoly(x0, y0)
    ur = (z**_sage_const_2  - h0).roots()
    if not ur:
        continue
    u0 = ur[_sage_const_0 ][_sage_const_0 ]
    if u0 == _sage_const_0 :
        continue
    tr = (z**_sage_const_3  - y0).roots()
    if not tr:
        continue
    t0 = tr[_sage_const_0 ][_sage_const_0 ]
    PTS.append((x0, y0, u0, t0))


def evalvec(vec, pt):
    x0, y0, u0, t0 = pt
    v = K6(_sage_const_0 )
    for cc, (pp, q, i, j) in zip(vec, LPOOL):
        if cc:
            v += cc * x0**pp * y0**q * u0**i * t0**j
    return v


def beta_rank(KL, KM):
    """Rank of the anti-invariant projection of the Petri products,
    by evaluation + sigma-averaging over t -> zeta^k t."""
    rows = []
    for a in range(KL.nrows()):
        for b in range(KM.nrows()):
            row = []
            for pt in PTS:
                x0, y0, u0, t0 = pt
                vals = []
                for k in range(_sage_const_3 ):
                    ptk = (x0, y0, u0, ZETA**k * t0)
                    vals.append(evalvec(KL.row(a), ptk) * evalvec(KM.row(b), ptk))
                row.append(vals[_sage_const_0 ] - sum(vals)/_sage_const_3 )
            rows.append(row)
    return matrix(K6, rows).rank()


def predicted_ker(maxmults):
    """dim{eta in H^0(omega_C~)^sigma-inv : v >= maxmult at all places over
    each C-point} — Lemma A's h^0(omega_C - Dbar), computed on the tower."""
    def allow(pl, iu, k):
        return -maxmults.get((pl, iu), _sage_const_0 )
    KP = kernel_of(allow, True)
    # restrict to sigma-invariant part: invariant monomials have j = 0
    # (eta = (A/u) omega0~ with A of t-grade 0); impose j != 0 coeffs vanish
    rows = []
    for r in range(KP.nrows()):
        pass
    # simpler: rebuild with j-0-only subpool
    rows = []
    sub = [mp for mp in LPOOL if mp[_sage_const_3 ] == _sage_const_0 ]
    for (pl, iu, k, (xs, ys, u, t)) in PLIST:
        a = allow(pl, iu, k)
        sers = [xs**pp * ys**q * u**i / u for (pp, q, i, j) in sub]
        minv = min(ss.valuation() for ss in sers)
        for order in range(minv, -a):
            rows.append([ss[order] for ss in sers])
    return len(sub) - matrix(K6, rows).rank()


comps3 = [(_sage_const_3 ,_sage_const_0 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_3 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_0 ,_sage_const_3 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_0 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ),
          (_sage_const_0 ,_sage_const_1 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_1 ,_sage_const_1 )]

print("=== O-family battery: 100 configs ===", flush=True)
tally = {}
fails = _sage_const_0 
for A3 in comps3:
    for B3 in comps3:
        mult = {}
        for k in range(_sage_const_3 ):
            mult[('O', _sage_const_0 , k)] = A3[k]
            mult[('O', _sage_const_1 , k)] = B3[k]
        KL = kernel_of(lambda pl, iu, k: mult.get((pl, iu, k), _sage_const_0 ), False)
        KM = kernel_of(lambda pl, iu, k: -mult.get((pl, iu, k), _sage_const_0 ), True)
        h0L, h0M = KL.nrows(), KM.nrows()
        rk = beta_rank(KL, KM)
        maxm = {('O', _sage_const_0 ): max(A3), ('O', _sage_const_1 ): max(B3)}
        pred = predicted_ker(maxm)
        # Lemma A check applies on the s-slice; at h0L = 1 the whole domain
        ok = True
        if h0L == _sage_const_1 :
            ok = (h0L * h0M - rk) == pred
        key = (max(A3), max(B3), h0L)
        tag = (h0L, h0M, rk, pred, ok)
        tally.setdefault(key, []).append(tag)
        if h0L == _sage_const_1  and not ok:
            fails += _sage_const_1 
            print(f"  LEMMA-A FAIL: {A3}|{B3}: h0L={h0L} h0M={h0M} "
                  f"rank={rk} pred_ker={pred}", flush=True)

print(f"Lemma-A failures at h0=1: {fails}", flush=True)
print("summary by (maxa, maxb, h0L): [h0L, h0M, rank, pred_ker, ok] reps:",
      flush=True)
for key in sorted(tally):
    reps = tally[key]
    uniq = sorted(set(reps))
    print(f"  {key} x{len(reps)}: {uniq}", flush=True)

# --- W1-scope verdict
print("=== verdict ===", flush=True)
bad_depth1 = [k for k, v in tally.items()
              if k[_sage_const_2 ] == _sage_const_1  and any(t[_sage_const_0 ]*t[_sage_const_1 ] - t[_sage_const_2 ] > t[_sage_const_3 ] or t[_sage_const_3 ] > _sage_const_1 
                                   for t in v)]
print(f"depth-one configs with ker > T: "
      f"{'NONE — specimen depth-one-clean, W1 holds on it' if not bad_depth1 else bad_depth1}",
      flush=True)

