

# This file was *autogenerated* from the file w2_specimen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_20260719 = Integer(20260719); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_400 = Integer(400); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20)# W2 specimen builder: bielliptic genus-4 tower with certified NON-thetanull.
# E0: y^2+2xy+y = x^3;  C: u^2 = h(x,y), h in L(6O) = <1,x,x^2,x^3,y,xy>
# (x^3 reduced by the curve relation => quadric z0^2 = Q(1,x,y));
# C~: t^3 = y (etale mu_3, eps = pullback of [T-O], nonzero automatically).
# Certificates: (a) rank Q = 3  <=> canonical quadric rank 4 <=> NO vanishing
# thetanull; (b) 6 simple branch zeros avoiding T/T'/O-fibers; (c) eigenspace
# gates dim H^0(omega_C~)_j = 4/3/3  (certifies genus 4 + connected cover).

p = _sage_const_7 
F = GF(p)
R2 = PolynomialRing(F, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
G = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 

import random
random.seed(int(_sage_const_20260719 ))

# --- scan for h = c0 + c1 x + c2 x^2 + c3 x^3 + c4 y + c5 xy with the certs
def reduce_h(cs):
    """h with x^3 replaced via curve: x^3 = y^2+2xy+y  =>  quadratic in (1,x,y)."""
    c0, c1, c2, c3, c4, c5 = cs
    # h = c0 + c1 X + c2 X^2 + c3 X^3 + c4 Y + c5 XY
    # X^3 -> Y^2 + 2XY + Y
    hq = c0 + c1*X + c2*X**_sage_const_2  + c4*Y + c5*X*Y + c3*(Y**_sage_const_2  + _sage_const_2 *X*Y + Y)
    return hq  # quadratic in (1, X, Y) when viewed with monomials 1,X,Y,X^2,XY,Y^2


def Qrank(hq):
    """Rank of hq as a quadratic form in (1, X, Y) (char 7 != 2)."""
    m = matrix(F, _sage_const_3 , _sage_const_3 )
    def co(i, j):
        if i == _sage_const_0  and j == _sage_const_0 :
            return hq.constant_coefficient()
        return hq.monomial_coefficient(X**i * Y**j)
    m[_sage_const_0 ,_sage_const_0 ] = co(_sage_const_0 ,_sage_const_0 )
    m[_sage_const_1 ,_sage_const_1 ] = co(_sage_const_2 ,_sage_const_0 )
    m[_sage_const_2 ,_sage_const_2 ] = co(_sage_const_0 ,_sage_const_2 )
    m[_sage_const_0 ,_sage_const_1 ] = co(_sage_const_1 ,_sage_const_0 )/_sage_const_2 ; m[_sage_const_1 ,_sage_const_0 ] = m[_sage_const_0 ,_sage_const_1 ]
    m[_sage_const_0 ,_sage_const_2 ] = co(_sage_const_0 ,_sage_const_1 )/_sage_const_2 ; m[_sage_const_2 ,_sage_const_0 ] = m[_sage_const_0 ,_sage_const_2 ]
    m[_sage_const_1 ,_sage_const_2 ] = co(_sage_const_1 ,_sage_const_1 )/_sage_const_2 ; m[_sage_const_2 ,_sage_const_1 ] = m[_sage_const_1 ,_sage_const_2 ]
    return m.rank()


def Dh(hpoly):
    """Invariant derivation on E0: D = (2y+2x+1) d/dx + (3x^2-2y) d/dy."""
    return (_sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 )*hpoly.derivative(X) + (_sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y)*hpoly.derivative(Y)


K6 = GF(p**_sage_const_6 , 'w')


def branch_ok(hpoly):
    """6 distinct simple zeros on E0, none over x=0 (T/T') or at O."""
    RX = PolynomialRing(F, names=('xx',)); (xx,) = RX._first_ngens(1)
    res = hpoly.resultant(G, Y)      # poly in X
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0 :
        return False
    dh = Dh(hpoly)
    cnt = _sage_const_0 
    for (x0, mult) in resx.roots(K6):
        # y-roots over x0 on the curve
        RY = PolynomialRing(K6, names=('yy',)); (yy,) = RY._first_ngens(1)
        for (y0, _) in RY(G(x0, yy)).roots():
            if hpoly(x0, y0) == _sage_const_0 :
                if x0 == _sage_const_0 :
                    return False
                if dh(x0, y0) == _sage_const_0 :
                    return False
                cnt += _sage_const_1 
    return cnt == _sage_const_6 


found = None
for trial in range(_sage_const_400 ):
    cs = [F(random.randrange(p)) for _ in range(_sage_const_6 )]
    if cs[_sage_const_3 ] == _sage_const_0 :
        cs[_sage_const_3 ] = F(_sage_const_1 )          # keep x^3 present => h has exact pole order 6 at O
    hpoly = cs[_sage_const_0 ] + cs[_sage_const_1 ]*X + cs[_sage_const_2 ]*X**_sage_const_2  + cs[_sage_const_3 ]*X**_sage_const_3  + cs[_sage_const_4 ]*Y + cs[_sage_const_5 ]*X*Y
    hq = reduce_h(cs)
    if Qrank(hq) != _sage_const_3 :
        continue
    if not branch_ok(hpoly):
        continue
    found = (cs, hpoly, hq)
    print(f"SPECIMEN found (trial {trial}): h = {hpoly}", flush=True)
    print(f"  reduced quadric Q = {hq}   rank(Q) = 3  => canonical quadric rank 4:"
          f" NON-THETANULL CERTIFIED", flush=True)
    break
if found is None:
    raise SystemExit("no specimen in scan range")
cs, hpoly, hq = found

# --- eigenspace gates on C~ = {u^2 = h, t^3 = y}: conditions only at the six
# places over O (pool monomials have poles nowhere else).
NTRUNC = _sage_const_20 
S = LaurentSeriesRing(K6, default_prec=NTRUNC, names=('s',)); (s,) = S._first_ngens(1)

P1 = PolynomialRing(K6, names=('z',)); (z,) = P1._first_ngens(1)
ZETA = K6(F(_sage_const_2 ))                      # 2^3 = 1 mod 7


def e0_series(pl):
    if pl == 'O':
        xs = s**-_sage_const_2 
        for _ in range(NTRUNC + _sage_const_4 ):
            xs = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xs*s)
        return xs, xs/s
    x0, y0 = pl
    xs = x0 + s
    ys = y0 + _sage_const_0 *s
    for _ in range(NTRUNC + _sage_const_4 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return xs, ys


def cover_places(pl):
    """All C~-places over the E0-place pl: (xs, ys, u-series, t-series) tuples,
    with the omega0-pullback shift implicit (div omega0-pullback = R~, away
    from T/T'/O)."""
    xs, ys = e0_series(pl)
    hser = hpoly(xs, ys)
    lead = hser.coefficients()[_sage_const_0 ]
    ubrs = []
    for (u0, _) in (z**_sage_const_2  - lead).roots():
        v = hser.valuation()
        assert v % _sage_const_2  == _sage_const_0 
        u = u0 * s**(v // _sage_const_2 )
        for _ in range(NTRUNC + _sage_const_4 ):
            u = u - (u**_sage_const_2  - hser)/(_sage_const_2 *u)
        ubrs.append(u)
    assert len(ubrs) == _sage_const_2 , f"u-cover not split at {pl}"
    yv = ys.valuation()
    assert yv % _sage_const_3  == _sage_const_0 
    tl = (z**_sage_const_3  - ys.coefficients()[_sage_const_0 ]).roots()
    assert tl, f"t-cover leading coeff not a cube at {pl}"
    t0 = tl[_sage_const_0 ][_sage_const_0 ] * s**(yv // _sage_const_3 )
    for _ in range(NTRUNC + _sage_const_4 ):
        t0 = t0 - (t0**_sage_const_3  - ys)/(_sage_const_3 *t0**_sage_const_2 )
    out = []
    for u in ubrs:
        for k in range(_sage_const_3 ):
            out.append((xs, ys, u, ZETA**k * t0))
    return out


PLACES = {pl: cover_places(pl) for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 )))}
POOL = [(pp, q, i, j) for pp in range(-_sage_const_2 , _sage_const_4 ) for q in (_sage_const_0 , _sage_const_1 )
        for i in (_sage_const_0 , _sage_const_1 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def gate(j):
    """dim of the t^j-eigenspace of H^0(omega_C~): eta = (A/u) * omega0-pullback,
    A = x^p y^q u^i t^j; regularity at the six O-places (poles allowed nowhere)
    plus the twelve T/T'-places (p = -1 monomials have poles there)."""
    rows = []
    ncols = len([_sage_const_1  for mp in POOL if mp[_sage_const_3 ] == j])
    for pl, places in PLACES.items():
        for (xs, ys, u, t) in places:
            sers = [(xs**pp * ys**q * u**i * t**j) / u
                    for (pp, q, i, jj) in POOL if jj == j]
            minv = min(tt.valuation() for tt in sers)
            for order in range(minv, _sage_const_0 ):
                rows.append([tt[order] for tt in sers])
    M = matrix(K6, rows)
    return ncols - M.rank()


dims = [gate(j) for j in range(_sage_const_3 )]
print(f"GATES: eigenspace dims = {dims}  (expect [4, 3, 3]:"
      f" genus 4 + connected etale mu_3 cover, eps != 0)", flush=True)

