

# This file was *autogenerated* from the file w3_count2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_49 = Integer(49); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_20000 = Integer(20000); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_120 = Integer(120)# W3/J3: |V^1(F_49)|-weighted count (k = 2 census) — irreducibility test:
# irreducible dim-3 => count/49^3 -> ~1 + O(q^{-1/2}); several components
# => ratio ~ #components.  Field-generic adaptation of w3_count.sage.

q = _sage_const_49 
K1 = GF(q, 'g2')
R2 = PolynomialRing(K1, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
G = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
hpoly = -_sage_const_2 *X**_sage_const_3  + X**_sage_const_2  - X*Y + _sage_const_3 *X + _sage_const_1 
RX = PolynomialRing(K1, names=('xx',)); (xx,) = RX._first_ngens(1)
OSPLIT = K1(-_sage_const_2 ).is_square()          # True over F_49


def Dop(f):
    return (_sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 )*f.derivative(X) + (_sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y)*f.derivative(Y)


def is_cube(v, K):
    return v == _sage_const_0  or v**((K.order() - _sage_const_1 ) // _sage_const_3 ) == _sage_const_1 


def comb2(m):
    return (m + _sage_const_2 )*(m + _sage_const_1 )//_sage_const_2 


EXT = {}
def ext_field(d):
    if d not in EXT:
        EXT[d] = K1.extension(d, f'e{d}')
    return EXT[d]


def closed_zeros(fpoly):
    res = fpoly.resultant(G, Y)
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0 :
        return None
    out = []
    for (pfac, _) in resx.factor():
        if pfac.degree() == _sage_const_0 :
            continue
        dx = pfac.degree()
        K = ext_field(dx) if dx > _sage_const_1  else K1
        x0 = pfac.roots(K)[_sage_const_0 ][_sage_const_0 ]
        RY = PolynomialRing(K, names=('yy',)); (yy,) = RY._first_ngens(1)
        yr = RY(G(x0, yy)).roots()
        found_pair = False
        if yr:
            for (y0, _) in yr:
                if fpoly(x0, y0) != _sage_const_0 :
                    continue
                m = _sage_const_0 
                ftest = fpoly
                while ftest(x0, y0) == _sage_const_0 :
                    m += _sage_const_1 
                    ftest = Dop(ftest)
                    if m > _sage_const_6 :
                        return None
                out.append((dx, m, x0, y0, K))
        else:
            K2 = ext_field(_sage_const_2 *dx)
            RY2 = PolynomialRing(K2, names=('y2',)); (y2,) = RY2._first_ngens(1)
            x02 = pfac.roots(K2)[_sage_const_0 ][_sage_const_0 ]
            for (y0, _) in RY2(G(x02, y2)).roots():
                if fpoly(x02, y0) != _sage_const_0  or found_pair:
                    continue
                found_pair = True
                m = _sage_const_0 
                ftest = fpoly
                while ftest(x02, y0) == _sage_const_0 :
                    m += _sage_const_1 
                    ftest = Dop(ftest)
                    if m > _sage_const_6 :
                        return None
                out.append((_sage_const_2 *dx, m, x02, y0, K2))
    return out


total = _sage_const_0 
nzero = _sage_const_0 
skipped = _sage_const_0 
done = _sage_const_0 
import sys
for c1 in K1:
    for c2 in K1:
        for c3 in K1:
            l = c1 + c2*X + c3*Y
            Fq = l**_sage_const_2  - hpoly
            pts = closed_zeros(Fq)
            done += _sage_const_1 
            if done % _sage_const_20000  == _sage_const_0 :
                print(f"  ...{done} etas, total so far {total}", flush=True)
            if pts is None:
                skipped += _sage_const_1 
                continue
            if sum(d*m for (d, m, _, _, _) in pts) != _sage_const_6 :
                skipped += _sage_const_1 
                continue
            nl = _sage_const_1 
            ok = True
            for (d, m, x0, y0, K) in pts:
                if l(x0, y0) == _sage_const_0  and hpoly(x0, y0) == _sage_const_0 :
                    ok = False
                    break
                if is_cube(y0, K):
                    nl *= comb2(m)
                else:
                    nl *= (_sage_const_1  if m % _sage_const_3  == _sage_const_0  else _sage_const_0 )
                if nl == _sage_const_0 :
                    break
            if not ok:
                skipped += _sage_const_1 
                continue
            if nl == _sage_const_0 :
                nzero += _sage_const_1 
            total += nl

# c0 = 0 face (O-part: two rational O-points over F_49, independent sides)
def opart(mside):
    return comb2(mside)**_sage_const_2  if OSPLIT else comb2(mside)


face = [(K1(_sage_const_0 ), K1(_sage_const_0 ), K1(_sage_const_1 )), (K1(_sage_const_0 ), K1(_sage_const_1 ), K1(_sage_const_0 )), (K1(_sage_const_1 ), K1(_sage_const_0 ), K1(_sage_const_0 ))]
face += [(c1, c2, K1(_sage_const_1 )) for c1 in K1 for c2 in K1 if (c1, c2) != (_sage_const_0 , _sage_const_0 )]
face += [(c1, K1(_sage_const_1 ), K1(_sage_const_0 )) for c1 in K1 if c1 != _sage_const_0 ]
for (c1, c2, c3) in face:
    l = c1 + c2*X + c3*Y
    a = _sage_const_3  if c3 != _sage_const_0  else (_sage_const_2  if c2 != _sage_const_0  else _sage_const_0 )
    nl = opart(_sage_const_3  - a)
    ok = True
    if a > _sage_const_0 :
        pts = closed_zeros(l)
        if pts is None or sum(d*m for (d, m, _, _, _) in pts) != a:
            skipped += _sage_const_1 
            continue
        for (d, m, x0, y0, K) in pts:
            hv = hpoly(x0, y0)
            if hv == _sage_const_0 :
                ok = False
                break
            if hv**((K.order()-_sage_const_1 )//_sage_const_2 ) == _sage_const_1 :
                if is_cube(y0, K):
                    nl *= (m+_sage_const_5 )*(m+_sage_const_4 )*(m+_sage_const_3 )*(m+_sage_const_2 )*(m+_sage_const_1 )//_sage_const_120 
                else:
                    nl *= (m//_sage_const_3  + _sage_const_1 ) if m % _sage_const_3  == _sage_const_0  else _sage_const_0 
            else:
                K2 = ext_field(_sage_const_2 *d) if K is K1 else ext_field(_sage_const_2 *d)
                y02 = K2(y0) if K.degree() == _sage_const_1  else                     y0.minimal_polynomial().roots(K2)[_sage_const_0 ][_sage_const_0 ]
                if is_cube(y02, K2):
                    nl *= comb2(m//_sage_const_2 ) if m % _sage_const_2  == _sage_const_0  else _sage_const_0 
                else:
                    nl *= _sage_const_1  if m % _sage_const_6  == _sage_const_0  else _sage_const_0 
            if nl == _sage_const_0 :
                break
    if not ok:
        skipped += _sage_const_1 
        continue
    total += nl

print(f"K2 CENSUS: weighted count = {total}", flush=True)
print(f"  ratio to 49^3 = {float(total/_sage_const_49 **_sage_const_3 ):.3f}   "
      f"(k=1 ratio was 1502/343 = 4.38)", flush=True)
print(f"  zero-lift etas: {nzero}; skipped {skipped}", flush=True)

