

# This file was *autogenerated* from the file w3_count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_120 = Integer(120); _sage_const_12 = Integer(12)# W3/J1: exact |V^1(F_7)|-count (rational effective W with pi_*W in |omega|)
# on the bielliptic specimen, via E0-side closed-point arithmetic.
# eta = (c0 u + l(x,y))/u * omega0,  l = c1 + c2 x + c3 y.
# c0 = 1 (343 etas): div(eta) = zeros of F = l^2 - h on E0, each lifting to
#   the UNIQUE u-sheet u = -l; t-fiber splits iff y-value is a cube.
# c0 = 0 (57 etas): div(eta) = pullback of div0(l) + (3-a)(O+ + O-), a = the
#   O-pole of l; u-sheet now a choice (h-value square test); O+- is one
#   closed degree-2 point (sqrt(-2) irrational) with 3 degree-2 t-points.

p = _sage_const_7 
F7 = GF(p)
R2 = PolynomialRing(F7, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
G = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
hpoly = -_sage_const_2 *X**_sage_const_3  + X**_sage_const_2  - X*Y + _sage_const_3 *X + _sage_const_1 
RX = PolynomialRing(F7, names=('xx',)); (xx,) = RX._first_ngens(1)


def Dop(f):
    return (_sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 )*f.derivative(X) + (_sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y)*f.derivative(Y)


def is_cube(v, K):
    if v == _sage_const_0 :
        return True          # y=0 only at T; leading coeff 1 is a cube
    return v**((K.order() - _sage_const_1 ) // _sage_const_3 ) == _sage_const_1 


def is_square(v, K):
    if v == _sage_const_0 :
        return None          # branch point — caller flags
    return v**((K.order() - _sage_const_1 ) // _sage_const_2 ) == _sage_const_1 


def comb2(m):
    return (m + _sage_const_2 )*(m + _sage_const_1 )//_sage_const_2 


def closed_zeros(fpoly):
    """Closed points of div0(fpoly) on E0: list of (d, m, x0, y0, K).
    Multiplicity by D-iteration.  Returns None if degenerate."""
    res = fpoly.resultant(G, Y)
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0 :
        return None
    out = []
    for (pfac, _) in resx.factor():
        if pfac.degree() == _sage_const_0 :
            continue
        dx = pfac.degree()
        K = GF(p**dx, 'a') if dx > _sage_const_1  else F7
        x0 = pfac.roots(K)[_sage_const_0 ][_sage_const_0 ] if dx > _sage_const_1  else pfac.roots()[_sage_const_0 ][_sage_const_0 ]
        RY = PolynomialRing(K, names=('yy',)); (yy,) = RY._first_ngens(1)
        gy = RY(G(x0, yy))
        yr = gy.roots()
        found_pair = False
        for (y0, _) in yr:
            if fpoly(x0, y0) != _sage_const_0 :
                continue
            m = _sage_const_0 
            ftest = fpoly
            while ftest(x0, y0) == _sage_const_0 :
                m += _sage_const_1 
                ftest = Dop(ftest)
                if m > _sage_const_6 :
                    return None
            out.append((dx, m, x0, y0, K))
        if not yr:                      # y in quadratic extension
            K2 = GF(p**(_sage_const_2 *dx), 'b')
            RY2 = PolynomialRing(K2, names=('y2',)); (y2,) = RY2._first_ngens(1)
            x02 = pfac.roots(K2)[_sage_const_0 ][_sage_const_0 ]
            for (y0, _) in RY2(G(x02, y2)).roots():
                if fpoly(x02, y0) != _sage_const_0 :
                    continue
                if found_pair:
                    continue            # conjugate — same closed point
                found_pair = True
                m = _sage_const_0 
                ftest = fpoly
                while ftest(x02, y0) == _sage_const_0 :
                    m += _sage_const_1 
                    ftest = Dop(ftest)
                    if m > _sage_const_6 :
                        return None
                out.append((_sage_const_2 *dx, m, x02, y0, K2))
    return out


total = _sage_const_0 
hist = {}
skipped = []
# --- c0 = 1 family: l = c1 + c2 x + c3 y, F = l^2 - h
for c1 in F7:
    for c2 in F7:
        for c3 in F7:
            l = c1 + c2*X + c3*Y
            Fq = l**_sage_const_2  - hpoly
            pts = closed_zeros(Fq)
            if pts is None:
                skipped.append(('c0=1', c1, c2, c3, 'degenerate'))
                continue
            degsum = sum(d*m for (d, m, _, _, _) in pts)
            if degsum != _sage_const_6 :
                skipped.append(('c0=1', c1, c2, c3, f'degsum={degsum}'))
                continue
            nl = _sage_const_1 
            ok = True
            for (d, m, x0, y0, K) in pts:
                if l(x0, y0) == _sage_const_0  and hpoly(x0, y0) == _sage_const_0 :
                    ok = False          # zero hits a branch point
                    break
                if is_cube(y0, K):
                    nl *= comb2(m)
                else:
                    nl *= (_sage_const_1  if m % _sage_const_3  == _sage_const_0  else _sage_const_0 )
                if nl == _sage_const_0 :
                    break
            if not ok:
                skipped.append(('c0=1', c1, c2, c3, 'branch-hit'))
                continue
            total += nl
            hist[nl] = hist.get(nl, _sage_const_0 ) + _sage_const_1 

# --- c0 = 0 face: eta = (l/u) omega0
def opart_lifts(mult_per_side):
    """O+- = one closed deg-2 point; 3 deg-2 t-points; symmetric mult
    (m, m): Frobenius-stable assignments = compositions of m into 3."""
    return comb2(mult_per_side)


for (c1, c2, c3) in [(_sage_const_0 , _sage_const_0 , _sage_const_1 ), (_sage_const_0 , _sage_const_1 , _sage_const_0 )] +         [(c1, c2, _sage_const_1 ) for c1 in F7 for c2 in F7 if (c1, c2) != (_sage_const_0 , _sage_const_0 )] +         [(c1, _sage_const_1 , _sage_const_0 ) for c1 in F7 if c1 != _sage_const_0 ] + [(_sage_const_1 , _sage_const_0 , _sage_const_0 )]:
    l = c1 + c2*X + c3*Y
    a = _sage_const_3  if c3 != _sage_const_0  else (_sage_const_2  if c2 != _sage_const_0  else _sage_const_0 )
    nl = opart_lifts(_sage_const_3  - a)
    ok = True
    if a > _sage_const_0 :
        pts = closed_zeros(l)
        if pts is None:
            skipped.append(('c0=0', c1, c2, c3, 'degenerate'))
            continue
        degsum = sum(d*m for (d, m, _, _, _) in pts)
        if degsum != a:
            skipped.append(('c0=0', c1, c2, c3, f'degsum={degsum}!={a}'))
            continue
        for (d, m, x0, y0, K) in pts:
            hv = hpoly(x0, y0)
            sq = is_square(hv, K)
            if sq is None:
                ok = False
                break
            if sq:      # u splits: 2 pts deg d
                if is_cube(y0, K):      # 6 pts deg d
                    nl *= (m+_sage_const_5 )*(m+_sage_const_4 )*(m+_sage_const_3 )*(m+_sage_const_2 )*(m+_sage_const_1 )//_sage_const_120 
                else:                   # 2 pts deg 3d
                    nl *= (m//_sage_const_3  + _sage_const_1 ) if m % _sage_const_3  == _sage_const_0  else _sage_const_0 
            else:       # u inert: 1 pt deg 2d
                K2 = GF(p**(_sage_const_2 *d), 'c')
                y02 = K2(y0) if d == _sage_const_1  else y0.minimal_polynomial().roots(K2)[_sage_const_0 ][_sage_const_0 ]
                if is_cube(y02, K2):    # 3 pts deg 2d
                    nl *= comb2(m//_sage_const_2 ) if m % _sage_const_2  == _sage_const_0  else _sage_const_0 
                else:                   # 1 pt deg 6d
                    nl *= _sage_const_1  if m % _sage_const_6  == _sage_const_0  else _sage_const_0 
            if nl == _sage_const_0 :
                break
    if not ok:
        skipped.append(('c0=0', c1, c2, c3, 'branch-hit'))
        continue
    total += nl
    hist[nl] = hist.get(nl, _sage_const_0 ) + _sage_const_1 

print(f"RAW COUNT (sum over eta of rational lifts) = {total}", flush=True)
print(f"  [= #V^1(F_7) weighted by #|L|(F_7); depth-one L count once]", flush=True)
print(f"heuristic scale: |P^3(F_7)| = 400, 7^3 = 343", flush=True)
print(f"lift-count histogram (lifts-per-eta: #etas): "
      f"{dict(sorted(hist.items()))}", flush=True)
print(f"skipped/exceptional etas: {len(skipped)}", flush=True)
for srow in skipped[:_sage_const_12 ]:
    print(f"  {srow}", flush=True)

