

# This file was *autogenerated* from the file w5_kummer.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_18 = Integer(18); _sage_const_2026721 = Integer(2026721); _sage_const_1 = Integer(1); _sage_const_400 = Integer(400); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_40 = Integer(40); _sage_const_25 = Integer(25); _sage_const_10 = Integer(10); _sage_const_27 = Integer(27); _sage_const_60 = Integer(60)# W5: the Kummer specimen — genus-4 (C, eps) breaking the structural
# obstructions (trinomial => thetanull; bielliptic => iota-corank).
# C: u^3 = f(x,y), f in L(3O) with x-dependence, 3 simple branch zeros off
# the fibers; C~: t^3 = y.  Loop over candidates until the canonical quadric
# has rank 4, then measure the RIGIDITY RANK (27 = surjective => generic
# rigidity of the AP-threefold, certified forever by semicontinuity).

p = _sage_const_7 
F = GF(p)
R2 = PolynomialRing(F, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
G = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
K6 = GF(p**_sage_const_6 , 'w')
ZETA = K6(F(_sage_const_2 ))
NTRUNC = _sage_const_18 
S = LaurentSeriesRing(K6, default_prec=NTRUNC, names=('s',)); (s,) = S._first_ngens(1)
RX = PolynomialRing(F, names=('xx',)); (xx,) = RX._first_ngens(1)
P1 = PolynomialRing(K6, names=('z',)); (z,) = P1._first_ngens(1)
import random
random.seed(int(_sage_const_2026721 ))


def Dop(f):
    return (_sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 )*f.derivative(X) + (_sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y)*f.derivative(Y)


CANDIDATES = []
for _ in range(_sage_const_400 ):
    c0, c1, c2 = [F(random.randrange(p)) for _ in range(_sage_const_3 )]
    if c2 == _sage_const_0  or c1 == _sage_const_0 :
        continue
    fp = c0 + c1*X + c2*Y
    if fp(_sage_const_0 , _sage_const_0 ) == _sage_const_0  or fp(_sage_const_0 , -_sage_const_1 ) == _sage_const_0  or fp in CANDIDATES:
        continue
    res = fp.resultant(G, Y)
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0  or not resx.is_squarefree():
        continue
    dh = Dop(fp)
    ok = True
    nz = _sage_const_0 
    for (pf, _) in resx.factor():
        if pf.degree() == _sage_const_0 :
            continue
        d = pf.degree()
        Kd = GF(p**d, 'a') if d > _sage_const_1  else F
        x0 = pf.roots(Kd)[_sage_const_0 ][_sage_const_0 ]
        RY = PolynomialRing(Kd, names=('yy',)); (yy,) = RY._first_ngens(1)
        for (y0, _) in RY(G(x0, yy)).roots():
            if fp(x0, y0) == _sage_const_0 :
                nz += d
                if x0 == _sage_const_0  or dh(x0, y0) == _sage_const_0 :
                    ok = False
    if ok and nz == _sage_const_3 :
        CANDIDATES.append(fp)
print(f"candidates: {len(CANDIDATES)}", flush=True)


def e0_series(pl):
    if pl == 'O':
        xs = s**-_sage_const_2 
        for _ in range(NTRUNC + _sage_const_4 ):
            xs = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xs*s)
        return xs, xs/s
    x0, y0 = pl
    xs = x0 + s
    ys = y0 + _sage_const_0 *s
    for _ in range(NTRUNC + _sage_const_4 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return xs, ys


def cover_places(fpoly, pl):
    xs, ys = e0_series(pl)
    fser = fpoly(xs, ys)
    fv = fser.valuation()
    assert fv % _sage_const_3  == _sage_const_0 
    ur = (z**_sage_const_3  - fser.coefficients()[_sage_const_0 ]).roots()
    if not ur:
        return None
    u0 = ur[_sage_const_0 ][_sage_const_0 ] * s**(fv // _sage_const_3 )
    for _ in range(NTRUNC + _sage_const_4 ):
        u0 = u0 - (u0**_sage_const_3  - fser)/(_sage_const_3 *u0**_sage_const_2 )
    yv = ys.valuation()
    tr = (z**_sage_const_3  - ys.coefficients()[_sage_const_0 ]).roots()
    if not tr:
        return None
    t0 = tr[_sage_const_0 ][_sage_const_0 ] * s**(yv // _sage_const_3 )
    for _ in range(NTRUNC + _sage_const_4 ):
        t0 = t0 - (t0**_sage_const_3  - ys)/(_sage_const_3 *t0**_sage_const_2 )
    return [(xs, ys, ZETA**ku * u0, ZETA**kt * t0)
            for ku in range(_sage_const_3 ) for kt in range(_sage_const_3 )]


POOL = [(pp, q, i, j) for pp in range(-_sage_const_2 , _sage_const_4 ) for q in (_sage_const_0 , _sage_const_1 )
        for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]
QPOOL = [(pp, q, i, j) for pp in range(-_sage_const_4 , _sage_const_7 ) for q in (_sage_const_0 , _sage_const_1 )
         for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def kernel_basis(PLACES, subpool, upow):
    rows = []
    for pl, places in PLACES.items():
        for (xs, ys, u, t) in places:
            sers = [xs**pp * ys**q * u**i * t**j / u**upow
                    for (pp, q, i, j) in subpool]
            minv = min(ss.valuation() for ss in sers)
            for order in range(minv, _sage_const_0 ):
                rows.append([ss[order] for ss in sers])
    return matrix(K6, rows).right_kernel().basis_matrix()


def evalp(vec, pt):
    x0, y0, u0, t0 = pt
    v = K6(_sage_const_0 )
    for cc, (pp, q, i, j) in zip(vec, POOL):
        if cc:
            v += cc * x0**pp * y0**q * u0**i * t0**j
    return v


for fpoly in CANDIDATES:
    PL = {}
    bad = False
    for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))):
        cp = cover_places(fpoly, pl)
        if cp is None:
            bad = True
            break
        PL[pl] = cp
    if bad:
        continue
    OMEGA = []
    dims = []
    for j in range(_sage_const_3 ):
        sub = [mp for mp in POOL if mp[_sage_const_3 ] == j]
        K = kernel_basis(PL, sub, _sage_const_2 )
        dims.append(K.nrows())
        idx = [POOL.index(mp) for mp in sub]
        for r in range(K.nrows()):
            v = [K6(_sage_const_0 )] * len(POOL)
            for c, ii in enumerate(idx):
                v[ii] = K[r][c]
            OMEGA.append(v)
    if dims != [_sage_const_4 , _sage_const_3 , _sage_const_3 ]:
        print(f"f = {fpoly}: gates {dims} — skip", flush=True)
        continue
    WITS = []
    while len(WITS) < _sage_const_40 :
        x0 = K6.random_element()
        if x0 == _sage_const_0 :
            continue
        yr = (z**_sage_const_2  + (_sage_const_2 *x0+_sage_const_1 )*z - x0**_sage_const_3 ).roots()
        if not yr:
            continue
        y0 = yr[random.randrange(len(yr))][_sage_const_0 ]
        if y0 == _sage_const_0  or fpoly(x0, y0) == _sage_const_0 :
            continue
        ur = (z**_sage_const_3  - fpoly(x0, y0)).roots()
        if not ur:
            continue
        tr = (z**_sage_const_3  - y0).roots()
        if not tr:
            continue
        WITS.append((x0, y0, ur[_sage_const_0 ][_sage_const_0 ], tr[_sage_const_0 ][_sage_const_0 ]))
    CAN = OMEGA[:_sage_const_4 ]
    qrows = []
    for pt in WITS[:_sage_const_25 ]:
        zc = [evalp(vb, pt) for vb in CAN]
        qrows.append([zc[a]*zc[b] for a in range(_sage_const_4 ) for b in range(a, _sage_const_4 )])
    KQ = matrix(K6, qrows).right_kernel().basis_matrix()
    if KQ.nrows() != _sage_const_1 :
        print(f"f = {fpoly}: {KQ.nrows()} quadrics — skip", flush=True)
        continue
    qv = KQ.row(_sage_const_0 )
    Smat = matrix(K6, _sage_const_4 , _sage_const_4 )
    idx = _sage_const_0 
    for a in range(_sage_const_4 ):
        for b in range(a, _sage_const_4 ):
            if a == b:
                Smat[a, a] = qv[idx]
            else:
                Smat[a, b] += qv[idx]/_sage_const_2 
                Smat[b, a] += qv[idx]/_sage_const_2 
            idx += _sage_const_1 
    qr = Smat.rank()
    print(f"f = {fpoly}: quadric rank {qr}", flush=True)
    if qr != _sage_const_4 :
        continue
    print(f"SPECIMEN ACCEPTED: u^3 = {fpoly} (non-thetanull certified)",
          flush=True)
    KQ2 = kernel_basis(PL, QPOOL, _sage_const_4 )
    print(f"GATE: h^0(omega~^2) = {KQ2.nrows()} (expect 27)", flush=True)
    ANTI = OMEGA[_sage_const_4 :]
    SG = [_sage_const_0 ]*_sage_const_4  + [_sage_const_1 ]*_sage_const_3  + [_sage_const_2 ]*_sage_const_3 
    rowsM = []
    labels = []
    for a in range(_sage_const_10 ):
        for b in range(_sage_const_6 ):
            row = []
            for pt in WITS:
                x0, y0, u0, t0 = pt
                row.append(evalp(OMEGA[a], pt) * evalp(ANTI[b], pt) / u0**_sage_const_4 )
            rowsM.append(row)
            labels.append((SG[a] + SG[_sage_const_4  + b]) % _sage_const_3 )
    rk = matrix(K6, rowsM).rank()
    print(f"RIGIDITY MULTIPLICATION RANK = {rk} of 27  "
          f"({'SURJECTIVE — GENERIC RIGIDITY CERTIFIED' if rk == _sage_const_27  else 'corank ' + str(_sage_const_27  - rk)})",
          flush=True)
    for gt in range(_sage_const_3 ):
        sub = [rowsM[i] for i in range(_sage_const_60 ) if labels[i] == gt]
        print(f"  sigma-grade {gt}: rank {matrix(K6, sub).rank()} of 9",
              flush=True)
    break

