

# This file was *autogenerated* from the file w6_scanner.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_30 = Integer(30); _sage_const_202607202 = Integer(202607202); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_20 = Integer(20); _sage_const_40 = Integer(40); _sage_const_4000 = Integer(4000); _sage_const_25 = Integer(25); _sage_const_60 = Integer(60); _sage_const_27 = Integer(27)# W6: index-formula scanner for the two-fiber specimen.
# C: v^3 + p v + q = 0 over E0, coefficients p, q rational functions with
# poles in the {O, T, T'} fiber set, at least two fibers polar => the {1,v}
# single-fiber pencil (thetanull law) is broken.  Per candidate: branches at
# level-6 substitution with per-branch ramification detection, gates
# [4,3,3] (genus 4 + connected mu_3 tower), canonical quadric rank (want 4),
# then the RIGIDITY RANK (27 = generic rigidity certified).

p7 = _sage_const_7 
F = GF(p7)
R2 = PolynomialRing(F, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
GE = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
K6 = GF(p7**_sage_const_6 , 'w')
ZETA = K6(F(_sage_const_2 ))
NTR = _sage_const_30 
S = LaurentSeriesRing(K6, default_prec=NTR, names=('s',)); (s,) = S._first_ngens(1)
P1 = PolynomialRing(K6, names=('z',)); (z,) = P1._first_ngens(1)
import random
random.seed(int(_sage_const_202607202 ))

# coefficient atoms: functions on E0 with fiber-set poles
# div(x) = T + T' - 2O ; div(y) = 3T - 3O ; div((y+1)/x) = poles T + O
ATOMS = {
    '1':    lambda xs, ys: xs**_sage_const_0 ,
    'x':    lambda xs, ys: xs,
    'y':    lambda xs, ys: ys,
    '1/x':  lambda xs, ys: _sage_const_1 /xs,
    'w':    lambda xs, ys: (ys+_sage_const_1 )/xs,      # poles T + O
    'y/x':  lambda xs, ys: ys/xs,          # poles T' + O
}
ATOMPOLY = {
    '1': R2(_sage_const_1 ), 'x': X, 'y': Y, '1/x': None, 'w': None, 'y/x': None,
}


def e0_series(pl, prec):
    Sl = LaurentSeriesRing(K6, default_prec=prec, names=('ss',)); (ss,) = Sl._first_ngens(1)
    if pl == 'O':
        xs = ss**-_sage_const_2 
        for _ in range(prec + _sage_const_4 ):
            xs = ss**-_sage_const_2  + _sage_const_2 *ss**-_sage_const_1  + _sage_const_1 /(xs*ss)
        return xs, xs/ss
    x0, y0 = pl
    xs = x0 + ss
    ys = y0 + _sage_const_0 *ss
    for _ in range(prec + _sage_const_4 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return xs, ys


def eval_coeff(coeffs, xs, ys):
    v = _sage_const_0 *xs
    for (cf, at) in coeffs:
        v = v + K6(cf) * ATOMS[at](xs, ys)
    return v


def eval_coeff_pt(coeffs, x0, y0):
    v = K6(_sage_const_0 )
    for (cf, at) in coeffs:
        if at == '1':
            v += K6(cf)
        elif at == 'x':
            v += K6(cf)*x0
        elif at == 'y':
            v += K6(cf)*y0
        elif at == '1/x':
            v += K6(cf)/x0
        elif at == 'w':
            v += K6(cf)*(y0+_sage_const_1 )/x0
        elif at == 'y/x':
            v += K6(cf)*y0/x0
    return v


def cubic_roots_series(ps, qs, prec):
    """All Laurent-series roots of v^3 + ps*v + qs (level of ps/qs), via
    Newton slopes + Hensel; returns list of series."""
    roots = []
    vp = ps.valuation() if ps != _sage_const_0  else _sage_const_10 **_sage_const_6 
    vq = qs.valuation() if qs != _sage_const_0  else _sage_const_10 **_sage_const_6 
    cand_v = set()
    # slopes from Newton polygon of (3,0),(1,vp),(0,vq)
    for k in range(-_sage_const_12 , _sage_const_13 ):
        vals = [_sage_const_3 *k, vp + k, vq]
        m = min(vals)
        if len([_sage_const_1  for t in vals if t == m]) >= _sage_const_2 :
            cand_v.add(k)
    for k in sorted(cand_v):
        Pz = PolynomialRing(K6, names=('cc',)); (cc,) = Pz._first_ngens(1)
        poly = Pz(_sage_const_0 )
        vals = [_sage_const_3 *k, vp + k, vq]
        m = min(vals)
        if _sage_const_3 *k == m:
            poly += cc**_sage_const_3 
        if ps != _sage_const_0  and vp + k == m:
            poly += ps.coefficients()[_sage_const_0 ]*cc
        if qs != _sage_const_0  and vq == m:
            poly += qs.coefficients()[_sage_const_0 ]
        for (c0, _) in poly.roots():
            if c0 == _sage_const_0 :
                continue
            u = c0 * s.parent()(ps.parent().gen())**k if False else c0 * ps.parent().gen()**k
            for _ in range(prec + _sage_const_6 ):
                fu = u**_sage_const_3  + ps*u + qs
                if fu == _sage_const_0 :
                    break
                dfu = _sage_const_3 *u**_sage_const_2  + ps
                if dfu == _sage_const_0 :
                    break
                u = u - fu/dfu
            res = u**_sage_const_3  + ps*u + qs
            if res != _sage_const_0  and res.valuation() < prec - _sage_const_10 :
                continue
            if any((u - r0) == _sage_const_0  or (u - r0).valuation() >= prec - _sage_const_12 
                   for r0 in roots):
                continue
            roots.append(u)
    return roots


def branch_data(pcoef, qcoef, pl):
    """Level-6 branches over E0-place pl: returns list of
    (xs6, ys6, vbr, tbr, m) with m = 6/e the sigma-lattice, or None."""
    xs6, ys6 = e0_series(pl, NTR)
    xs6, ys6 = xs6.V(_sage_const_6 ), ys6.V(_sage_const_6 )
    Sl = xs6.parent()
    ps = eval_coeff(pcoef, xs6, ys6)
    qs = eval_coeff(qcoef, xs6, ys6)
    vroots = cubic_roots_series(ps, qs, NTR*_sage_const_6  - _sage_const_20 )
    if len(vroots) != _sage_const_3 :
        return None
    # t: cube root of ys6 (one; others by zeta)
    yv = ys6.valuation()
    if yv % _sage_const_3  != _sage_const_0 :
        return None
    tr = (z**_sage_const_3  - ys6.coefficients()[_sage_const_0 ]).roots()
    if not tr:
        return None
    t0 = tr[_sage_const_0 ][_sage_const_0 ] * Sl.gen()**(yv//_sage_const_3 )
    for _ in range(_sage_const_40 ):
        t0 = t0 - (t0**_sage_const_3  - ys6)/(_sage_const_3 *t0**_sage_const_2 )
    out = []
    for vb in vroots:
        # detect lattice m = gcd of exponent support (with 6)
        expo = [e for e, c in enumerate([]) ] # placeholder
        supp = vb.exponents()
        m = _sage_const_6 
        for e in supp:
            m = gcd(m, e - supp[_sage_const_0 ]) if supp else _sage_const_6 
        m = gcd(m, _sage_const_6 )
        if m == _sage_const_0 :
            m = _sage_const_6 
        for kt in range(_sage_const_3 ):
            out.append((xs6, ys6, vb, ZETA**kt * t0, m))
    return out


GPOOL = [(a, b, i, j) for a in range(-_sage_const_2 , _sage_const_4 ) for b in (_sage_const_0 , _sage_const_1 )
         for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]
G2POOL = [(a, b, i, j) for a in range(-_sage_const_4 , _sage_const_7 ) for b in (_sage_const_0 , _sage_const_1 )
          for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def kernel_dims(BR, pcoef, pool, power):
    """Kernel of regularity for eta = (g t^j / F_v^power) * pi*omega0^power,
    per t-grade j; returns (dims, bases-over-pool)."""
    out_dims = []
    out_bases = []
    for j in range(_sage_const_3 ):
        sub = [mp for mp in pool if mp[_sage_const_3 ] == j]
        rows = []
        for pl, brs in BR.items():
            for (xs6, ys6, vb, tb, m) in brs:
                Fv = _sage_const_3 *vb**_sage_const_2  + eval_coeff(pcoef, xs6, ys6)
                w0 = xs6.derivative() / (_sage_const_2 *ys6 + _sage_const_2 *xs6 + _sage_const_1 )
                pref = (tb**j) * w0**power / Fv**power
                sers = [xs6**a * ys6**b * vb**i * pref for (a, b, i, jj) in sub]
                minv = min(ss.valuation() for ss in sers)
                cutoff = power*(m - _sage_const_1 ) - (m - _sage_const_1 ) + (m - _sage_const_1 )  # = power*(m-1)
                for order in range(minv, power*(m-_sage_const_1 )):
                    rows.append([ss[order] for ss in sers])
        M = matrix(K6, rows)
        Kb = M.right_kernel().basis_matrix()
        out_dims.append(Kb.nrows())
        out_bases.append((sub, Kb))
    return out_dims, out_bases


def run_candidate(pcoef, qcoef, verbose=False):
    BR = {}
    for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))):
        bd = branch_data(pcoef, qcoef, pl)
        if bd is None:
            return None
        BR[pl] = bd
    dims, bases = kernel_dims(BR, pcoef, GPOOL, _sage_const_1 )
    if verbose:
        print(f"    gates {dims}", flush=True)
    if dims != [_sage_const_4 , _sage_const_3 , _sage_const_3 ]:
        return ('gates', dims)
    # witnesses on C~
    WITS = []
    tries = _sage_const_0 
    while len(WITS) < _sage_const_40  and tries < _sage_const_4000 :
        tries += _sage_const_1 
        x0 = K6.random_element()
        if x0 == _sage_const_0 :
            continue
        yr = (z**_sage_const_2  + (_sage_const_2 *x0+_sage_const_1 )*z - x0**_sage_const_3 ).roots()
        if not yr:
            continue
        y0 = yr[random.randrange(len(yr))][_sage_const_0 ]
        if y0 == _sage_const_0 :
            continue
        pv = eval_coeff_pt(pcoef, x0, y0)
        qv = eval_coeff_pt(qcoef, x0, y0)
        vr = (z**_sage_const_3  + pv*z + qv).roots()
        if not vr:
            continue
        v0 = vr[random.randrange(len(vr))][_sage_const_0 ]
        if _sage_const_3 *v0**_sage_const_2  + pv == _sage_const_0 :
            continue
        tr2 = (z**_sage_const_3  - y0).roots()
        if not tr2:
            continue
        WITS.append((x0, y0, v0, tr2[_sage_const_0 ][_sage_const_0 ]))
    if len(WITS) < _sage_const_40 :
        return ('wits', len(WITS))

    def evg(subKrow, sub, pt):
        x0, y0, v0, t0 = pt
        val = K6(_sage_const_0 )
        for cc, (a, b, i, jj) in zip(subKrow, sub):
            if cc:
                val += cc * x0**a * y0**b * v0**i * t0**jj
        return val

    sub0, K0 = bases[_sage_const_0 ]
    qrows = []
    for pt in WITS[:_sage_const_25 ]:
        zc = [evg(K0.row(r), sub0, pt) for r in range(_sage_const_4 )]
        qrows.append([zc[a]*zc[b] for a in range(_sage_const_4 ) for b in range(a, _sage_const_4 )])
    KQ = matrix(K6, qrows).right_kernel().basis_matrix()
    if KQ.nrows() != _sage_const_1 :
        return ('nquad', KQ.nrows())
    qv2 = KQ.row(_sage_const_0 )
    Sm = matrix(K6, _sage_const_4 , _sage_const_4 )
    idx = _sage_const_0 
    for a in range(_sage_const_4 ):
        for b in range(a, _sage_const_4 ):
            if a == b:
                Sm[a, a] = qv2[idx]
            else:
                Sm[a, b] += qv2[idx]/_sage_const_2 
                Sm[b, a] += qv2[idx]/_sage_const_2 
            idx += _sage_const_1 
    qr = Sm.rank()
    if qr != _sage_const_4 :
        return ('quadric', qr)
    # RIGIDITY
    dims2, _ = kernel_dims(BR, pcoef, G2POOL, _sage_const_2 )
    h0q = sum(dims2)
    rowsM = []
    for j1 in range(_sage_const_3 ):
        subA, KA = bases[j1]
        for j2 in (_sage_const_1 , _sage_const_2 ):
            subB, KB = bases[j2]
            for ra in range(KA.nrows()):
                for rb in range(KB.nrows()):
                    row = []
                    for pt in WITS:
                        x0, y0, v0, t0 = pt
                        pv = eval_coeff_pt(pcoef, x0, y0)
                        Fv = _sage_const_3 *v0**_sage_const_2  + pv
                        row.append(evg(KA.row(ra), subA, pt) *
                                   evg(KB.row(rb), subB, pt) / Fv**_sage_const_2 )
                    rowsM.append(row)
    rk = matrix(K6, rowsM).rank()
    return ('HIT', qr, h0q, rk)


# --- candidate sweep: q with T'-structure (y+1)-vanishing kept, plus a
# two-fiber polar term in p or q
FAMS = []
for _ in range(_sage_const_60 ):
    pc = [(random.randrange(_sage_const_1 , _sage_const_7 ), 'x'),
          (random.randrange(_sage_const_7 ), '1'),
          (random.randrange(_sage_const_7 ), 'w')]
    qc = [(random.randrange(_sage_const_1 , _sage_const_7 ), 'y'), (random.randrange(_sage_const_1 , _sage_const_7 ), '1'),
          (random.randrange(_sage_const_7 ), 'x'), (random.randrange(_sage_const_7 ), '1/x')]
    FAMS.append((pc, qc))

hits = _sage_const_0 
diag = {}
nc = _sage_const_0 
for (pc, qc) in FAMS:
    nc += _sage_const_1 
    try:
        res = run_candidate(pc, qc)
    except (AssertionError, ZeroDivisionError, ValueError) as e:
        diag[type(e).__name__] = diag.get(type(e).__name__, _sage_const_0 ) + _sage_const_1 
        continue
    if res is None:
        diag['branches'] = diag.get('branches', _sage_const_0 ) + _sage_const_1 
        continue
    key = res[_sage_const_0 ] if res[_sage_const_0 ] != 'gates' else f"gates{res[_sage_const_1 ]}"
    diag[key] = diag.get(key, _sage_const_0 ) + _sage_const_1 
    if nc <= _sage_const_6 :
        print(f"  cand {nc}: {res[:_sage_const_2 ]}", flush=True)
    if res[_sage_const_0 ] == 'HIT':
        print(f"p = {pc}", flush=True)
        print(f"q = {qc}", flush=True)
        print(f"  quadric rank 4; h^0(omega~^2) = {res[_sage_const_2 ]}; "
              f"RIGIDITY RANK = {res[_sage_const_3 ]} of 27", flush=True)
        if res[_sage_const_3 ] == _sage_const_27 :
            print("  *** SURJECTIVE — GENERIC RIGIDITY CERTIFIED ***",
                  flush=True)
            hits += _sage_const_1 
            break
    elif res[_sage_const_0 ] == 'gates' and res[_sage_const_1 ] != [_sage_const_4 , _sage_const_3 , _sage_const_3 ]:
        pass
print(f"sweep done; certified hits: {hits}; diagnostics: {diag}", flush=True)

