

# This file was *autogenerated* from the file w7_nodes.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_26 = Integer(26); _sage_const_72026 = Integer(72026); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_200 = Integer(200); _sage_const_40 = Integer(40); _sage_const_4000 = Integer(4000); _sage_const_25 = Integer(25); _sage_const_27 = Integer(27)# W7: the node-adjoint specimen family (eightfold tuned-pair playbook).
# C: (v - alpha)^2 (v + 2 alpha) + c^2 = 0  over E0, alpha in F7*,
# c = gamma*y + delta*x + eps in L(3O).  disc = -27 c^2 (4 alpha^3 + c^2):
# 3 NODES at {c = 0, v = alpha}, 6 simple branch points at {4a^3 + c^2 = 0}
# => R = 6, genus 4.  v has val -2 poles on the O-fiber only, but lies in
# L(2*O-fiber) = |omega|: the single-fiber pencil law does NOT fire.
# All fiber places unramified => level-1 engine; adjoint conditions at the
# node branches arise from the same regularity rows (F_v val 1 there).
# Chain: gates [4,3,3] (Sigma = 10 sanity) -> quadric rank 4 -> RIGIDITY.

p7 = _sage_const_7 
F = GF(p7)
R2 = PolynomialRing(F, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
GE = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
K6 = GF(p7**_sage_const_6 , 'w')
ZETA = K6(F(_sage_const_2 ))
NTR = _sage_const_26 
S = LaurentSeriesRing(K6, default_prec=NTR, names=('s',)); (s,) = S._first_ngens(1)
P1 = PolynomialRing(K6, names=('z',)); (z,) = P1._first_ngens(1)
RX = PolynomialRing(F, names=('xx',)); (xx,) = RX._first_ngens(1)
import random
random.seed(int(_sage_const_72026 ))


def e0_series_at(x0, y0):
    xs = x0 + s
    ys = y0 + _sage_const_0 *s
    for _ in range(NTR + _sage_const_4 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return xs, ys


def e0_series_O():
    xs = s**-_sage_const_2 
    for _ in range(NTR + _sage_const_4 ):
        xs = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xs*s)
    return xs, xs/s


def Dop(f):
    return (_sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 )*f.derivative(X) + (_sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y)*f.derivative(Y)


def hensel_cubic(pser, qser):
    """Roots of v^3 + pser v + qser with SIMPLE leading roots (level 1)."""
    roots = []
    vp = pser.valuation() if pser != _sage_const_0  else _sage_const_10 **_sage_const_6 
    vq = qser.valuation() if qser != _sage_const_0  else _sage_const_10 **_sage_const_6 
    for k in range(-_sage_const_6 , _sage_const_7 ):
        vals = [_sage_const_3 *k, vp + k, vq]
        m = min(vals)
        if len([_sage_const_1  for t in vals if t == m]) < _sage_const_2 :
            continue
        Pz = PolynomialRing(K6, names=('cc',)); (cc,) = Pz._first_ngens(1)
        poly = Pz(_sage_const_0 )
        if _sage_const_3 *k == m:
            poly += cc**_sage_const_3 
        if pser != _sage_const_0  and vp + k == m:
            poly += pser.coefficients()[_sage_const_0 ]*cc
        if qser != _sage_const_0  and vq == m:
            poly += qser.coefficients()[_sage_const_0 ]
        for (c0, mult) in poly.roots():
            if c0 == _sage_const_0  or mult > _sage_const_1 :
                continue
            u = c0 * s**k
            for _ in range(NTR + _sage_const_6 ):
                fu = u**_sage_const_3  + pser*u + qser
                if fu == _sage_const_0 :
                    break
                u = u - fu/(_sage_const_3 *u**_sage_const_2  + pser)
            if any((u - r0) == _sage_const_0  or (u - r0).valuation() >= NTR - _sage_const_8 
                   for r0 in roots):
                continue
            roots.append(u)
    return roots


def tower_places(alpha, cpoly):
    """All condition places of C~: fiber places (O/T/T') + node places.
    Returns list of (xs, ys, vbr, tbr) or None."""
    a3 = K6(alpha)**_sage_const_3 
    out = []
    # fiber places
    for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))):
        if pl == 'O':
            xs, ys = e0_series_O()
        else:
            xs, ys = e0_series_at(K6(pl[_sage_const_0 ]), K6(pl[_sage_const_1 ]))
        cs = cpoly(xs, ys)
        pser = (-_sage_const_3 *K6(alpha)**_sage_const_2 ) + _sage_const_0 *xs
        qser = _sage_const_2 *a3 + cs**_sage_const_2 
        vr = hensel_cubic(pser, qser)
        if len(vr) != _sage_const_3 :
            return None
        yv = ys.valuation()
        if yv % _sage_const_3  != _sage_const_0 :
            return None
        tr = (z**_sage_const_3  - ys.coefficients()[_sage_const_0 ]).roots()
        if not tr:
            return None
        t0 = tr[_sage_const_0 ][_sage_const_0 ] * s**(yv//_sage_const_3 )
        for _ in range(NTR + _sage_const_6 ):
            t0 = t0 - (t0**_sage_const_3  - ys)/(_sage_const_3 *t0**_sage_const_2 )
        for vb in vr:
            for kt in range(_sage_const_3 ):
                out.append((xs, ys, vb, ZETA**kt * t0))
    # node places: zeros of cpoly on E0, v-branches v = alpha + w, w = c*h
    res = cpoly.resultant(GE, Y)
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0 :
        return None
    ndeg = _sage_const_0 
    for (pf, _) in resx.factor():
        if pf.degree() == _sage_const_0 :
            continue
        d = pf.degree()
        if _sage_const_6  % d != _sage_const_0 :
            return None
        Kd = GF(p7**d, 'a') if d > _sage_const_1  else F
        x0r = pf.roots(Kd)[_sage_const_0 ][_sage_const_0 ]
        RY = PolynomialRing(Kd, names=('yy',)); (yy,) = RY._first_ngens(1)
        for (y0r, _) in RY(GE(x0r, yy)).roots():
            if cpoly(x0r, y0r) != _sage_const_0 :
                continue
            # embed into K6
            if d == _sage_const_1 :
                x0, y0 = K6(x0r), K6(y0r)
            else:
                emb = Kd.hom([Kd.gen().minimal_polynomial().roots(K6)[_sage_const_0 ][_sage_const_0 ]],
                             K6)
                x0, y0 = emb(x0r), emb(y0r)
            # all Frobenius conjugates are separate geometric node points
            for _ in range(d):
                xs, ys = e0_series_at(x0, y0)
                cs = cpoly(xs, ys)
                if cs.valuation() != _sage_const_1 :
                    return None      # non-simple c-zero: skip candidate
                # w^2 (w + 3 alpha) = -c^2 ; w = c*h, h^2 (c h + 3a) = -1
                sq = (z**_sage_const_2  + _sage_const_1 /(_sage_const_3 *K6(alpha))).roots()
                if not sq:
                    return None
                for (h0, _) in sq:
                    h = h0 + _sage_const_0 *s
                    for _ in range(NTR + _sage_const_6 ):
                        fh = h**_sage_const_2  * (cs*h + _sage_const_3 *K6(alpha)) + _sage_const_1 
                        dfh = _sage_const_3 *cs*h**_sage_const_2  + _sage_const_6 *K6(alpha)*h
                        h = h - fh/dfh
                    vb = K6(alpha) + cs*h
                    yv = ys.valuation()
                    tr = (z**_sage_const_3  - ys.coefficients()[_sage_const_0 ]).roots()
                    if not tr:
                        return None
                    t0 = tr[_sage_const_0 ][_sage_const_0 ] * s**(yv//_sage_const_3 )
                    for _ in range(NTR + _sage_const_6 ):
                        t0 = t0 - (t0**_sage_const_3  - ys)/(_sage_const_3 *t0**_sage_const_2 )
                    for kt in range(_sage_const_3 ):
                        out.append((xs, ys, vb, ZETA**kt * t0))
                ndeg += _sage_const_1 
                x0, y0 = x0**_sage_const_7 , y0**_sage_const_7 
    if ndeg != _sage_const_3 :
        return None
    return out


GPOOL = [(a, b, i, j) for a in range(-_sage_const_2 , _sage_const_5 ) for b in (_sage_const_0 , _sage_const_1 )
         for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]
G2POOL = [(a, b, i, j) for a in range(-_sage_const_4 , _sage_const_8 ) for b in (_sage_const_0 , _sage_const_1 )
          for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def kernel_grades(PLACES, alpha, pool, power):
    dims = []
    bases = []
    for j in range(_sage_const_3 ):
        sub = [mp for mp in pool if mp[_sage_const_3 ] == j]
        rows = []
        for (xs, ys, vb, tb) in PLACES:
            Fv = _sage_const_3 *vb**_sage_const_2  - _sage_const_3 *K6(alpha)**_sage_const_2 
            w0 = xs.derivative() / (_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
            pref = (tb**j) * w0**power / Fv**power
            sers = [xs**a * ys**b * vb**i * pref for (a, b, i, jj) in sub]
            minv = min(ss.valuation() for ss in sers)
            for order in range(minv, _sage_const_0 ):
                rows.append([ss[order] for ss in sers])
        Kb = matrix(K6, rows).right_kernel().basis_matrix()
        dims.append(Kb.nrows())
        bases.append((sub, Kb))
    return dims, bases


def evg(row, sub, pt):
    x0, y0, v0, t0 = pt
    val = K6(_sage_const_0 )
    for cc, (a, b, i, jj) in zip(row, sub):
        if cc:
            val += cc * x0**a * y0**b * v0**i * t0**jj
    return val


tested = _sage_const_0 
for trial in range(_sage_const_200 ):
    alpha = F(random.randrange(_sage_const_1 , _sage_const_7 ))
    gam = F(random.randrange(_sage_const_1 , _sage_const_7 ))
    dlt = F(random.randrange(_sage_const_7 ))
    epsc = F(random.randrange(_sage_const_7 ))
    cpoly = gam*Y + dlt*X + epsc
    # basic exclusions: c nonzero at T, T'; 4a^3 + c^2 nonzero at fibers
    if cpoly(_sage_const_0 , _sage_const_0 ) == _sage_const_0  or cpoly(_sage_const_0 , -_sage_const_1 ) == _sage_const_0 :
        continue
    if _sage_const_4 *alpha**_sage_const_3  + cpoly(_sage_const_0 , _sage_const_0 )**_sage_const_2  == _sage_const_0  or _sage_const_4 *alpha**_sage_const_3  + cpoly(_sage_const_0 , -_sage_const_1 )**_sage_const_2  == _sage_const_0 :
        continue
    PLACES = tower_places(alpha, cpoly)
    if PLACES is None:
        continue
    tested += _sage_const_1 
    dims, bases = kernel_grades(PLACES, alpha, GPOOL, _sage_const_1 )
    if sum(dims) != _sage_const_10 :
        if tested <= _sage_const_5 :
            print(f"alpha={alpha} c={cpoly}: gates {dims} (Sigma "
                  f"{sum(dims)}) — reject", flush=True)
        continue
    if dims != [_sage_const_4 , _sage_const_3 , _sage_const_3 ]:
        print(f"alpha={alpha} c={cpoly}: gates {dims} — odd split", flush=True)
        continue
    print(f"alpha={alpha} c={cpoly}: gates [4,3,3] PASS", flush=True)
    # witnesses
    WITS = []
    tries = _sage_const_0 
    while len(WITS) < _sage_const_40  and tries < _sage_const_4000 :
        tries += _sage_const_1 
        x0 = K6.random_element()
        if x0 == _sage_const_0 :
            continue
        yr = (z**_sage_const_2  + (_sage_const_2 *x0+_sage_const_1 )*z - x0**_sage_const_3 ).roots()
        if not yr:
            continue
        y0 = yr[random.randrange(len(yr))][_sage_const_0 ]
        if y0 == _sage_const_0 :
            continue
        cv = cpoly(x0, y0)
        if cv == _sage_const_0 :
            continue
        vr = (z**_sage_const_3  - _sage_const_3 *K6(alpha)**_sage_const_2 *z + _sage_const_2 *K6(alpha)**_sage_const_3  + cv**_sage_const_2 ).roots()
        if not vr:
            continue
        v0 = vr[random.randrange(len(vr))][_sage_const_0 ]
        if _sage_const_3 *v0**_sage_const_2  - _sage_const_3 *K6(alpha)**_sage_const_2  == _sage_const_0 :
            continue
        tr2 = (z**_sage_const_3  - y0).roots()
        if not tr2:
            continue
        WITS.append((x0, y0, v0, tr2[_sage_const_0 ][_sage_const_0 ]))
    if len(WITS) < _sage_const_40 :
        continue
    sub0, K0 = bases[_sage_const_0 ]
    qrows = []
    for pt in WITS[:_sage_const_25 ]:
        zc = [evg(K0.row(r), sub0, pt) for r in range(_sage_const_4 )]
        qrows.append([zc[a]*zc[b] for a in range(_sage_const_4 ) for b in range(a, _sage_const_4 )])
    KQ = matrix(K6, qrows).right_kernel().basis_matrix()
    if KQ.nrows() != _sage_const_1 :
        print(f"  {KQ.nrows()} quadrics — skip", flush=True)
        continue
    qv = KQ.row(_sage_const_0 )
    Sm = matrix(K6, _sage_const_4 , _sage_const_4 )
    idx = _sage_const_0 
    for a in range(_sage_const_4 ):
        for b in range(a, _sage_const_4 ):
            if a == b:
                Sm[a, a] = qv[idx]
            else:
                Sm[a, b] += qv[idx]/_sage_const_2 
                Sm[b, a] += qv[idx]/_sage_const_2 
            idx += _sage_const_1 
    qr = Sm.rank()
    print(f"  quadric rank = {qr}", flush=True)
    if qr != _sage_const_4 :
        continue
    print(f"  NON-THETANULL SPECIMEN FOUND — running rigidity", flush=True)
    dims2, _ = kernel_grades(PLACES, alpha, G2POOL, _sage_const_2 )
    print(f"  h^0(omega~^2) grades {dims2} (Sigma {sum(dims2)}, expect 27)",
          flush=True)
    rowsM = []
    labels = []
    for j1 in range(_sage_const_3 ):
        subA, KA = bases[j1]
        for j2 in (_sage_const_1 , _sage_const_2 ):
            subB, KB = bases[j2]
            for ra in range(KA.nrows()):
                for rb in range(KB.nrows()):
                    row = []
                    for pt in WITS:
                        x0, y0, v0, t0 = pt
                        Fv = _sage_const_3 *v0**_sage_const_2  - _sage_const_3 *K6(alpha)**_sage_const_2 
                        row.append(evg(KA.row(ra), subA, pt) *
                                   evg(KB.row(rb), subB, pt) / Fv**_sage_const_2 )
                    rowsM.append(row)
                    labels.append((j1 + j2) % _sage_const_3 )
    rk = matrix(K6, rowsM).rank()
    print(f"  RIGIDITY RANK = {rk} of 27  "
          f"({'*** SURJECTIVE — GENERIC RIGIDITY CERTIFIED ***' if rk == _sage_const_27  else 'corank ' + str(_sage_const_27  - rk)})",
          flush=True)
    for gt in range(_sage_const_3 ):
        subr = [rowsM[i] for i in range(len(rowsM)) if labels[i] == gt]
        print(f"    sigma-grade {gt}: rank {matrix(K6, subr).rank()} of 9",
              flush=True)
    if rk == _sage_const_27 :
        break
print(f"done; tested {tested}", flush=True)

