

# This file was *autogenerated* from the file w8_model33.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_24 = Integer(24); _sage_const_3372026 = Integer(3372026); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_27 = Integer(27); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_9 = Integer(9); _sage_const_5 = Integer(5); _sage_const_400 = Integer(400); _sage_const_10 = Integer(10); _sage_const_40 = Integer(40); _sage_const_5000 = Integer(5000); _sage_const_25 = Integer(25)# W8: the (3,3)-model specimen — tri-nodal bidegree-(3,3) curve in E0 x P^1
# with PRESCRIBED generic nodes (9 linear conditions on the 12 L(3O)-coeffs).
# Genus 7 - 3 = 4; omega = O(R) with R involving the generic node positions:
# NOT a fiber-class multiple => the master thetanull law cannot fire.
# Engine: monic depressed W-form (W-poles only over O, val -3); condition
# places = O/T/T' fibers + 3 real nodes + artifact nodes at a_3-zeros; the
# adjoint conditions arise automatically from 1/F_W's val at node branches.
# Chain: linear solve -> gates [4,3,3] -> quadric rank -> RIGIDITY RANK.

p7 = _sage_const_7 
F = GF(p7)
R2 = PolynomialRing(F, names=('X', 'Y',)); (X, Y,) = R2._first_ngens(2)
GE = Y**_sage_const_2  + _sage_const_2 *X*Y + Y - X**_sage_const_3 
K6 = GF(p7**_sage_const_6 , 'w')
ZETA = K6(F(_sage_const_2 ))
NTR = _sage_const_24 
S = LaurentSeriesRing(K6, default_prec=NTR, names=('s',)); (s,) = S._first_ngens(1)
P1 = PolynomialRing(K6, names=('z',)); (z,) = P1._first_ngens(1)
RX = PolynomialRing(F, names=('xx',)); (xx,) = RX._first_ngens(1)
import random
random.seed(int(_sage_const_3372026 ))

Dx = _sage_const_2 *Y + _sage_const_2 *X + _sage_const_1 
Dy = _sage_const_3 *X**_sage_const_2  - _sage_const_2 *Y

# --- E0 rational points for node placement
E0RAT = [(F(x0), F(y0)) for x0 in F for y0 in F
         if x0 != _sage_const_0  and y0 != _sage_const_0  and (y0**_sage_const_2  + _sage_const_2 *x0*y0 + y0 - x0**_sage_const_3 ) == _sage_const_0 
         and y0 != -_sage_const_1 ]


def e0_series_at(x0, y0):
    xs = x0 + s
    ys = y0 + _sage_const_0 *s
    for _ in range(NTR + _sage_const_4 ):
        fy = ys**_sage_const_2  + _sage_const_2 *xs*ys + ys - xs**_sage_const_3 
        ys = ys - fy/(_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
    return xs, ys


def e0_series_O():
    xs = s**-_sage_const_2 
    for _ in range(NTR + _sage_const_4 ):
        xs = s**-_sage_const_2  + _sage_const_2 *s**-_sage_const_1  + _sage_const_1 /(xs*s)
    return xs, xs/s


def sqrt_series(f):
    v = f.valuation()
    if v % _sage_const_2  != _sage_const_0 :
        return None
    rt = (z**_sage_const_2  - f.coefficients()[_sage_const_0 ]).roots()
    if not rt:
        return None
    g = rt[_sage_const_0 ][_sage_const_0 ] * s**(v//_sage_const_2 )
    for _ in range(NTR + _sage_const_6 ):
        g = g - (g**_sage_const_2  - f)/(_sage_const_2 *g)
    return g


def cube_series(f):
    v = f.valuation()
    if v % _sage_const_3  != _sage_const_0 :
        return None
    rt = (z**_sage_const_3  - f.coefficients()[_sage_const_0 ]).roots()
    if not rt:
        return None
    g = rt[_sage_const_0 ][_sage_const_0 ] * s**(v//_sage_const_3 )
    for _ in range(NTR + _sage_const_6 ):
        g = g - (g**_sage_const_3  - f)/(_sage_const_3 *g**_sage_const_2 )
    return g


def build_candidate():
    """Pick 3 nodes, solve the 9 linear conditions, return (a-coeffs, nodes)."""
    nodes = random.sample(E0RAT, _sage_const_3 )
    vvals = [F(random.randrange(_sage_const_1 , _sage_const_7 )) for _ in range(_sage_const_3 )]
    if len({pt[_sage_const_0 ] for pt in nodes}) < _sage_const_3 :
        return None
    rows = []
    # unknowns: (alpha_i, beta_i, gamma_i) for a_i = alpha + beta x + gamma y
    for ((x0, y0), v0) in zip(nodes, vvals):
        rF, rFv, rD = [], [], []
        dxv, dyv = Dx(x0, y0), Dy(x0, y0)
        for i in range(_sage_const_4 ):
            vi = v0**i
            vim = F(i)*v0**(i-_sage_const_1 ) if i >= _sage_const_1  else F(_sage_const_0 )
            rF += [vi, x0*vi, y0*vi]
            rFv += [vim, x0*vim, y0*vim]
            rD += [F(_sage_const_0 ), dxv*vi, dyv*vi]
        rows += [rF, rFv, rD]
    M = matrix(F, rows)
    Kb = M.right_kernel().basis_matrix()
    if Kb.nrows() < _sage_const_1 :
        return None
    coef = sum(F(random.randrange(_sage_const_7 )) * Kb.row(r) for r in range(Kb.nrows()))
    A = [coef[_sage_const_3 *i] + coef[_sage_const_3 *i+_sage_const_1 ]*X + coef[_sage_const_3 *i+_sage_const_2 ]*Y for i in range(_sage_const_4 )]
    if A[_sage_const_3 ] == _sage_const_0 :
        return None
    return A, list(zip(nodes, vvals))


def PQ_of(A):
    a0, a1, a2, a3 = A
    P = a1*a3 - a2**_sage_const_2 /F(_sage_const_3 )
    Q = a0*a3**_sage_const_2  - a1*a2*a3/F(_sage_const_3 ) + _sage_const_2 *a2**_sage_const_3 /F(_sage_const_27 )
    return P, Q


def node_branches(Ppoly, Qpoly, x0, y0, W0):
    """Two branches of W^3 + P W + Q at a double root W0 over (x0,y0)."""
    xs, ys = e0_series_at(x0, y0)
    Ps, Qs = Ppoly(xs, ys), Qpoly(xs, ys)
    c1 = _sage_const_3 *W0**_sage_const_2  + Ps
    c0 = W0**_sage_const_3  + Ps*W0 + Qs
    if c0 == _sage_const_0  or c1 == _sage_const_0 :
        return None
    if c0.valuation() < _sage_const_2  or c1.valuation() < _sage_const_1  or W0 == _sage_const_0 :
        return None
    outs = []
    for sgn in (_sage_const_1 , -_sage_const_1 ):
        w = _sage_const_0 *s
        okb = False
        for _ in range(NTR + _sage_const_8 ):
            disc = c1**_sage_const_2  - _sage_const_12 *W0*(c0 + w**_sage_const_3 )
            r = sqrt_series(disc)
            if r is None:
                return None
            w2 = (-c1 + K6(sgn)*r)/(_sage_const_6 *W0)
            if (w2 - w) == _sage_const_0 :
                okb = True
                w = w2
                break
            w = w2
        outs.append(W0 + w)
    if (outs[_sage_const_0 ] - outs[_sage_const_1 ]) == _sage_const_0  or (outs[_sage_const_0 ]-outs[_sage_const_1 ]).valuation() > _sage_const_2 :
        return None
    return xs, ys, outs


def fiber_branches(Ppoly, Qpoly, pl):
    if pl == 'O':
        xs, ys = e0_series_O()
    else:
        xs, ys = e0_series_at(K6(pl[_sage_const_0 ]), K6(pl[_sage_const_1 ]))
    Ps, Qs = Ppoly(xs, ys), Qpoly(xs, ys)
    vq = Qs.valuation()
    branches = []
    if pl == 'O':
        if vq != -_sage_const_9 :
            return None
        lead = z**_sage_const_3  + (Ps.coefficients()[_sage_const_0 ] if Ps.valuation() == -_sage_const_6  else _sage_const_0 )*z             + Qs.coefficients()[_sage_const_0 ]
        rts = lead.roots()
        if len(rts) != _sage_const_3 :
            return None
        for (c0, _) in rts:
            u = c0*s**-_sage_const_3 
            for _ in range(NTR + _sage_const_6 ):
                u = u - (u**_sage_const_3  + Ps*u + Qs)/(_sage_const_3 *u**_sage_const_2  + Ps)
            branches.append(u)
    else:
        rts = (z**_sage_const_3  + Ps.coefficients()[_sage_const_0 ]*z + Qs.coefficients()[_sage_const_0 ]).roots()             if Ps.valuation() == _sage_const_0  and vq == _sage_const_0  else             (z**_sage_const_3  + (Ps[_sage_const_0 ])*z + (Qs[_sage_const_0 ])).roots()
        if len(rts) != _sage_const_3 :
            return None
        for (c0, _) in rts:
            u = c0 + _sage_const_0 *s
            for _ in range(NTR + _sage_const_6 ):
                u = u - (u**_sage_const_3  + Ps*u + Qs)/(_sage_const_3 *u**_sage_const_2  + Ps)
            branches.append(u)
    return xs, ys, branches


def all_places(A, NODES):
    Ppoly, Qpoly = PQ_of(A)
    a0, a1, a2, a3 = A
    PLACES = []
    for pl in ('O', (F(_sage_const_0 ), F(_sage_const_0 )), (F(_sage_const_0 ), F(_sage_const_6 ))):
        fb = fiber_branches(Ppoly, Qpoly, pl)
        if fb is None:
            return None
        xs, ys, brs = fb
        ts = cube_series(ys)
        if ts is None:
            return None
        for vb in brs:
            for kt in range(_sage_const_3 ):
                PLACES.append((xs, ys, vb, ZETA**kt*ts))
    # real nodes
    for ((x0, y0), v0) in NODES:
        W0 = K6(a3(x0, y0))*K6(v0) + K6(a2(x0, y0))/_sage_const_3 
        nb = node_branches(Ppoly, Qpoly, K6(x0), K6(y0), W0)
        if nb is None:
            return None
        xs, ys, outs = nb
        ts = cube_series(ys)
        if ts is None:
            return None
        for wb in outs:
            for kt in range(_sage_const_3 ):
                PLACES.append((xs, ys, wb, ZETA**kt*ts))
    # artifact nodes at a_3-zeros
    res = a3.resultant(GE, Y)
    resx = RX(res(xx, _sage_const_0 ))
    if resx == _sage_const_0 :
        return None
    for (pf, _) in resx.factor():
        if pf.degree() == _sage_const_0 :
            continue
        d = pf.degree()
        if _sage_const_6  % d != _sage_const_0 :
            return None
        Kd = GF(p7**d, 'a') if d > _sage_const_1  else F
        x0r = pf.roots(Kd)[_sage_const_0 ][_sage_const_0 ]
        RY = PolynomialRing(Kd, names=('yy',)); (yy,) = RY._first_ngens(1)
        for (y0r, _) in RY(GE(x0r, yy)).roots():
            if a3(x0r, y0r) != _sage_const_0 :
                continue
            if d == _sage_const_1 :
                x0, y0 = K6(x0r), K6(y0r)
            else:
                emb = Kd.hom([Kd.gen().minimal_polynomial().roots(K6)[_sage_const_0 ][_sage_const_0 ]],
                             K6)
                x0, y0 = emb(x0r), emb(y0r)
            for _ in range(d):
                if x0 == _sage_const_0  or y0 == _sage_const_0 :
                    return None
                W0 = K6(a2(x0, y0))/_sage_const_3 
                if K6(a2(x0, y0)) == _sage_const_0 :
                    return None
                nb = node_branches(Ppoly, Qpoly, x0, y0, W0)
                if nb is None:
                    return None
                xs, ys, outs = nb
                ts = cube_series(ys)
                if ts is None:
                    return None
                for wb in outs:
                    for kt in range(_sage_const_3 ):
                        PLACES.append((xs, ys, wb, ZETA**kt*ts))
                x0, y0 = x0**_sage_const_7 , y0**_sage_const_7 
    return PLACES


GPOOL = [(a, b, i, j) for a in range(-_sage_const_2 , _sage_const_5 ) for b in (_sage_const_0 , _sage_const_1 )
         for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]
G2POOL = [(a, b, i, j) for a in range(-_sage_const_4 , _sage_const_8 ) for b in (_sage_const_0 , _sage_const_1 )
          for i in (_sage_const_0 , _sage_const_1 , _sage_const_2 ) for j in (_sage_const_0 , _sage_const_1 , _sage_const_2 )]


def kernel_grades(PLACES, Ppoly, pool, power):
    dims, bases = [], []
    for j in range(_sage_const_3 ):
        sub = [mp for mp in pool if mp[_sage_const_3 ] == j]
        rows = []
        for (xs, ys, wb, tb) in PLACES:
            Fw = _sage_const_3 *wb**_sage_const_2  + Ppoly(xs, ys)
            w0 = xs.derivative() / (_sage_const_2 *ys + _sage_const_2 *xs + _sage_const_1 )
            pref = (tb**j) * w0**power / Fw**power
            sers = [xs**a * ys**b * wb**i * pref for (a, b, i, jj) in sub]
            minv = min(ss.valuation() for ss in sers)
            for order in range(minv, _sage_const_0 ):
                rows.append([ss[order] for ss in sers])
        Kb = matrix(K6, rows).right_kernel().basis_matrix()
        dims.append(Kb.nrows())
        bases.append((sub, Kb))
    return dims, bases


def evg(row, sub, pt):
    x0, y0, w0v, t0 = pt
    val = K6(_sage_const_0 )
    for cc, (a, b, i, jj) in zip(row, sub):
        if cc:
            val += cc * x0**a * y0**b * w0v**i * t0**jj
    return val


found = _sage_const_0 
for trial in range(_sage_const_400 ):
    cand = build_candidate()
    if cand is None:
        continue
    A, NODES = cand
    Ppoly, Qpoly = PQ_of(A)
    PLACES = all_places(A, NODES)
    if PLACES is None:
        continue
    found += _sage_const_1 
    dims, bases = kernel_grades(PLACES, Ppoly, GPOOL, _sage_const_1 )
    if sum(dims) != _sage_const_10 :
        if found <= _sage_const_6 :
            print(f"cand {found}: gates {dims} Sigma {sum(dims)} — reject",
                  flush=True)
        continue
    if dims != [_sage_const_4 , _sage_const_3 , _sage_const_3 ]:
        print(f"cand {found}: gates {dims} — odd split", flush=True)
        continue
    print(f"cand {found}: gates [4,3,3] PASS  (nodes {NODES})", flush=True)
    # witnesses
    WITS = []
    tries = _sage_const_0 
    while len(WITS) < _sage_const_40  and tries < _sage_const_5000 :
        tries += _sage_const_1 
        x0 = K6.random_element()
        if x0 == _sage_const_0 :
            continue
        yr = (z**_sage_const_2  + (_sage_const_2 *x0+_sage_const_1 )*z - x0**_sage_const_3 ).roots()
        if not yr:
            continue
        y0 = yr[random.randrange(len(yr))][_sage_const_0 ]
        if y0 == _sage_const_0 :
            continue
        Pv, Qv = Ppoly(x0, y0), Qpoly(x0, y0)
        wr = (z**_sage_const_3  + Pv*z + Qv).roots()
        if not wr:
            continue
        w0v = wr[random.randrange(len(wr))][_sage_const_0 ]
        if _sage_const_3 *w0v**_sage_const_2  + Pv == _sage_const_0 :
            continue
        tr2 = (z**_sage_const_3  - y0).roots()
        if not tr2:
            continue
        WITS.append((x0, y0, w0v, tr2[_sage_const_0 ][_sage_const_0 ]))
    if len(WITS) < _sage_const_40 :
        continue
    sub0, K0 = bases[_sage_const_0 ]
    qrows = []
    for pt in WITS[:_sage_const_25 ]:
        zc = [evg(K0.row(r), sub0, pt) for r in range(_sage_const_4 )]
        qrows.append([zc[a]*zc[b] for a in range(_sage_const_4 ) for b in range(a, _sage_const_4 )])
    KQ = matrix(K6, qrows).right_kernel().basis_matrix()
    if KQ.nrows() != _sage_const_1 :
        print(f"  {KQ.nrows()} quadrics — skip", flush=True)
        continue
    qv = KQ.row(_sage_const_0 )
    Sm = matrix(K6, _sage_const_4 , _sage_const_4 )
    idx = _sage_const_0 
    for a in range(_sage_const_4 ):
        for b in range(a, _sage_const_4 ):
            if a == b:
                Sm[a, a] = qv[idx]
            else:
                Sm[a, b] += qv[idx]/_sage_const_2 
                Sm[b, a] += qv[idx]/_sage_const_2 
            idx += _sage_const_1 
    qr = Sm.rank()
    print(f"  quadric rank = {qr}", flush=True)
    if qr != _sage_const_4 :
        continue
    print(f"  *** NON-THETANULL (3,3)-SPECIMEN — running rigidity ***",
          flush=True)
    dims2, _ = kernel_grades(PLACES, Ppoly, G2POOL, _sage_const_2 )
    print(f"  h^0(omega~^2) grades {dims2} (Sigma {sum(dims2)}, expect 27)",
          flush=True)
    rowsM, labels = [], []
    for j1 in range(_sage_const_3 ):
        subA, KA = bases[j1]
        for j2 in (_sage_const_1 , _sage_const_2 ):
            subB, KB = bases[j2]
            for ra in range(KA.nrows()):
                for rb in range(KB.nrows()):
                    row = []
                    for pt in WITS:
                        x0, y0, w0v, t0 = pt
                        Fw = _sage_const_3 *w0v**_sage_const_2  + Ppoly(x0, y0)
                        row.append(evg(KA.row(ra), subA, pt) *
                                   evg(KB.row(rb), subB, pt) / Fw**_sage_const_2 )
                    rowsM.append(row)
                    labels.append((j1 + j2) % _sage_const_3 )
    rk = matrix(K6, rowsM).rank()
    print(f"  RIGIDITY RANK = {rk} of 27  "
          f"({'*** SURJECTIVE — GENERIC RIGIDITY CERTIFIED ***' if rk == _sage_const_27  else 'corank ' + str(_sage_const_27  - rk)})",
          flush=True)
    for gt in range(_sage_const_3 ):
        subr = [rowsM[i] for i in range(len(rowsM)) if labels[i] == gt]
        print(f"    sigma-grade {gt}: rank {matrix(K6, subr).rank()} of 9",
              flush=True)
    if rk == _sage_const_27 :
        break
print(f"done; viable candidates: {found}", flush=True)

