

# This file was *autogenerated* from the file tmp/weil_eightfold_lpoly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_60 = Integer(60); _sage_const_9 = Integer(9); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_0p5 = RealNumber('0.5'); _sage_const_8 = Integer(8); _sage_const_13 = Integer(13)# Eightfold flex construction: C' : u^3 - 3(1+x)^2 u + (2(1+x)^3 + y + 2x + 1) = 0
# over E0 : y^2 + 2xy + y = x^3;  C : t^3 = y.  Claimed g' = 5, Prym dim 8, sig (4,4).
#
# Stage 1 (p = 7): counts k = 1..6; FE-complete an assumed-degree-10 numerator from
#   k <= 5, purity check, AND overdetermination: predict #C'(F_{7^6}) from the poly,
#   compare to the actual count  ==> genus-5 certificate at full strength.
# Stage 2 (p = 7): counts of C up to k = 8; Prym power sums s_k = #C' - #C (Schoen
#   convention); Newton with g = 8 -> FE-complete deg-16 P_Prym; purity; factor over ZZ.
#   IRREDUCIBLE at the split prime 7  ==>  the eightfold is SIMPLE (any isogeny factor
#   over Q or over K = Q(sqrt(-3)) would factor P).
# Stage 3 (p = 13): genus-5 certificate cross-check (k <= 6).

def counts(p, k):
    q = p ** k
    F = GF(q, 'g')
    R = PolynomialRing(F, 'U')
    U = R.gen()
    one_third = _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_1 
    third = (q - _sage_const_1 ) // _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_0 
    nE0 = _sage_const_1 
    nCp = _sage_const_0 
    nC = _sage_const_0 
    for x0 in F:
        b = _sage_const_2  * x0 + _sage_const_1 
        D = b * b + _sage_const_4  * x0 ** _sage_const_3 
        if D == _sage_const_0 :
            ys = [-b / _sage_const_2 ]
        elif D.is_square():
            s = D.sqrt()
            ys = [(-b + s) / _sage_const_2 , (-b - s) / _sage_const_2 ]
        else:
            ys = []
        for y0 in ys:
            nE0 += _sage_const_1 
            f = U ** _sage_const_3  - _sage_const_3  * (_sage_const_1  + x0) ** _sage_const_2  * U + (_sage_const_2  * (_sage_const_1  + x0) ** _sage_const_3  + y0 + _sage_const_2  * x0 + _sage_const_1 )
            nu = len(f.roots(multiplicities=False))
            if y0 == _sage_const_0 :
                nt = one_third
            elif q % _sage_const_3  == _sage_const_1 :
                nt = _sage_const_3  if y0 ** third == _sage_const_1  else _sage_const_0 
            else:
                nt = _sage_const_1 
            nCp += nu
            nC += nu * nt
    nCp += _sage_const_2                       # O: e=2 place + unramified slope-2 branch
    nC += _sage_const_2  * one_third
    return nE0, nCp, nC


def fe_lpoly_from_powersums(p, s, g):
    # s[k-1] = power sum of the 2g Frobenius roots, k = 1..g; FE-complete.
    e = [_sage_const_1 ] + [_sage_const_0 ] * g
    for k in range(_sage_const_1 , g + _sage_const_1 ):
        acc = _sage_const_0 
        for i in range(_sage_const_1 , k + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e[k - i] * s[i - _sage_const_1 ]
        e[k] = acc / k
    c = [_sage_const_0 ] * (_sage_const_2  * g + _sage_const_1 )
    for j in range(g + _sage_const_1 ):
        c[j] = (-_sage_const_1 ) ** j * e[j]
    for j in range(g):
        c[_sage_const_2  * g - j] = p ** (g - j) * c[j]
    S = PolynomialRing(QQ, 'T')
    T = S.gen()
    return sum(QQ(c[j]) * T ** j for j in range(_sage_const_2  * g + _sage_const_1 ))


def purity(P, p):
    rts = P.change_ring(CDF).roots(multiplicities=False)
    return all(abs(abs(r) ** _sage_const_2  * p - _sage_const_1 ) < _sage_const_1en6  for r in rts),         sorted(set(round(abs(r) ** _sage_const_2  * p, _sage_const_3 ) for r in rts))


print("=" * _sage_const_60 )
print("STAGE 1+2: p = 7, k = 1..8")
NsC, NsCp = [], []
for k in range(_sage_const_1 , _sage_const_9 ):
    nE0, nCp, nC = counts(_sage_const_7 , k)
    NsCp.append(nCp)
    NsC.append(nC)
    print(f"k={k} q={_sage_const_7 **k}: #E0={nE0} #C'={nCp} #C={nC}  s_k={nCp - nC}")
    sys.stdout.flush()

tC = [_sage_const_7  ** k + _sage_const_1  - NsCp[k - _sage_const_1 ] for k in range(_sage_const_1 , _sage_const_6 )]
P5 = fe_lpoly_from_powersums(_sage_const_7 , tC, _sage_const_5 )
ok5, pur5 = purity(P5, _sage_const_7 )
print("P_C'(T) deg", P5.degree(), ":", P5)
print("|root|^2 * 7:", pur5, "->", "PASS" if ok5 else "FAIL")
# overdetermination: predict #C'(F_{7^6}) from P5
S = PolynomialRing(QQ, 'T')
T = S.gen()
alpha_pows6 = sum(r ** _sage_const_6  for r in P5.change_ring(CDF).roots(multiplicities=False))
pred6 = _sage_const_7  ** _sage_const_6  + _sage_const_1  - alpha_pows6.real()
print(f"overdetermination k=6: predicted #C' = {pred6:.2f}, actual = {NsCp[5]}",
      "PASS" if abs(pred6 - NsCp[_sage_const_5 ]) < _sage_const_0p5  else "FAIL")
print("GENUS 5 CERTIFICATE (p=7):",
      "PASS" if ok5 and abs(pred6 - NsCp[_sage_const_5 ]) < _sage_const_0p5  else "FAIL")
print("factor over ZZ:", factor(P5))
sys.stdout.flush()

sPrym = [NsCp[k - _sage_const_1 ] - NsC[k - _sage_const_1 ] for k in range(_sage_const_1 , _sage_const_9 )]
print("Prym power sums s_1..s_8:", sPrym)
PP = fe_lpoly_from_powersums(_sage_const_7 , sPrym, _sage_const_8 )
okP, purP = purity(PP, _sage_const_7 )
print("P_Prym(T) deg", PP.degree(), ":", PP)
print("|root|^2 * 7:", purP, "->", "PASS" if okP else "FAIL")
fac = factor(PP)
print("factor over ZZ:", fac)
irr = len(list(fac)) == _sage_const_1  and fac[_sage_const_0 ][_sage_const_1 ] == _sage_const_1 
print("SIMPLICITY CERTIFICATE (deg-16 irreducible at split p=7):",
      "PASS -- SIMPLE ABELIAN EIGHTFOLD" if irr else "NOT IRREDUCIBLE -- inspect")
sys.stdout.flush()

print("=" * _sage_const_60 )
print("STAGE 3: p = 13 genus-5 cross-check, k = 1..6")
Ns13 = []
for k in range(_sage_const_1 , _sage_const_7 ):
    nE0, nCp, nC = counts(_sage_const_13 , k)
    Ns13.append(nCp)
    print(f"k={k} q={_sage_const_13 **k}: #E0={nE0} #C'={nCp} #C={nC}  s_k={nCp - nC}")
    sys.stdout.flush()
t13 = [_sage_const_13  ** k + _sage_const_1  - Ns13[k - _sage_const_1 ] for k in range(_sage_const_1 , _sage_const_6 )]
Q5 = fe_lpoly_from_powersums(_sage_const_13 , t13, _sage_const_5 )
ok13, pur13 = purity(Q5, _sage_const_13 )
alpha6 = sum(r ** _sage_const_6  for r in Q5.change_ring(CDF).roots(multiplicities=False))
pred = _sage_const_13  ** _sage_const_6  + _sage_const_1  - alpha6.real()
print("P_C'(T):", Q5)
print("|root|^2 * 13:", pur13)
print(f"overdetermination k=6: predicted {pred:.2f}, actual {Ns13[5]}")
print("GENUS 5 CERTIFICATE (p=13):",
      "PASS" if ok13 and abs(pred - Ns13[_sage_const_5 ]) < _sage_const_0p5  else "FAIL")
print("factor over ZZ:", factor(Q5))

