

# This file was *autogenerated* from the file tmp/weil_tenfold_lpoly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_13 = Integer(13); _sage_const_60 = Integer(60); _sage_const_6 = Integer(6); _sage_const_1en6 = RealNumber('1e-6')# Tenfold base C' : u^3 + x*u + (y + x^2 + a) = 0 over E0 : y^2 + 2xy + y = x^3.
# Genus-6 CERTIFICATE: count #C'(F_{p^k}) for k = 1..6, Newton -> elementary symmetric
# -> FE-complete to an assumed-degree-12 numerator -> purity |root|^2 * p = 1 for all
# 12 roots.  Purity pass <=> the numerator really has degree 12 <=> g(C') = 6 EXACTLY
# (a wrong genus assumption breaks the functional-equation completion and purity).
# Also records #C(F_{p^k}) and Prym s_k = #C' - #C for the eventual deg-20 analysis.

A_PARAM = _sage_const_1 


def counts(p, k, a=A_PARAM):
    q = p ** k
    F = GF(q, 'g')
    R = PolynomialRing(F, 'U')
    U = R.gen()
    one_third = _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_1 
    third = (q - _sage_const_1 ) // _sage_const_3  if q % _sage_const_3  == _sage_const_1  else _sage_const_0 
    nE0 = _sage_const_1           # O
    nCp = _sage_const_0 
    nC = _sage_const_0 
    aF = F(a)
    for x0 in F:
        b = _sage_const_2  * x0 + _sage_const_1 
        D = b * b + _sage_const_4  * x0 ** _sage_const_3 
        if D == _sage_const_0 :
            ys = [-b / _sage_const_2 ]
        elif D.is_square():
            s = D.sqrt()
            ys = [(-b + s) / _sage_const_2 , (-b - s) / _sage_const_2 ]
        else:
            ys = []
        for y0 in ys:
            nE0 += _sage_const_1 
            f = U ** _sage_const_3  + x0 * U + (y0 + x0 ** _sage_const_2  + aF)
            nu = len(f.roots(multiplicities=False))
            if y0 == _sage_const_0 :
                nt = one_third                    # T: leading coeff of y is a cube
            elif q % _sage_const_3  == _sage_const_1 :
                nt = _sage_const_3  if y0 ** third == _sage_const_1  else _sage_const_0 
            else:
                nt = _sage_const_1 
            nCp += nu
            nC += nu * nt
    nCp += _sage_const_1                                       # O: totally ramified, one point
    nC += one_third                               # tau^3 = (unit)^3
    return nE0, nCp, nC


def fe_lpoly(p, Ns, g):
    # Ns[k-1] = #C'(F_{p^k}), k = 1..g; numerator P(T) = prod (1 - a_i T), deg 2g.
    t = [p ** (k) + _sage_const_1  - Ns[k - _sage_const_1 ] for k in range(_sage_const_1 , g + _sage_const_1 )]   # power sums s_k
    e = [_sage_const_1 ] + [_sage_const_0 ] * g
    for k in range(_sage_const_1 , g + _sage_const_1 ):
        acc = _sage_const_0 
        for i in range(_sage_const_1 , k + _sage_const_1 ):
            acc += (-_sage_const_1 ) ** (i - _sage_const_1 ) * e[k - i] * t[i - _sage_const_1 ]
        e[k] = acc / k
    # coefficients of P: c_j = (-1)^j e_j for j <= g; FE: c_{2g-j} = p^{g-j} c_j
    c = [_sage_const_0 ] * (_sage_const_2  * g + _sage_const_1 )
    for j in range(g + _sage_const_1 ):
        c[j] = (-_sage_const_1 ) ** j * e[j]
    for j in range(g):
        c[_sage_const_2  * g - j] = p ** (g - j) * c[j]
    S = PolynomialRing(QQ, 'T')
    T = S.gen()
    P = sum(QQ(c[j]) * T ** j for j in range(_sage_const_2  * g + _sage_const_1 ))
    return P


for p in [_sage_const_7 , _sage_const_13 ]:
    print("=" * _sage_const_60 )
    print(f"p = {p}")
    Ns, Ms = [], []
    for k in range(_sage_const_1 , _sage_const_7 ):
        nE0, nCp, nC = counts(p, k)
        Ns.append(nCp)
        Ms.append(nC)
        print(f"k={k} q={p**k}: #E0={nE0} #C'={nCp} #C={nC}  s_{k}={nCp - nC}")
        sys.stdout.flush()
    P = fe_lpoly(p, Ns, _sage_const_6 )
    print("P_C'(T) deg", P.degree(), ":", P)
    rts = P.change_ring(CDF).roots(multiplicities=False)
    purity = sorted(set(round(abs(r) ** _sage_const_2  * p, _sage_const_3 ) for r in rts))
    print("|root|^2 * p (all must be 1.000):", purity)
    ok = all(abs(abs(r) ** _sage_const_2  * p - _sage_const_1 ) < _sage_const_1en6  for r in rts)
    print("GENUS 6 CERTIFICATE:", "PASS" if ok else "FAIL")
    print("factor over ZZ:", factor(P))

