

# This file was *autogenerated* from the file tmp/weil_sixfold_v2_p13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_13 = Integer(13); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_12 = Integer(12)# v2 (involution-hardened) sixfold: degree-12 L-poly at p=7, full k<=6 tower.
# C' : u^3 + x*u + (y+a) = 0 over E0;  C : t^3 = y.  n_u now depends on BOTH coordinates.
# O-fiber for u: residual cubic w^3 + w + 1 (disc -31; sign-independent).
# THE QUESTION: is P_B still a square at the split prime -- or not (tau-mechanism gone)?

p = _sage_const_13 
a_par = _sage_const_1 
KMAX = _sage_const_6 

def counts(q):
    F = GF(q)
    R = PolynomialRing(F, names=('u',)); (u,) = R._first_ngens(1)
    three_div = (q - _sage_const_1 ) % _sage_const_3  == _sage_const_0 
    e3 = (q - _sage_const_1 ) // _sage_const_3  if three_div else None
    def n_cube(v):
        if v == _sage_const_0 :
            return _sage_const_1 
        if not three_div:
            return _sage_const_1 
        return _sage_const_3  if v**e3 == _sage_const_1  else _sage_const_0 
    sum_nt = _sage_const_0 ; nCp = _sage_const_0 ; nC = _sage_const_0 ; nE0 = _sage_const_1 
    nuO = len((u**_sage_const_3  + u + _sage_const_1 ).roots(multiplicities=False))   # residual at O
    ntO = n_cube(F(-_sage_const_1 ))
    sum_nt += ntO; nCp += nuO; nC += nuO * ntO
    two = F(_sage_const_2 ); four = F(_sage_const_4 )
    for x in F:
        b = two * x + _sage_const_1 ; d = b*b + four * x**_sage_const_3 
        if d == _sage_const_0 :
            ys = [-b / two]
        elif d.is_square():
            s = d.sqrt(); ys = [(-b + s)/two, (-b - s)/two]
        else:
            ys = []
        for y0 in ys:
            nE0 += _sage_const_1 
            nu = len((u**_sage_const_3  + x*u + (y0 + a_par)).roots(multiplicities=False))
            nt = n_cube(F(_sage_const_1 )) if (x == _sage_const_0  and y0 == _sage_const_0 ) else n_cube(y0)
            sum_nt += nt; nCp += nu; nC += nu * nt
    assert sum_nt == nE0, (q, sum_nt, nE0)
    return nE0, nCp, nC

s = []
for k in range(_sage_const_1 , KMAX + _sage_const_1 ):
    q = p**k
    nE0, nCp, nC = counts(q)
    s.append(nCp - nC)
    print(f"k={k} q={q}: #E0={nE0} #C'={nCp} #C={nC}  s_{k}={nCp-nC}")

e = [QQ(_sage_const_1 )]
for k in range(_sage_const_1 , KMAX + _sage_const_1 ):
    acc = QQ(_sage_const_0 )
    for i in range(_sage_const_1 , k + _sage_const_1 ):
        acc += (-_sage_const_1 )**(i - _sage_const_1 ) * e[k - i] * s[i - _sage_const_1 ]
    e.append(acc / k)
for j in range(_sage_const_7 , _sage_const_13 ):
    e.append(QQ(p)**(j - _sage_const_6 ) * e[_sage_const_12  - j])
RZ = ZZ['T']; (T,) = RZ._first_ngens(1)
P = RZ(sum((-_sage_const_1 )**j * e[j] * T**j for j in range(_sage_const_13 )))
print("\nP_B(T) =", P)
print("\nfactor over ZZ:", P.factor())
print("\n|roots|^2 * p (want all 1.000):",
      sorted(set(round(abs(r)**_sage_const_2  * p, _sage_const_3 ) for r in P.roots(CC, multiplicities=False))))

