

# This file was *autogenerated* from the file tmp/ws_c3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12)# Weil sixfold candidate: degree-12 Prym L-polynomial via exact counts over GF(p^k), k<=6.
# RUN: sage tmp/weil_sixfold_lpoly.sage      (Sage GF only -- no FunctionField, per house note)
#
# Construction (weil-sixfold-hunt dossier, validated k=1 by tmp/weil_sixfold.py, 14/14 PASS):
#   E0 : y^2 + 2xy + y = x^3   (Schoen curve, cond 19);  C' : u^3 + x*u + c = 0 (genus 4,
#   non-Galois cubic cover -- involution-free bet);  C : t^3 = y (etale, genus 10).
#   Prym dim 6, signature (3,3), Q(zeta3)-multiplication.
#   s_k = #C(F_{p^k}) - #C'(F_{p^k}) = sum of 12 Frobenius eigenvalues^k.
# Newton -> e_1..e_6 (exact in QQ), functional equation e_{12-j} = p^{6-j} e_j -> P_B(T).
# Verdict: factor P_B over QQ.  Simple-candidate signature: no square factor, no low-degree
# split matching the decomposable (occ-18) pattern that killed the bielliptic route.

p = _sage_const_7 
c = _sage_const_3 
KMAX = _sage_const_6 

def counts(q):
    F = GF(q)
    R = PolynomialRing(F, names=('u',)); (u,) = R._first_ngens(1)
    three_div = (q - _sage_const_1 ) % _sage_const_3  == _sage_const_0 
    e3 = (q - _sage_const_1 ) // _sage_const_3  if three_div else None
    def n_t(y0):
        if y0 == _sage_const_0 :
            return _sage_const_1 
        if not three_div:
            return _sage_const_1 
        return _sage_const_3  if y0**e3 == _sage_const_1  else _sage_const_0 
    def n_cube(a):  # roots of t^3 = a
        return n_t(a) if a != _sage_const_0  else _sage_const_1 
    sum_nt = _sage_const_0 ; nCp = _sage_const_0 ; nC = _sage_const_0 ; nE0 = _sage_const_1   # start with O
    # O contributions
    nuO = _sage_const_1  + (_sage_const_2  if F(-_sage_const_1 ).is_square() else _sage_const_0 )
    ntO = n_cube(F(-_sage_const_1 ))
    sum_nt += ntO; nCp += nuO; nC += nuO * ntO
    two = F(_sage_const_2 ); four = F(_sage_const_4 )
    for x in F:
        # y^2 + (2x+1) y - x^3 = 0
        b = two * x + _sage_const_1 ; d = b*b + four * x**_sage_const_3 
        if d == _sage_const_0 :
            ys = [-b / two]
        elif d.is_square():
            s = d.sqrt(); ys = [(-b + s)/two, (-b - s)/two]
        else:
            ys = []
        if not ys:
            continue
        nu = len((u**_sage_const_3  + x*u + c).roots(multiplicities=False))
        for y0 in ys:
            nE0 += _sage_const_1 
            nt = n_cube(F(_sage_const_1 )) if (x == _sage_const_0  and y0 == _sage_const_0 ) else n_t(y0)  # T: leading 1/a3 = 1
            sum_nt += nt; nCp += nu; nC += nu * nt
    assert sum_nt == nE0, (q, sum_nt, nE0)   # cross-check A (3-isogeny)
    return nE0, nCp, nC

s = []
for k in range(_sage_const_1 , KMAX + _sage_const_1 ):
    q = p**k
    nE0, nCp, nC = counts(q)
    s.append(nCp - nC)   # Prym power sum: a_C(k) - a_C'(k) = #C' - #C  (Schoen convention)
    print(f"k={k} q={q}: #E0={nE0} #C'={nCp} #C={nC}  s_{k}={nCp-nC}")

# Newton's identities (power sums -> elementary symmetric), exact over QQ
e = [QQ(_sage_const_1 )]
for k in range(_sage_const_1 , KMAX + _sage_const_1 ):
    acc = QQ(_sage_const_0 )
    for i in range(_sage_const_1 , k + _sage_const_1 ):
        acc += (-_sage_const_1 )**(i - _sage_const_1 ) * e[k - i] * s[i - _sage_const_1 ]
    e.append(acc / k)
# functional equation completes e_7..e_12
for j in range(_sage_const_7 , _sage_const_13 ):
    e.append(QQ(p)**(j - _sage_const_6 ) * e[_sage_const_12  - j])
RZ = ZZ['T']; (T,) = RZ._first_ngens(1)
P = RZ(sum((-_sage_const_1 )**j * e[j] * T**j for j in range(_sage_const_13 )))
print("\nP_B(T) =", P)
print("\nfactor over ZZ:", P.factor())
# Weil purity: roots at |r| = 1/sqrt(p), i.e. |r|^2 * p = 1 exactly
print("\n|roots|^2 * p (want all 1.000):",
      sorted(set(round(abs(r)**_sage_const_2  * p, _sage_const_3 ) for r in P.roots(CC, multiplicities=False))))

