import numpy as np
# GL(n) rung (Sym^r -> GL(r+1) is the linear target).  Carrier = Z^n lattice with metric Y (posdef);
# Epstein theta Theta(Y,t)=sum_{x in Z^n} e^{-pi t x^t Y x}.  Poisson S: Y->Y^{-1}.  Clocks = GL(n,Z)
# acting Y->U^t Y U, generated by ELEMENTARY transvections E_ij (the linear clocks).
def theta(Y, t, M=14):
    n = Y.shape[0]
    rng = range(-M, M+1)
    import itertools
    s = 0.0
    for x in itertools.product(rng, repeat=n):
        x = np.array(x, float)
        s += np.exp(-np.pi*t*(x @ Y @ x))
    return s

n = 3
Y = np.array([[2.0,0.5,0.3],[0.5,1.7,-0.4],[0.3,-0.4,1.9]])   # posdef metric (a symmetric-space point)
# (S) Poisson: Theta(Y,t) = t^{-n/2} det(Y)^{-1/2} Theta(Y^{-1}, 1/t)
t = 0.9
lhs = theta(Y, t)
rhs = t**(-n/2)*np.linalg.det(Y)**(-0.5)*theta(np.linalg.inv(Y), 1/t)
print(f"  (S) GL({n}) Poisson: Theta(Y,t) - t^-n/2 det(Y)^-1/2 Theta(Y^-1,1/t) = {abs(lhs-rhs):.2e}")

# (clocks) elementary transvections E_ij = I + e_ij  -- the linear clocks -- act Y -> E^t Y E,
# and leave the lattice sum INVARIANT (relabel x -> E^{-1} x in Z^n):
def E(i,j):
    A = np.eye(n); A[i,j] = 1.0; return A
inv_defect = []
for (i,j) in [(0,1),(1,2),(2,0),(0,2)]:
    Ee = E(i,j)
    inv_defect.append(abs(theta(Ee.T @ Y @ Ee, t) - theta(Y, t)))
    print(f"  (clock) transvection E_{i}{j}: det={round(np.linalg.det(Ee))}, |Theta(E^tYE)-Theta(Y)| = {inv_defect[-1]:.2e}")
# permutation (Weyl) clock too:
P = np.array([[0,1,0],[0,0,1],[1,0,0]],float)
print(f"  (clock) Weyl/perm P: det={round(np.linalg.det(P))}, |Theta(P^tYP)-Theta(Y)| = {abs(theta(P.T@Y@P,t)-theta(Y,t)):.2e}")
# generation fact: SL(n,Z) is generated by the elementary transvections E_ij (classical, Bass-Milnor-Serre);
# GL(n,Z) adds a sign.  All E_ij, P are in GL(n,Z) (integer, det +-1):
gens = [E(i,j) for (i,j) in [(0,1),(1,2),(2,0),(0,2),(1,0),(2,1)]] + [P]
allint = all(np.allclose(g, np.round(g)) and abs(round(np.linalg.det(g)))==1 for g in gens)
print(f"  all clocks in GL({n},Z) (integer, det +-1): {allint}")
print(f"  => emergent carrier clocks: elementary transvections (linear) generate SL({n},Z);")
print(f"     + Poisson S (Y->Y^-1) => the GL({n},Z) automorphy group, carrier-generated.")
print(f"     Tower: SL(2)[arclength] -> Sp(4)[symmetric] -> GL({n})[elementary].  All from the carrier.")
