import RequestProject.HelixFlowUnitaryGroup

/-!
# A concrete Stone's theorem for the phasor flow

Abstract Stone (every strongly-continuous one-parameter unitary group has a self-adjoint generator) is
absent from Mathlib. But for *this* setup it is unnecessary: the diagonal flow `U(t)(n) = n^{it}` has
its generator in **closed form** — multiplication by `log n`. So the Stone content is *computed*, not
invoked:

* `gen n = log n` — the generator's diagonal symbol, **real** (so `H = diag(log n)` is self-adjoint).
* `phasorFlow_eq_exp` — `U(t)(n) = e^{i·t·log n}` (`U(t) = e^{itH}`).
* `phasorFlow_hasDerivAt` — `d/dt U(t)(n) = i·log n · U(t)(n)` (the generator equation `U' = iH·U`).
* `phasorFlow_hasDerivAt_zero` — `U'(0)(n) = i·log n` (the **infinitesimal generator** is `iH`).
* `gen_real` — the generator is real, hence self-adjoint.

## This is the PRIME-side generator, NOT the Hilbert–Pólya operator

Its spectrum is `{log n}` — the **primes'** logs, real but **not** the zeros. So `H = diag(log n)` is the
**prime-side** generator. The actual Hilbert–Pólya self-adjoint operator is its **dual** `H_z`, whose
spectrum *is* the nontrivial-zero parameters. The two are different operators, linked by a single
function:

* **`H` (prime side, built here):** spectrum `{log n}`; its log-determinant trace (the von Mangoldt
  chain) is `−L'/L` — `HelixFlowVonMangoldt.flowVonMangoldtTrace_eq_neg_logDeriv`.
* **`H_z` (zero side, the H–P operator):** spectrum = the zeros; its *resolvent* trace is `−L'/L` — the
  trace identity, the open weld (`HelixResolventCapture`).

**The link is `−L'/L`, read two ways** — the prime side's log-det trace *and* the zero side's resolvent
trace. The von Mangoldt explicit formula is exactly this duality, and the zeros are the **resonances**
of `−L'/L` (`EnergyBalance.resonates_at_zeros`), hence the spectrum of `H_z`. So: the line is forced not
by *this* generator's reality (its spectrum is the primes) but by the flow's **unitarity** carried onto
the **dual** operator `H_z` — never confuse the two.
-/

open Complex HelixFlow HelixLogFree

namespace HelixFlowGenerator

/-- The **generator's diagonal symbol** `H(n) = log n`. Real, so `H = diag(log n)` is self-adjoint. -/
noncomputable def gen (n : ℕ) : ℝ := Real.log n

/-- The winding-angle bridge for **all** `n` (the `n = 0` case is `0 = t·log 0`, both `0`). -/
theorem windAngle_log_all (t : ℝ) (n : ℕ) :
    windAngle (fun p => t * Real.log p) n = t * Real.log n := by
  rcases eq_or_ne n 0 with hn | hn
  · subst hn; simp [windAngle, Finsupp.sum]
  · exact HelixImaginaryAxis.windAngle_log_bridge t n hn

/-- **`U(t) = e^{itH}`.** The flow is the exponential of `i·t` times the real generator `H(n) = log n`:
    `(phasorFlow t n : ℂ) = exp(I·(t·log n))`. -/
theorem phasorFlow_eq_exp (t : ℝ) (n : ℕ) :
    (phasorFlow t n : ℂ) = Complex.exp (Complex.I * ((t : ℂ) * (gen n : ℂ))) := by
  show (wind (fun p => t * Real.log p) n : ℂ) = _
  rw [wind, Circle.coe_exp, windAngle_log_all]
  congr 1
  rw [gen]; push_cast; ring

/-- **The generator equation `U'(t) = iH·U(t)`.** Per mode, `d/dt U(t)(n) = i·log n · U(t)(n)` — the
    flow is generated by `i` times the real diagonal operator `H = diag(log n)`. -/
theorem phasorFlow_hasDerivAt (t : ℝ) (n : ℕ) :
    HasDerivAt (fun τ : ℝ => (phasorFlow τ n : ℂ))
      (Complex.I * (gen n : ℂ) * (phasorFlow t n : ℂ)) t := by
  have heq : (fun τ : ℝ => (phasorFlow τ n : ℂ))
      = fun τ : ℝ => Complex.exp (Complex.I * ((τ : ℂ) * (gen n : ℂ))) := by
    funext τ; exact phasorFlow_eq_exp τ n
  rw [heq]
  have hlin : HasDerivAt (fun τ : ℝ => Complex.I * ((τ : ℂ) * (gen n : ℂ)))
      (Complex.I * (gen n : ℂ)) t := by
    have h1 : HasDerivAt (fun τ : ℝ => (τ : ℂ)) 1 t := Complex.ofRealCLM.hasDerivAt
    simpa using ((h1.mul_const (gen n : ℂ)).const_mul Complex.I)
  have hexp := hlin.cexp
  rw [← phasorFlow_eq_exp t n] at hexp
  convert hexp using 1
  ring

/-- **The infinitesimal generator is `iH`.** `U'(0)(n) = i·log n` — the derivative of the flow at
    `t = 0` recovers `i` times the (real) generator `H(n) = log n`. This is the Stone correspondence,
    computed: `U(t) = e^{itH}` ⟹ `U'(0) = iH`. -/
theorem phasorFlow_hasDerivAt_zero (n : ℕ) :
    HasDerivAt (fun τ : ℝ => (phasorFlow τ n : ℂ)) (Complex.I * (gen n : ℂ)) 0 := by
  have h := phasorFlow_hasDerivAt 0 n
  rw [phasorFlow_zero] at h
  simpa using h

/-- **The generator is self-adjoint** — its symbol is real (`gen n = log n ∈ ℝ`, `Im = 0`). A diagonal
    operator with real entries is self-adjoint; its spectrum `{log n}` is real (the primes' logs). -/
theorem gen_real (n : ℕ) : (gen n : ℂ).im = 0 := by simp

/-- **Stone for the phasor flow, assembled.** The strongly-continuous one-parameter unitary group
    `phasorFlow` has the self-adjoint generator `H(n) = log n` (real): `U(t) = e^{itH}`, `U'(0) = iH`,
    `H` real — all by closed-form computation, no abstract Stone. -/
theorem stone_phasorFlow (n : ℕ) :
    (∀ t : ℝ, (phasorFlow t n : ℂ) = Complex.exp (Complex.I * ((t : ℂ) * (gen n : ℂ)))) ∧
      HasDerivAt (fun τ : ℝ => (phasorFlow τ n : ℂ)) (Complex.I * (gen n : ℂ)) 0 ∧
      (gen n : ℂ).im = 0 :=
  ⟨fun t => phasorFlow_eq_exp t n, phasorFlow_hasDerivAt_zero n, gen_real n⟩

end HelixFlowGenerator

#print axioms HelixFlowGenerator.phasorFlow_eq_exp
#print axioms HelixFlowGenerator.phasorFlow_hasDerivAt_zero
#print axioms HelixFlowGenerator.stone_phasorFlow
