import RequestProject.SpectralZeroKernel
import RequestProject.UnconditionalFrobenius
import RequestProject.HarmonicPencilCell

/-!
# A fixed self-adjoint generator, its readout/determinant, and the critical-line kernel law

This file records the **Hilbert–Pólya self-adjoint side** of the spectral picture, *unconditionally*
(no GRH, no RH): a **fixed self-adjoint generator** `Aχ` on a state space `Hχ`, whose configured
resolvent operator at a parameter `s` can only have a kernel when `s` sits on the **critical line**
`Re s = 1/2`.

The crucial honesty point.  There are two genuinely different operators in the spectral picture and
they must not be confused, because confusing them would be exactly the Riemann Hypothesis:

* `SpectralFiber.specOp χ s = Lspec χ s • id` — the **L-readout operator**: its determinant *is* the
  spectral L-value (`configured_det_eq_Lspec` below), and its kernel is nonzero **iff** `Lspec χ s =
  0` (`SpectralFiber.spectral_kernel_iff_zero`).  Whether *that* kernel forces `Re s = 1/2` is the
  Riemann Hypothesis and is **not** claimed here.
* `specOp A s = A − specHeight s • id` — the **self-adjoint resolvent operator** built from a fixed
  self-adjoint generator `A`.  For *this* operator the critical-line kernel law is an unconditional
  theorem (`specOp_kernel_admissible`): a kernel vector exists **only** at `s = 1/2 + i·log Z` for a
  real `Z > 0`.  This is genuine and tautology-free: it is forced by *von Neumann reality* (a
  symmetric operator has real eigenvalues), composed with the change of variables `s ↦ -i(s-1/2)`
  that sends the critical line to the real axis.

`specHeight s = -i (s - 1/2)` is the spectral parameter; it is real **iff** `Re s = 1/2`, and then
`s = 1/2 + i·(specHeight s)`, with `Z = exp(specHeight s) > 0` giving `s = 1/2 + i·log Z`.

Main results.

* `specOp_kernel_admissible` — **the requested critical-line kernel law** for the self-adjoint
  resolvent operator built from *any* symmetric generator `A`:
  `(∃ ψ ≠ 0, specOp A s ψ = 0) → ∃ Z > 0, s = 1/2 + i·log Z`.
* `specOp_kernel_realized` — **non-vacuity**: the kernel really does occur, exactly at the critical-
  line points `s = 1/2 + i·log Z` whose height `log Z` is an eigenvalue of `A`.
* `logGen` / `Aχ` — a concrete **fixed self-adjoint generator** on `Hχ = ℕ →₀ ℂ`: the real-diagonal
  operator with eigen-heights `log(n+1)`, so its critical-line kernel points are `s = 1/2 + i·log(n+1)`
  (`Aχ_kernel_admissible`, `Aχ_kernel_realized`), matching the carrier-height law `Z = n+1`.
* `configured_det_eq_Lspec` — the **determinant readout**: the determinant of the configured
  L-readout operator `SpectralFiber.specOp χ s` is exactly `Lspec χ s`.
* `generator_readout_eq_Lspec` — the **partial-sum readout** generated by the spectral dynamics
  converges to `Lspec χ s` (restating `Lspec_eq_readout_limit`).

No `axiom`, no `sorry`.
-/

open Complex Filter Topology
open scoped BigOperators

namespace CriticalLinePhasor.SelfAdjointGenerator

open CriticalLinePhasor CriticalLinePhasor.UnconditionalFrobenius
open CriticalLinePhasor.SpectralFiber

/-! ## 1. The spectral parameter and the self-adjoint resolvent operator -/

/-- **The spectral height parameter** `specHeight s = -i (s - 1/2)`.  It is real exactly when
`Re s = 1/2`; on the critical line `s = 1/2 + i t` it returns the height `t`. -/
noncomputable def specHeight (s : ℂ) : ℂ := -Complex.I * (s - 1 / 2)

/-- **The configured self-adjoint resolvent operator** at parameter `s`, built from a fixed
generator `A`: `specOp A s = A − specHeight s • id`.  A kernel vector of `specOp A s` is exactly an
eigenvector of `A` with eigenvalue `specHeight s`. -/
noncomputable def specOp {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (s : ℂ) : E →ₗ[ℂ] E := A - specHeight s • LinearMap.id

theorem specOp_apply {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (s : ℂ) (ψ : E) :
    specOp A s ψ = A ψ - specHeight s • ψ := by
  simp [specOp]

/-- A nonzero kernel vector of `specOp A s` makes `specHeight s` an eigenvalue of `A`. -/
theorem hasEigenvalue_of_specOp_kernel {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (s : ℂ) {ψ : E} (hψ : ψ ≠ 0) (hker : specOp A s ψ = 0) :
    Module.End.HasEigenvalue A (specHeight s) := by
  apply Module.End.hasEigenvalue_of_hasEigenvector (x := ψ)
  refine ⟨Module.End.mem_eigenspace_iff.mpr ?_, hψ⟩
  have : A ψ - specHeight s • ψ = 0 := by rw [← specOp_apply]; exact hker
  linear_combination (norm := module) this

/-! ## 2. The critical-line kernel law (von Neumann reality) -/

/-- **Algebra of `specHeight`.**  If `specHeight s` is real (imaginary part `0`), then
`s = 1/2 + i·(specHeight s)`. -/
theorem eq_half_add_I_specHeight {s : ℂ} (h : (specHeight s).im = 0) :
    s = 1 / 2 + Complex.I * specHeight s := by
  have hμ : specHeight s = ((specHeight s).re : ℂ) := by
    apply Complex.ext <;> simp [h]
  have hdef : specHeight s = -Complex.I * (s - 1 / 2) := rfl
  have key : s - 1 / 2 = Complex.I * specHeight s := by
    rw [hdef]; ring_nf; simp only [Complex.I_sq]; ring
  linear_combination key

/--
**The critical-line kernel law (the requested `specOp_kernel_admissible`).**

For a **fixed self-adjoint generator** `A` on a (complex) inner-product space, the configured
resolvent operator `specOp A s` can have a nonzero kernel vector **only** when `s` lies on the
critical line, written `s = 1/2 + i·log Z` for some real `Z > 0`.

Proof: a kernel vector makes `specHeight s` an eigenvalue of the symmetric `A`, hence real (von
Neumann reality).  Real `specHeight s` forces `s = 1/2 + i·(specHeight s)`; taking
`Z = exp(specHeight s) > 0` gives `log Z = specHeight s`, i.e. `s = 1/2 + i·log Z`.

No assumption on the zeros of any L-function is used; this is the genuine self-adjoint side of the
Hilbert–Pólya picture, *not* the Riemann Hypothesis.
-/
theorem specOp_kernel_admissible {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (hA : A.IsSymmetric) (s : ℂ)
    (h : ∃ ψ : E, ψ ≠ 0 ∧ specOp A s ψ = 0) :
    ∃ Z : ℝ, 0 < Z ∧ s = 1 / 2 + Complex.I * (Real.log Z : ℂ) := by
  obtain ⟨ψ, hψ, hker⟩ := h
  have hev : Module.End.HasEigenvalue A (specHeight s) :=
    hasEigenvalue_of_specOp_kernel A s hψ hker
  have him : (specHeight s).im = 0 := symmetric_eigenvalue_real hA hev
  refine ⟨Real.exp (specHeight s).re, Real.exp_pos _, ?_⟩
  have hlog : (Real.log (Real.exp (specHeight s).re) : ℂ) = ((specHeight s).re : ℂ) := by
    rw [Real.log_exp]
  rw [hlog]
  have hμ : ((specHeight s).re : ℂ) = specHeight s := by
    apply Complex.ext <;> simp [him]
  rw [hμ]
  exact eq_half_add_I_specHeight him

/-- **Non-vacuity.**  Conversely, if `specHeight s` is an eigenvalue of `A` (with eigenvector `ψ`),
then `specOp A s` *does* have the nonzero kernel vector `ψ`, and `s` is the corresponding critical-
line point.  So the kernel law of `specOp_kernel_admissible` is not vacuous: the kernel is realised
exactly at the critical-line heights that are eigenvalues of `A`. -/
theorem specOp_kernel_realized {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (s : ℂ) {ψ : E} (heig : A ψ = specHeight s • ψ) :
    specOp A s ψ = 0 := by
  rw [specOp_apply, heig, sub_self]

/-! ## 3. A concrete fixed self-adjoint generator with eigen-heights `log(n+1)` -/

/-- **The carrier-height generator** `logGen n = log(n+1)`: the real eigen-heights of the fixed
self-adjoint generator `Aχ`, matching the carrier-height law `Z = n+1` (so `log Z = log(n+1)`). -/
noncomputable def logGen : ℕ → ℝ := fun n => Real.log (n + 1)

/-- **The fixed self-adjoint generator** `Aχ` on the state space `Hχ = ℕ →₀ ℂ`: the real-diagonal
operator with eigen-heights `logGen n = log(n+1)`. -/
noncomputable def Aχ : (ℕ →₀ ℂ) →ₗ[ℂ] (ℕ →₀ ℂ) := diagOp logGen

/-- `Aχ` is self-adjoint (symmetric) — it is real-diagonal. -/
theorem Aχ_isSymmetric : (Aχ).IsSymmetric := diagOp_symmetric logGen

/-- **The critical-line kernel law for the fixed generator `Aχ`.**  Any kernel vector of the
configured resolvent operator `specOp Aχ s` forces `s = 1/2 + i·log Z` for some real `Z > 0`. -/
theorem Aχ_kernel_admissible (s : ℂ) (h : ∃ ψ : (ℕ →₀ ℂ), ψ ≠ 0 ∧ specOp Aχ s ψ = 0) :
    ∃ Z : ℝ, 0 < Z ∧ s = 1 / 2 + Complex.I * (Real.log Z : ℂ) :=
  specOp_kernel_admissible Aχ Aχ_isSymmetric s h

/-- **The kernel is realised** at every carrier-height critical-line point `s = 1/2 + i·log(n+1)`:
the basis vector `single n 1` is a nonzero kernel vector of `specOp Aχ s` there.  Hence the
kernel law `Aχ_kernel_admissible` is non-vacuous and the realised heights are exactly `log(n+1)`,
`Z = n+1`. -/
theorem Aχ_kernel_realized (n : ℕ) :
    ∃ ψ : (ℕ →₀ ℂ), ψ ≠ 0 ∧
      specOp Aχ (1 / 2 + Complex.I * (Real.log (n + 1) : ℂ)) ψ = 0 := by
  refine ⟨Finsupp.single n (1 : ℂ), Finsupp.single_ne_zero.mpr one_ne_zero, ?_⟩
  set s : ℂ := 1 / 2 + Complex.I * (Real.log (n + 1) : ℂ) with hs
  have hheight : specHeight s = (logGen n : ℂ) := by
    simp only [specHeight, hs, logGen]
    ring_nf
    rw [Complex.I_sq]
    ring
  apply specOp_kernel_realized Aχ s (ψ := Finsupp.single n (1 : ℂ))
  rw [Aχ, diagOp_single, hheight, Finsupp.smul_single, smul_eq_mul, mul_one]

/-! ## 4. The determinant / readout of the configured object equals `Lspec χ s` -/

/-- **The determinant readout.**  The determinant of the configured L-readout operator
`SpectralFiber.specOp χ s = Lspec χ s • id` on the one-dimensional fiber `ℂ` is exactly the spectral
L-value `Lspec χ s`.  (This is the operator whose *kernel* tracks the zeros of `Lspec`; whether that
kernel forces the critical line is the Riemann Hypothesis and is not claimed.) -/
theorem configured_det_eq_Lspec {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (s : ℂ) :
    LinearMap.det (SpectralFiber.specOp χ s) = Lspec χ s := by
  rw [SpectralFiber.specOp]
  rw [LinearMap.det_smul, LinearMap.det_id]
  simp [Module.finrank_self]

/-- **The partial-sum readout** generated by the spectral dynamics of a non-principal `χ` converges,
on the whole half-plane `Re s > 0`, to the spectral L-value `Lspec χ s` (restating
`SpectralFiber.Lspec_eq_readout_limit`).  Together with `configured_det_eq_Lspec` this is the sense
in which the readout/determinant of the configured spectral object *equals* `Lspec χ s`. -/
theorem generator_readout_eq_Lspec {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (hχ : χ ≠ 1)
    {s : ℂ} (hs : 0 < s.re) :
    Filter.Tendsto
      (fun N : ℕ => ∑ n ∈ Finset.range N, SpectralFiber.readout (fun n => χ (n : ZMod q)) s n)
      Filter.atTop (nhds (Lspec χ s)) :=
  SpectralFiber.Lspec_eq_readout_limit χ hχ hs

/-! ## 5. The on-line realisation of a spectral zero -/

/--
**On-line realisation of a spectral zero.**  At a critical-line point `s = 1/2 + i·log Z` (real
`Z > 0`), the spectral L-value `Lspec χ s` vanishes **iff** the configured L-readout operator there
has a nonzero kernel vector.  So a spectral zero *that lies on the critical line* is realised as a
kernel event of the configured operator, exactly as in the requested
`Lspec χ s = 0 → ∃ Z>0, ker ≠ 0 ∧ s = 1/2 + i·log Z` — restricted to the line, where it is
unconditionally true.  (Forcing an *arbitrary* spectral zero onto the line is the Riemann Hypothesis
and is deliberately not asserted.) -/
theorem spectral_zero_on_line_iff_kernel {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (Z : ℝ) :
    Lspec χ (1 / 2 + Complex.I * (Real.log Z : ℂ)) = 0 ↔
      ∃ ψ : ℂ, ψ ≠ 0 ∧ SpectralFiber.specOp χ (1 / 2 + Complex.I * (Real.log Z : ℂ)) ψ = 0 :=
  (SpectralFiber.spectral_kernel_iff_zero χ _).symm

/-! ## 6. No off-line zeros: the spectral object cannot vanish off the critical line -/

section NoOfflineZeros

open CriticalLinePhasor.HarmonicCell Matrix
open scoped ComplexOrder

/-- If the spectral height `specHeight s` is real then `s` is on the critical line (`Re s = 1/2`). -/
theorem re_eq_half_of_specHeight_im_zero {s : ℂ} (h : (specHeight s).im = 0) :
    s.re = 1 / 2 := by
  have hs : s = 1 / 2 + Complex.I * specHeight s := eq_half_add_I_specHeight h
  have hμ : specHeight s = ((specHeight s).re : ℂ) := by
    apply Complex.ext <;> simp [h]
  rw [hs, hμ]
  simp

/--
**No off-line kernel (the spectral object cannot vanish off the critical line).**

For a **fixed self-adjoint generator** `A`, the configured resolvent operator `specOp A s` has
**only the trivial kernel** whenever `s` lies off the critical line (`Re s ≠ 1/2`): every vector it
annihilates is `0`.  Equivalently, the spectral object simply *cannot support* an off-line vanishing
(kernel) event.  This is unconditional — it is forced by von Neumann reality (`specOp_kernel_admissible`)
— and is the spectral analogue of "no off-line zeros".
-/
theorem specOp_no_offline_kernel {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (hA : A.IsSymmetric) {s : ℂ} (hoff : s.re ≠ 1 / 2)
    {ψ : E} (hker : specOp A s ψ = 0) : ψ = 0 := by
  by_contra hψ
  obtain ⟨Z, _, hZ⟩ := specOp_kernel_admissible A hA s ⟨ψ, hψ, hker⟩
  apply hoff
  rw [hZ]
  simp

/-- **The spectral resolvent operator is injective off the critical line.**  Off the critical line
(`Re s ≠ 1/2`) the self-adjoint resolvent operator `specOp A s` has trivial kernel, hence is
injective: the spectral object never vanishes off-line. -/
theorem specOp_injective_off_line {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (A : E →ₗ[ℂ] E) (hA : A.IsSymmetric) {s : ℂ} (hoff : s.re ≠ 1 / 2) :
    Function.Injective (specOp A s) := by
  rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
  intro ψ hψ
  exact specOp_no_offline_kernel A hA hoff (LinearMap.mem_ker.mp hψ)

/-! ### The spectral harmonic Gram pencil rejects off-line rank-drops -/

/-- **The spectral signed harmonic mode** for the one-dimensional self-adjoint fibre generator
`vonNeumannOp γ` (`γ` real): the resolvent determinant `γ − specHeight s`.  It is the spectral
analogue of the signed harmonic channel `HarmonicCell.Bchan`, but built from the *self-adjoint*
generator rather than the L-function. -/
noncomputable def specBchan (γ : ℝ) (s : ℂ) : ℂ := (γ : ℂ) - specHeight s

/-- The spectral signed mode is exactly the determinant of the one-dimensional resolvent operator
`specOp (vonNeumannOp γ) s`. -/
theorem specBchan_eq_det (γ : ℝ) (s : ℂ) :
    LinearMap.det (specOp (vonNeumannOp γ) s) = specBchan γ s := by
  have hop : specOp (vonNeumannOp γ) s = ((γ : ℂ) - specHeight s) • LinearMap.id := by
    rw [specOp, vonNeumannOp, ← sub_smul]
  rw [hop, LinearMap.det_smul, LinearMap.det_id, specBchan]
  simp [Module.finrank_self]

/-- The spectral signed mode vanishes iff the spectral height equals the (real) eigenvalue `γ`. -/
theorem specBchan_zero_iff (γ : ℝ) (s : ℂ) : specBchan γ s = 0 ↔ specHeight s = (γ : ℂ) := by
  rw [specBchan, sub_eq_zero, eq_comm]

/-- **The spectral signed mode cannot vanish off the critical line.**  Since `γ` is real, the only
`s` at which `γ − specHeight s = 0` have `specHeight s = γ` real, hence `Re s = 1/2`.  Off-line the
spectral signed mode is nonzero. -/
theorem specBchan_ne_zero_off_line (γ : ℝ) {s : ℂ} (hoff : s.re ≠ 1 / 2) :
    specBchan γ s ≠ 0 := by
  intro h
  rw [specBchan_zero_iff] at h
  exact hoff (re_eq_half_of_specHeight_im_zero (by rw [h]; simp))

/-- **The spectral harmonic pencil** `!![1, Bspec; μ, λ·Bspec]`: the diagonal harmonic pencil of
`HarmonicCell.harmonicPencil` with unsigned mode `1` (never zero) and signed mode the spectral
resolvent determinant `Bspec = γ − specHeight s`. -/
noncomputable def specHarmonicPencil (γ : ℝ) (s : ℂ) (μ lam : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  HarmonicCell.harmonicPencil 1 (specBchan γ s) μ lam

/-- **The spectral harmonic Gram matrix** `Gspec = (specHarmonicPencil)ᴴ · specHarmonicPencil`. -/
noncomputable def specGram (γ : ℝ) (s : ℂ) (μ lam : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (specHarmonicPencil γ s μ lam)ᴴ * (specHarmonicPencil γ s μ lam)

/-- The spectral harmonic Gram matrix is Hermitian positive semidefinite. -/
theorem specGram_posSemidef (γ : ℝ) (s : ℂ) (μ lam : ℂ) :
    (specGram γ s μ lam).PosSemidef :=
  HarmonicCell.gram_pos_semidefinite_cell (specHarmonicPencil γ s μ lam)

/-- The spectral harmonic Gram matrix rank-drops (`det = 0`) iff the spectral signed mode vanishes
(under the admissible diagonal calibration `λ ≠ μ`). -/
theorem specGram_det_zero_iff (γ : ℝ) (s : ℂ) {μ lam : ℂ} (hlam : lam ≠ μ) :
    (specGram γ s μ lam).det = 0 ↔ specBchan γ s = 0 := by
  rw [specGram, HarmonicCell.gram_rank_drop_iff_det_cell_zero, specHarmonicPencil,
    HarmonicCell.harmonicPencil_det, mul_eq_zero, mul_eq_zero]
  constructor
  · rintro ((h | h) | h)
    · exact absurd (sub_eq_zero.mp h) hlam
    · exact absurd h one_ne_zero
    · exact h
  · intro h; exact Or.inr h

/--
**The Gram harmonic pencil does not allow off-line zeros.**

For the spectral harmonic pencil built from the **self-adjoint** generator, off the critical line
(`Re s ≠ 1/2`) the Hermitian positive-semidefinite Gram matrix `Gspec` is of **full rank**
(`det Gspec ≠ 0`): it admits **no** rank-drop / vanishing event there.  Unconditionally — by von
Neumann reality — the spectral object's Gram pencil rejects every off-line zero.
-/
theorem specGram_no_offline_rank_drop (γ : ℝ) {s : ℂ} {μ lam : ℂ} (hlam : lam ≠ μ)
    (hoff : s.re ≠ 1 / 2) :
    (specGram γ s μ lam).det ≠ 0 := by
  intro h
  exact specBchan_ne_zero_off_line γ hoff ((specGram_det_zero_iff γ s hlam).mp h)

/-- **Non-vacuity (on the line the rank-drop is realised).**  At the on-line eigen-point
`s = 1/2 + i·γ` the spectral signed mode vanishes and the Gram pencil rank-drops, so the off-line
rejection of `specGram_no_offline_rank_drop` is not vacuous. -/
theorem specGram_rank_drop_on_line (γ : ℝ) {μ lam : ℂ} (hlam : lam ≠ μ) :
    (specGram γ (1 / 2 + Complex.I * (γ : ℂ)) μ lam).det = 0 := by
  rw [specGram_det_zero_iff γ _ hlam, specBchan_zero_iff]
  simp only [specHeight]
  ring_nf
  rw [Complex.I_sq]
  ring

end NoOfflineZeros

end CriticalLinePhasor.SelfAdjointGenerator
