import RequestProject.LefschetzRung

/-!
# The CM-product rung: the general channel bundle, instantiated where Hodge is a theorem

Phase two of the proof-attempt path.  The Lefschetz rung fixed three channels; the CM-product
rung needs the full character decomposition of `H^{2p}(E₁ × ⋯ × E_n)` under the CM/Galois
clock, whose frequency set varies with the product.  So the bundle is stated once,
bank-generically (`HodgeChannelData`): channels at arbitrary distinct integer frequencies,
faithful decomposition, rational DC readings, and a recognition field.  The rung theorems —
realization term, retention, recognition, executed source exhaustion, sharp DC retention —
are proved once for every such bundle.

The CM-product instantiation (`CMProductData`) is then the bundle whose recognition field is
the **theorem of record for products of elliptic curves**: every rational Hodge class on
`E₁ × ⋯ × E_n` is algebraic, generated by divisor classes (Imai; Kahn; via Faltings for the
Tate side) — the class of varieties on which the in-tree freeze detector
(`ChannelConstancy`) was certified.  DC is the frozen-channel condition: support on the
frequency-zero rails of the clock decomposition.  Register: as with Lefschetz, nothing new is
claimed about the classical theorem; what is new is the pipeline executing on the largest
family where the conjecture is known, with the same typed interface that above this rung has
to be *earned*.  No `sorry`, no `axiom`.
-/

open scoped BigOperators

namespace CriticalLinePhasor.HodgeLedgerFiltration

/-- **The general channel bundle**: rational cohomology presented through a faithful channel
decomposition at distinct integer frequencies, with rational DC readings and a recognition
field.  Each field is a classical statement at each instantiation (Hodge decomposition,
intersection theory, and the known case of the Hodge conjecture supplying `sourced`). -/
structure HodgeChannelData (H : Type*) [AddCommGroup H] {m : ℕ} (B : IntFrequencyBank m) where
  /-- The channel readings of the complexified class. -/
  channel : Fin m → H →+ ℂ
  /-- Faithfulness: a class silent on every channel is zero. -/
  channel_faithful : ∀ v : H, (∀ i, channel i v = 0) → v = 0
  /-- The frequency-zero (DC) readings are rational on DC classes. -/
  dc_rational : ∀ v : H, (∀ i, B.freq i ≠ 0 → channel i v = 0) →
    ∀ i, B.freq i = 0 → ∃ q : ℚ, channel i v = (q : ℂ)
  /-- The algebraic classes. -/
  Algebraic : H → Prop
  /-- The recognition field: a rational DC class is algebraic — the known case of the Hodge
  conjecture at each instantiation. -/
  sourced : ∀ v : H, (∀ i, B.freq i ≠ 0 → channel i v = 0) → Algebraic v

namespace HodgeChannelData

variable {H : Type*} [AddCommGroup H] {m : ℕ} {B : IntFrequencyBank m}
  (D : HodgeChannelData H B)

/-- The channel realization into the order-zero jet model. -/
noncomputable def toModelHom : H →+ GeneralExtensionData 0 m where
  toFun v := fun _ i => D.channel i v
  map_zero' := by
    funext l i
    simp
  map_add' a b := by
    funext l i
    simp [Pi.add_apply]

/-- The channel dial: DC = frozen (frequency-zero) support, `Rational = True` (the space is
the rational cohomology), readouts = the winding tower of the realization. -/
noncomputable def dial : HodgeDial H where
  DC v := ∀ i, B.freq i ≠ 0 → D.channel i v = 0
  Rational _ := True
  Algebraic := D.Algebraic
  T d v := generalExtensionTower B.toClockBank d (D.toModelHom v)

/-- **The realization term**, once for every channel bundle. -/
noncomputable def realization : FaithfulRealization D.dial 0 B where
  toModel := D.toModelHom
  regCompat _ _ := rfl
  dcCompat v hdc := fun _ i hi => hdc i hi
  ratCompat v hdc _ := by
    intro l i
    by_cases hf : B.freq i = 0
    · exact D.dc_rational v hdc i hf
    · exact ⟨0, by rw [Rat.cast_zero]; exact hdc i hf⟩
  noKernel v _ _ h :=
    D.channel_faithful v fun i => congrFun (congrFun h 0) i

/-- Retention, supplied by the bridge. -/
theorem retention : Retention D.dial :=
  D.realization.retention

/-- Recognition, consumed from the instantiation's theorem of record. -/
theorem recognition : Recognition D.dial :=
  fun v _ hdc _ => D.sourced v hdc

/-- **The executed terminus**: every nonzero rational DC class has an algebraic source. -/
theorem sourceExhaustion : SourceExhaustion D.dial :=
  D.realization.sourceExhaustion_of_recognition D.recognition

/-- **Sharp DC retention**: a nonzero rational DC class fires at some frequency-zero
channel. -/
theorem dc_fires_on_dc_rail (v : H) (hv : v ≠ 0)
    (hdc : ∀ i, B.freq i ≠ 0 → D.channel i v = 0) :
    ∃ i, B.freq i = 0 ∧ D.channel i v ≠ 0 := by
  by_contra hnone
  push Not at hnone
  refine hv (D.channel_faithful v fun i => ?_)
  by_cases hf : B.freq i = 0
  · exact hnone i hf
  · exact hdc i hf

end HodgeChannelData

/-- **The CM-product rung**: the channel bundle of `H^{2p}(E₁ × ⋯ × E_n)` under its CM/Galois
clock decomposition, whose `sourced` field is the theorem of record — every rational Hodge
class on a product of elliptic curves is algebraic, generated by divisor classes (Imai; Kahn;
Faltings on the Tate side).  DC is the frozen-channel condition of the in-tree constancy
mechanism; the executed terminus below is the Hodge conjecture on this family, run through
the carrier pipeline. -/
abbrev CMProductData (H : Type*) [AddCommGroup H] {m : ℕ} (B : IntFrequencyBank m) :=
  HodgeChannelData H B

/-- The Hodge conjecture for the CM-product instantiation, executed end to end through the
pipeline: nonzero rational frozen classes have algebraic sources. -/
theorem cmProduct_sourceExhaustion {H : Type*} [AddCommGroup H] {m : ℕ}
    {B : IntFrequencyBank m} (D : CMProductData H B) :
    SourceExhaustion D.dial :=
  D.sourceExhaustion

end CriticalLinePhasor.HodgeLedgerFiltration

#print axioms CriticalLinePhasor.HodgeLedgerFiltration.HodgeChannelData.realization
#print axioms CriticalLinePhasor.HodgeLedgerFiltration.HodgeChannelData.sourceExhaustion
#print axioms CriticalLinePhasor.HodgeLedgerFiltration.HodgeChannelData.dc_fires_on_dc_rail
#print axioms CriticalLinePhasor.HodgeLedgerFiltration.cmProduct_sourceExhaustion
