import RequestProject.ThreeDConverse

/-!
# The rank-n CPS carrier quotient

The diagonal completion clocks and transvection windings generate the rank-n carrier move group.
Quotienting a three-dimensional state space by those moves therefore identifies every full
`GL(n)` translate.  This is the generator descent in quotient form, before taking any scalar
readout.
-/

namespace CriticalLinePhasor.ThreeDConverse

/-- The subgroup generated by the diagonal-clock and transvection-winding carrier moves. -/
noncomputable abbrev cpsCarrierMoveGroup
    (n K : Type*) [Fintype n] [DecidableEq n] [Field K] :
    Subgroup (Matrix.GeneralLinearGroup n K) :=
  Subgroup.closure (glCarrierGenerators n K)

/-- Three-dimensional carrier states modulo the native CPS generator moves. -/
noncomputable abbrev CPSCarrierCoinvariant
    (n K X : Type*) [Fintype n] [DecidableEq n] [Field K]
    [MulAction (Matrix.GeneralLinearGroup n K) X] : Type _ :=
  MulAction.orbitRel.Quotient (cpsCarrierMoveGroup n K) X

/-- Every full rank-n linear move is already a carrier-generator move. -/
theorem generalLinear_mem_cpsCarrierMoveGroup
    {n K : Type*} [Fintype n] [DecidableEq n] [Field K]
    (g : Matrix.GeneralLinearGroup n K) : g ∈ cpsCarrierMoveGroup n K := by
  change g ∈ Subgroup.closure (glCarrierGenerators n K)
  rw [glCarrierGenerators_closure]
  exact Subgroup.mem_top g

/-- The quotient class of a 3D state is fixed by every `GL(n)` translate. -/
theorem cpsCarrierCoinvariant_mk_smul_eq
    {n K X : Type*} [Fintype n] [DecidableEq n] [Field K]
    [MulAction (Matrix.GeneralLinearGroup n K) X]
    (g : Matrix.GeneralLinearGroup n K) (x : X) :
    (Quotient.mk'' (g • x) : CPSCarrierCoinvariant n K X) = Quotient.mk'' x := by
  apply Quotient.sound
  change g • x ∈ MulAction.orbit (cpsCarrierMoveGroup n K) x
  rw [MulAction.mem_orbit_iff]
  exact ⟨⟨g, generalLinear_mem_cpsCarrierMoveGroup g⟩, rfl⟩

/-- All translates of a 3D state have one CPS carrier-coinvariant class. -/
theorem cpsCarrierCoinvariant_orbit_constant
    {n K X : Type*} [Fintype n] [DecidableEq n] [Field K]
    [MulAction (Matrix.GeneralLinearGroup n K) X]
    (x : X) :
    ∀ g : Matrix.GeneralLinearGroup n K,
      (Quotient.mk'' (g • x) : CPSCarrierCoinvariant n K X) = Quotient.mk'' x :=
  fun g => cpsCarrierCoinvariant_mk_smul_eq g x

end CriticalLinePhasor.ThreeDConverse

#print axioms CriticalLinePhasor.ThreeDConverse.generalLinear_mem_cpsCarrierMoveGroup
#print axioms CriticalLinePhasor.ThreeDConverse.cpsCarrierCoinvariant_mk_smul_eq
#print axioms CriticalLinePhasor.ThreeDConverse.cpsCarrierCoinvariant_orbit_constant
