import RequestProject.FdTiling

/-!
# The Eisenstein height is a class function on `Γ_∞`-cosets

First step of the Eisenstein--Epstein identity, which is item (1) of the three-piece continuation
the `r = 2` rung still needs.

The coset sum `∑_{q : CosetQ} Im(γ_q·z)^s` is written through `rep`, a choice of representative
by `Quotient.out`.  For it to be the classical Eisenstein series — a sum over bottom rows `(c,d)` —
the height has to be independent of that choice.  It is, for the reason the cosets were formed:
`Γ_∞` is generated by `T`, which acts by horizontal translation and so does not move `Im` at all
(`im_T_zpow_smul`), and the sign ambiguity is invisible because `SL(2,ℤ)` acts through `PSL`
(`SL_neg_smul`).

Harmonically this is the statement that the height is pure DC along the `Γ_∞` direction: the whole
`T`-orbit sits at one height, which is why the orbit can be summed out and only the bottom row
survives.  Combined with Mathlib's `im_smul_eq_div_normSq`, the coset sum is
`∑ y^s/‖cz+d‖^{2s}` over coprime `(c,d)` — and dividing by `ζ(2s)` extends it to all `(c,d) ≠ 0`,
which is the Epstein lattice sum of `generalFEPair`.

**Scope.**  This file now supplies all of item (1) at the level of general lemmas: the coset ↔
coprime-pair correspondence in both directions, the modulus/direction split of nonzero lattice
pairs as an `Equiv`, and the `ζ`-factor `tsum` identity for any homogeneous summand.  What is *not*
here is the instantiation at the Eisenstein summand `y^s/‖cz+d‖^{2s}` — that needs the summability
inputs and the identification of the resulting lattice sum with `generalFEPair`'s `Λ`.
-/

open ModularGroup UpperHalfPlane
open scoped MatrixGroups

namespace CriticalLinePhasor.Unfolding

/-- **The Eisenstein height does not depend on the coset representative.**  `Γ_∞` translates
horizontally, and the sign acts trivially. -/
lemma im_rep_smul_eq (γ : SL(2, ℤ)) (z : ℍ) :
    ((rep (Quotient.mk cosetSetoid γ)) • z).im = (γ • z).im := by
  obtain ⟨n, h | h⟩ := rep_spec γ
  · conv_rhs => rw [h]
    rw [mul_smul, ModularGroup.im_T_zpow_smul]
  · conv_rhs => rw [h]
    rw [SL_neg_smul, mul_smul, ModularGroup.im_T_zpow_smul]

/-- The height is `Γ_∞`-invariant on the nose, in the form the coset sum consumes. -/
lemma im_T_zpow_mul_smul (n : ℤ) (γ : SL(2, ℤ)) (z : ℍ) :
    ((ModularGroup.T ^ n * γ) • z).im = (γ • z).im := by
  rw [mul_smul, ModularGroup.im_T_zpow_smul]

/-! ## The bottom row is the coset invariant -/

/-- **`Γ_∞` does not move the bottom row.**  `T^n` has bottom row `(0,1)`, so left multiplication
by it leaves the bottom row of `γ` untouched — exactly, not just up to sign.  This is the algebraic
shadow of `im_rep_smul_eq`: the height depends only on the bottom row, and the bottom row is the
coset invariant. -/
lemma bottomRow_T_zpow_mul (n : ℤ) (γ : SL(2, ℤ)) (j : Fin 2) :
    (ModularGroup.T ^ n * γ) 1 j = γ 1 j := by
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply,
    ModularGroup.coe_T_zpow]
  simp [Fin.sum_univ_two]

/-- **The bottom row of a modular matrix is a coprime pair.**  Immediate from `det = 1`: the top
row supplies the Bézout witnesses. -/
lemma isCoprime_bottomRow (γ : SL(2, ℤ)) : IsCoprime (γ 1 0) (γ 1 1) := by
  have hdet : γ 0 0 * γ 1 1 - γ 0 1 * γ 1 0 = 1 := by
    have h := γ.2
    rw [Matrix.det_fin_two] at h
    exact h
  exact ⟨-γ 0 1, γ 0 0, by linarith⟩

/-- **Every coprime pair is a bottom row.**  Bézout supplies the top row directly, so the image of
`γ ↦ (γ 1 0, γ 1 1)` is exactly the coprime pairs. -/
lemma exists_bottomRow_of_isCoprime {c d : ℤ} (h : IsCoprime c d) :
    ∃ γ : SL(2, ℤ), γ 1 0 = c ∧ γ 1 1 = d := by
  obtain ⟨u, v, huv⟩ := h
  refine ⟨⟨!![v, -u; c, d], ?_⟩, ?_, ?_⟩
  · rw [Matrix.det_fin_two_of]; linarith
  · simp
  · simp

/-- **The bottom-row map characterizes the coprime pairs exactly.**  Together with
`bottomRow_T_zpow_mul` (the row is a `Γ_∞`-invariant) and `im_rep_smul_eq` (the height factors
through it), this is the index set of the classical Eisenstein series. -/
theorem bottomRow_range_eq_isCoprime (c d : ℤ) :
    (∃ γ : SL(2, ℤ), γ 1 0 = c ∧ γ 1 1 = d) ↔ IsCoprime c d := by
  constructor
  · rintro ⟨γ, rfl, rfl⟩
    exact isCoprime_bottomRow γ
  · exact exists_bottomRow_of_isCoprime

/-- **Same bottom row means same `Γ_∞`-coset.**  The converse of `bottomRow_T_zpow_mul`: the
bottom row does not merely happen to be invariant, it *determines* the coset.  The shift is read
off by Bézout — `n = u(a'-a) + v(b'-b)` for any `(u,v)` with `uc + vd = 1` — which is available
precisely because the row is coprime. -/
lemma exists_T_zpow_of_same_bottomRow (γ δ : SL(2, ℤ))
    (h0 : δ 1 0 = γ 1 0) (h1 : δ 1 1 = γ 1 1) :
    ∃ n : ℤ, δ = ModularGroup.T ^ n * γ := by
  obtain ⟨u, v, huv⟩ := isCoprime_bottomRow γ
  have hdetγ : γ 0 0 * γ 1 1 - γ 0 1 * γ 1 0 = 1 := by
    have h := γ.2; rw [Matrix.det_fin_two] at h; exact h
  have hdetδ : δ 0 0 * γ 1 1 - δ 0 1 * γ 1 0 = 1 := by
    have h := δ.2; rw [Matrix.det_fin_two, h0, h1] at h; exact h
  have hkey : (δ 0 0 - γ 0 0) * γ 1 1 = (δ 0 1 - γ 0 1) * γ 1 0 := by
    linear_combination hdetδ - hdetγ
  set n : ℤ := u * (δ 0 0 - γ 0 0) + v * (δ 0 1 - γ 0 1) with hn
  have hnc : n * γ 1 0 = δ 0 0 - γ 0 0 := by
    have expand : n * γ 1 0 =
        u * (δ 0 0 - γ 0 0) * γ 1 0 + v * ((δ 0 1 - γ 0 1) * γ 1 0) := by
      rw [hn]; ring
    rw [expand, ← hkey]
    linear_combination (δ 0 0 - γ 0 0) * huv
  have hnd : n * γ 1 1 = δ 0 1 - γ 0 1 := by
    have expand : n * γ 1 1 =
        u * ((δ 0 0 - γ 0 0) * γ 1 1) + v * (δ 0 1 - γ 0 1) * γ 1 1 := by
      rw [hn]; ring
    rw [expand, hkey]
    linear_combination (δ 0 1 - γ 0 1) * huv
  refine ⟨n, Subtype.ext (Matrix.ext fun i j => ?_)⟩
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, ModularGroup.coe_T_zpow]
  fin_cases i <;> fin_cases j <;>
    simp [Fin.sum_univ_two, h0, h1] <;> linarith [hnc, hnd]

/-- **The coset is exactly the bottom row, up to `Γ_∞`.**  Both directions together: the height in
the Eisenstein sum depends only on a coprime pair, and distinct cosets give distinct pairs. -/
theorem sameCoset_iff_same_bottomRow (γ δ : SL(2, ℤ)) :
    (∃ n : ℤ, δ = ModularGroup.T ^ n * γ) ↔ (δ 1 0 = γ 1 0 ∧ δ 1 1 = γ 1 1) := by
  constructor
  · rintro ⟨n, rfl⟩
    exact ⟨bottomRow_T_zpow_mul n γ 0, bottomRow_T_zpow_mul n γ 1⟩
  · rintro ⟨h0, h1⟩
    exact exists_T_zpow_of_same_bottomRow γ δ h0 h1

/-- Negation negates the bottom row. -/
lemma bottomRow_neg (γ : SL(2, ℤ)) (j : Fin 2) : (-γ) 1 j = -(γ 1 j) := rfl

/-- **The coset relation is exactly "same bottom row up to sign".**  `cosetSetoid` quotients by
`±⟨T⟩`, so the invariant is the bottom row modulo negation — and `CosetQ` is therefore the index
set of the classical Eisenstein series: coprime pairs `(c,d)` taken up to sign. -/
theorem cosetSetoid_iff_bottomRow_eq_or_neg (γ δ : SL(2, ℤ)) :
    cosetSetoid.r γ δ ↔
      ((δ 1 0 = γ 1 0 ∧ δ 1 1 = γ 1 1) ∨ (δ 1 0 = -γ 1 0 ∧ δ 1 1 = -γ 1 1)) := by
  constructor
  · rintro ⟨n, h | h⟩
    · exact Or.inl ⟨by rw [h, bottomRow_T_zpow_mul], by rw [h, bottomRow_T_zpow_mul]⟩
    · exact Or.inr ⟨by rw [h, bottomRow_neg, bottomRow_T_zpow_mul],
        by rw [h, bottomRow_neg, bottomRow_T_zpow_mul]⟩
  · rintro (⟨h0, h1⟩ | ⟨h0, h1⟩)
    · obtain ⟨n, hn⟩ := exists_T_zpow_of_same_bottomRow γ δ h0 h1
      exact ⟨n, Or.inl hn⟩
    · have h0' : (-δ) 1 0 = γ 1 0 := by simp [h0]
      have h1' : (-δ) 1 1 = γ 1 1 := by simp [h1]
      obtain ⟨n, hn⟩ := exists_T_zpow_of_same_bottomRow γ (-δ) h0' h1'
      exact ⟨n, Or.inr (by rw [← hn, neg_neg])⟩

/-! ## The `ζ(2s)` factor: every nonzero pair is a scaled coprime pair -/

/-- **Every nonzero integer pair factors as a positive scalar times a coprime pair**, and the
scalar is the gcd.  This is the combinatorial content of the `ζ(2s)` factor: summing a
`(-2s)`-homogeneous function over all nonzero pairs is `∑_{k≥1} k^{-2s}` times the sum over coprime
pairs, i.e. `ζ(2s)` times the Eisenstein sum. -/
lemma exists_coprime_factorization {m n : ℤ} (h : ¬(m = 0 ∧ n = 0)) :
    ∃ k c d : ℤ, 0 < k ∧ IsCoprime c d ∧ m = k * c ∧ n = k * d := by
  have hg : Int.gcd m n ≠ 0 := by
    rw [Ne, Int.gcd_eq_zero_iff]
    exact h
  have hgpos : 0 < Int.gcd m n := Nat.pos_of_ne_zero hg
  refine ⟨(Int.gcd m n : ℤ), m / (Int.gcd m n : ℤ), n / (Int.gcd m n : ℤ),
    by exact_mod_cast hgpos, ?_, ?_, ?_⟩
  · rw [Int.isCoprime_iff_gcd_eq_one]
    exact Int.gcd_div_gcd_div_gcd hgpos
  · exact (Int.mul_ediv_cancel' (Int.gcd_dvd_left m n)).symm
  · exact (Int.mul_ediv_cancel' (Int.gcd_dvd_right m n)).symm

/-- The scalar in that factorization is determined: it is the gcd, up to sign. -/
lemma gcd_eq_of_coprime_factorization {m n k c d : ℤ} (hk : 0 < k)
    (hcd : IsCoprime c d) (hm : m = k * c) (hn : n = k * d) :
    (Int.gcd m n : ℤ) = k := by
  subst hm; subst hn
  rw [Int.gcd_mul_left]
  rw [Int.isCoprime_iff_gcd_eq_one] at hcd
  rw [hcd, mul_one, Int.natAbs_of_nonneg hk.le]

/-- **The gcd split as an equivalence.**  Nonzero lattice pairs are exactly (positive scalar) ×
(primitive direction).  This is the reindexing the `ζ(2s)` factor sums along: the modulus carries
`∑_{k≥1}k^{-2s} = ζ(2s)`, the direction carries the Eisenstein sum. -/
noncomputable def gcdSplitEquiv :
    {p : ℤ × ℤ // ¬(p.1 = 0 ∧ p.2 = 0)} ≃
      {k : ℤ // 0 < k} × {q : ℤ × ℤ // IsCoprime q.1 q.2} where
  toFun p :=
    (⟨(Int.gcd p.1.1 p.1.2 : ℤ), by
        have h : Int.gcd p.1.1 p.1.2 ≠ 0 := by rw [Ne, Int.gcd_eq_zero_iff]; exact p.2
        exact_mod_cast Nat.pos_of_ne_zero h⟩,
     ⟨(p.1.1 / (Int.gcd p.1.1 p.1.2 : ℤ), p.1.2 / (Int.gcd p.1.1 p.1.2 : ℤ)), by
        rw [Int.isCoprime_iff_gcd_eq_one]
        refine Int.gcd_div_gcd_div_gcd ?_
        have h : Int.gcd p.1.1 p.1.2 ≠ 0 := by rw [Ne, Int.gcd_eq_zero_iff]; exact p.2
        exact Nat.pos_of_ne_zero h⟩)
  invFun kq :=
    ⟨(kq.1.1 * kq.2.1.1, kq.1.1 * kq.2.1.2), by
      rintro ⟨e1, e2⟩
      have hk : kq.1.1 ≠ 0 := kq.1.2.ne'
      have h1 : kq.2.1.1 = 0 := by
        rcases mul_eq_zero.mp e1 with h | h
        · exact absurd h hk
        · exact h
      have h2 : kq.2.1.2 = 0 := by
        rcases mul_eq_zero.mp e2 with h | h
        · exact absurd h hk
        · exact h
      have hc := kq.2.2
      rw [h1, h2] at hc
      exact not_isCoprime_zero_zero hc⟩
  left_inv p := by
    apply Subtype.ext
    apply Prod.ext <;>
      simp only [] <;>
      exact Int.mul_ediv_cancel' (by first | exact Int.gcd_dvd_left _ _ | exact Int.gcd_dvd_right _ _)
  right_inv kq := by
    obtain ⟨⟨k, hk⟩, ⟨⟨c, d⟩, hcd⟩⟩ := kq
    have hgcd : (Int.gcd (k * c) (k * d) : ℤ) = k :=
      gcd_eq_of_coprime_factorization hk hcd rfl rfl
    apply Prod.ext
    · exact Subtype.ext hgcd
    · apply Subtype.ext
      apply Prod.ext <;> simp only [hgcd] <;>
        exact Int.mul_ediv_cancel_left _ hk.ne'

/-- **The `ζ` factor, as a `tsum` identity.**  For any function on lattice pairs that is
homogeneous of degree `-w` under positive scaling, the sum over *all* nonzero pairs factors as
`(∑_{k>0} k^{-w}) · (sum over primitive pairs)`.

This is the analytic half of the `ζ(2s)` factor: nothing about the Eisenstein series is used, only
homogeneity and the modulus/direction split.  Applied with `w = 2s` and
`f (c,d) = y^s/‖cz+d‖^{2s}`, the left side is the Epstein lattice sum of `generalFEPair` and the
right side is `ζ(2s)` times the Eisenstein sum. -/
theorem tsum_nonzero_eq_zeta_factor {f : ℤ × ℤ → ℂ} {w : ℂ}
    (hhom : ∀ k c d : ℤ, 0 < k → f (k * c, k * d) = (k : ℂ) ^ (-w) * f (c, d))
    (hk : Summable fun k : {k : ℤ // 0 < k} => ‖(k.1 : ℂ) ^ (-w)‖)
    (hq : Summable fun q : {q : ℤ × ℤ // IsCoprime q.1 q.2} => ‖f q.1‖) :
    ∑' p : {p : ℤ × ℤ // ¬(p.1 = 0 ∧ p.2 = 0)}, f p.1 =
      (∑' k : {k : ℤ // 0 < k}, (k.1 : ℂ) ^ (-w)) *
        (∑' q : {q : ℤ × ℤ // IsCoprime q.1 q.2}, f q.1) := by
  rw [tsum_mul_tsum_of_summable_norm hk hq,
    ← gcdSplitEquiv.symm.tsum_eq (fun p : {p : ℤ × ℤ // ¬(p.1 = 0 ∧ p.2 = 0)} => f p.1)]
  refine tsum_congr fun kq => ?_
  obtain ⟨⟨k, hk0⟩, ⟨⟨c, d⟩, hcd⟩⟩ := kq
  exact hhom k c d hk0

/-- The positive integers, indexed by `ℕ`. -/
def posIntEquiv : ℕ ≃ {k : ℤ // 0 < k} where
  toFun n := ⟨(n : ℤ) + 1, by positivity⟩
  invFun k := (k.1 - 1).toNat
  left_inv n := by simp
  right_inv k := by
    apply Subtype.ext
    have hk : (0:ℤ) < k.1 := k.2
    simp only
    omega

/-- **The modulus side is summable on `Re w > 1`** — the `ζ(w)` factor converges.  This is one of
the two summability inputs of `tsum_nonzero_eq_zeta_factor`; at `w = 2s` it is `Re s > 1/2`, weaker
than the Eisenstein side needs, so it never binds. -/
lemma summable_pos_int_cpow {w : ℂ} (hw : 1 < w.re) :
    Summable fun k : {k : ℤ // 0 < k} => ‖(k.1 : ℂ) ^ (-w)‖ := by
  rw [← posIntEquiv.summable_iff]
  have hval : ∀ n : ℕ,
      (fun k : {k : ℤ // 0 < k} => ‖(k.1 : ℂ) ^ (-w)‖) (posIntEquiv n) =
        ((n : ℝ) + 1) ^ (-w.re) := by
    intro n
    have hpos : (0:ℝ) < (n : ℝ) + 1 := by positivity
    show ‖((((n : ℤ) + 1 : ℤ) : ℂ)) ^ (-w)‖ = _
    rw [show ((((n : ℤ) + 1 : ℤ) : ℂ)) = (((n : ℝ) + 1 : ℝ) : ℂ) by push_cast; ring,
      Complex.norm_cpow_eq_rpow_re_of_pos hpos]
    congr 1
  rw [Function.comp_def]
  simp_rw [hval]
  have hshift : Summable fun n : ℕ => ((n : ℝ) + 1) ^ (-w.re) := by
    have hbase : Summable fun n : ℕ => (n : ℝ) ^ (-w.re) :=
      Real.summable_nat_rpow.mpr (by linarith)
    have := (summable_nat_add_iff (f := fun n : ℕ => (n : ℝ) ^ (-w.re)) 1).mpr hbase
    refine this.congr fun n => ?_
    congr 1
    push_cast
    ring
  exact hshift

end CriticalLinePhasor.Unfolding

#print axioms CriticalLinePhasor.Unfolding.summable_pos_int_cpow
#print axioms CriticalLinePhasor.Unfolding.tsum_nonzero_eq_zeta_factor
#print axioms CriticalLinePhasor.Unfolding.gcdSplitEquiv
#print axioms CriticalLinePhasor.Unfolding.exists_coprime_factorization
#print axioms CriticalLinePhasor.Unfolding.gcd_eq_of_coprime_factorization
#print axioms CriticalLinePhasor.Unfolding.cosetSetoid_iff_bottomRow_eq_or_neg
#print axioms CriticalLinePhasor.Unfolding.exists_T_zpow_of_same_bottomRow
#print axioms CriticalLinePhasor.Unfolding.sameCoset_iff_same_bottomRow
#print axioms CriticalLinePhasor.Unfolding.bottomRow_range_eq_isCoprime
#print axioms CriticalLinePhasor.Unfolding.im_rep_smul_eq
#print axioms CriticalLinePhasor.Unfolding.im_T_zpow_mul_smul
#print axioms CriticalLinePhasor.Unfolding.bottomRow_T_zpow_mul
#print axioms CriticalLinePhasor.Unfolding.isCoprime_bottomRow
