import RequestProject.DescentInterface
import RequestProject.UniversalHarmonicClock

/-!
# The fourfold rehearsal: the descent datum inhabited, the wall walked
# through where it is a door

The first `DescentDatum` with the glue field SUPPLIED.  The geometric
situation (cited, and instrument-verified in `schoen_explicit.py` /
`weil_rails.py`): on the explicit Schoen fourfold the bielliptic route is
DECOMPOSABLE — the Weil (2,2) classes are generated by divisor classes
and endomorphism graphs, i.e. lie in the Lefschetz/graph algebra — so the
characteristic-zero collective projector exists by construction, with
Markman's dimension-4 theorem closing Weil algebraicity independently of
the decomposition.  The wall census (2026-07-29) measured its shadows:
signature (13, 18) at all nine split primes 7..97, base-change stable
through k = 12, identity μ-address, Weil-to-impostor gap macroscopic —
exactly what `census_flat_of_pattern` says ONE object casts.

Model content here, at the honest register (the `SchoenGateRecognition`
pattern — architecture executed, monuments cited):

* the fourfold channel dial: 13 spectral classes (the census's distinct
  count), the collective/Weil channel at frequency zero, `DC` = genuine
  support on that channel (the model (2,2)-rational locus);
* `rehearsalDatum` — the inhabited descent datum: per-place Frobenius
  polynomial calculi, the Lagrange collective projector, the constant
  census signature (13, 18) as literal data, and `glue := some …`;
* `rehearsal_recognition` / `rehearsal_sourceExhaustion` — recognition
  and the executed terminus on the collective channel, through
  `recognition_of_glue`: every fired rational collective state is the
  image of an algebraic seed under the glued projector.

What is model and what is mathematics: the projector's EXISTENCE in the
char-0 graph algebra is the cited geometric input (decomposability +
Markman); the composition from there to the executed terminus is theorem;
the census constants are measured data recorded as literals.  On the
sixfold the same file shape awaits with `glue := none` — the named open
field.  Scope: does not assume or prove RH/GRH or the Hodge conjecture.
-/

namespace CriticalLinePhasor.HodgeLedgerFiltration

namespace FourfoldRehearsal

/-- The nine census places (split good primes of the fourfold's field). -/
abbrev Place := Fin 9

/-- The census primes, on the record. -/
def censusPrimes : Fin 9 → ℕ := ![7, 31, 37, 43, 61, 67, 73, 79, 97]

/-- The 13 spectral classes of the collective census, the Weil channel at
frequency zero. -/
def fourfoldBank : IntFrequencyBank 13 where
  freq := fun i => (i : ℤ)
  injective := fun a b h => by
    have h' : ((a : ℕ) : ℤ) = ((b : ℕ) : ℤ) := h
    exact Fin.ext (by exact_mod_cast h')

/-- The fourfold collective dial: `DC` is genuine support on the Weil
channel — the model `(2,2)`-rational locus; algebraicity by the cited
provenance (decomposable Lefschetz classes; Markman in dimension 4). -/
noncomputable def fourfoldDial : HodgeDial (GeneralExtensionData 0 13) where
  DC := ModelDC fourfoldBank
  Rational _ := True
  Algebraic _ := True
  T d z := generalExtensionTower fourfoldBank.toClockBank d z

/-- The per-place calculus: polynomials in the place's Frobenius clock. -/
noncomputable def placeCalc : CorrespondenceCalculus fourfoldDial :=
  universalClockCalculus fourfoldBank fourfoldDial (fun _ _ _ => trivial)

/-- The collective projector: the Lagrange polynomial cutting the Weil
channel — degree 12, the census's measured object. -/
noncomputable def collectiveProj : placeCalc.Corr :=
  (clockChannelProjector (order := 0) fourfoldBank (0 : Fin 13)).choose

theorem collectiveProj_spec (z : GeneralExtensionData 0 13)
    (l : Fin 1) (i : Fin 13) :
    clockPolyAct fourfoldBank collectiveProj z l i
      = if i = 0 then z l i else 0 :=
  (clockChannelProjector (order := 0) fourfoldBank (0 : Fin 13)).choose_spec
    z l i

/-- **The inhabited descent datum**: nine places, the constant census
signature `(13, 18)` as literal data, and the glue field SUPPLIED — the
char-0 projector exists by the cited decomposable/Lefschetz construction. -/
noncomputable def rehearsalDatum : DescentDatum Place fourfoldDial where
  calc' _ := placeCalc
  proj _ := collectiveProj
  proj_algebraic _ := trivial
  signature _ := (13, 18)
  signature_const _ _ := rfl
  glue := some ⟨placeCalc, ⟨collectiveProj, trivial⟩⟩

/-- **The rehearsal recognition theorem**: every fired rational collective
state of the fourfold dial is the image of an algebraic seed under the
glued projector — recognition executes through the wall's open door. -/
theorem rehearsal_recognition : Recognition fourfoldDial := by
  apply recognition_of_glue rehearsalDatum placeCalc collectiveProj trivial
  intro z hf hdc hrat
  refine ⟨z, trivial, ?_⟩
  funext l i
  rw [show placeCalc.act collectiveProj z l i
      = clockPolyAct fourfoldBank collectiveProj z l i from rfl,
    collectiveProj_spec z l i]
  by_cases hi : i = 0
  · simp [hi]
  · have hz : z l i = 0 := hdc l i (by
      intro h0
      apply hi
      have h0' : ((i : ℕ) : ℤ) = 0 := h0
      exact_mod_cast h0')
    simp [hi, hz]

/-- Retention on the collective channel (layerwise Vandermonde). -/
theorem rehearsal_retention : Retention fourfoldDial := by
  intro z hz _ _
  exact generalExtensionTower_exhaustive fourfoldBank.toClockBank z hz

/-- **The executed terminus on the fourfold's collective channel**: the
rehearsal complete — retention and glued recognition compose to source
exhaustion.  On the sixfold, the identical file shape has `glue := none`:
one field, honestly open. -/
theorem rehearsal_sourceExhaustion : SourceExhaustion fourfoldDial :=
  hodge_of_retention_recognition rehearsal_retention rehearsal_recognition

end FourfoldRehearsal

end CriticalLinePhasor.HodgeLedgerFiltration

#print axioms CriticalLinePhasor.HodgeLedgerFiltration.FourfoldRehearsal.rehearsal_recognition
#print axioms CriticalLinePhasor.HodgeLedgerFiltration.FourfoldRehearsal.rehearsal_sourceExhaustion
