import RequestProject.Faithfulness

/-!
# The compact local spectral mechanism: Frobenius similitude, det‑one chiral block, orthogonality

This file deepens the spectral / Frobenius layer of the model into a single **compact local
spectral mechanism**, assembled from four unconditional ingredients.  Everything here is new; the
existing files are untouched and stay `sorry`‑free.

1. **Frobenius similitude (self‑similarity).**  Prime/integer multiplication `n ↦ m·n` acts on the
   carrier point `helixPt θ n = √n · wind θ n` by a *similitude*: a radial area‑law scaling `√m`
   times the unit‑modulus winding rotation `wind θ m`,
   `helixPt θ (m·n) = (√m · wind θ m) · helixPt θ n` (`helixPt_mul`, `helixPt_eq_similitude`).
   The multiplier has modulus exactly `√m` (`norm_frobeniusMultiplier`) — the rotation is
   unimodular (`Circle.norm_coe`) — so the map scales every length by `√m`
   (`norm_frobeniusSimilitude`).  These similitudes compose multiplicatively
   (`frobeniusSimilitude_mul`): the carrier is **self‑similar** under the whole multiplicative
   monoid generated by the primes (the Frobenius maps).

2. **Conjugate chirality, determinant‑one *unitary* transverse block.**  The two chiralities carry
   the reciprocal phases `z = spin y n` and `z̄`; the transverse block `diag(z, z̄)` is **unitary**
   (`frobeniusBlock_unitary`) with `det = z·z̄ = |z|² = 1` (`frobeniusBlock_det_one`).  This is the
   orientation/volume‑preserving chiral invariant of the transverse phase dynamics — *not* a deep
   statement about the zeros.

3. **Real eigenphase (von Neumann reality).**  `z` and `z̄` are values of the unit‑modulus
   eigenstate `spectralWave y` of the self‑adjoint generator `D = −i d/dt`, whose eigenvalue is the
   **real** height `y`; `spectralWave y` is a one‑parameter unitary group (`spectralWave_add`,
   `spectralWave_zero`).  A symmetric operator on a complex inner‑product space has real eigenvalues,
   so the spectral parameter is real by design.

4. **Arithmetic orthogonality (the useful spectral interpretation).**  Every real `y` gives an
   eigenwave; the special event is its *orthogonality* to the arithmetic data.  The finite phasor
   accumulation on the critical line is exactly the ℓ² inner product of the sampled eigenwave with
   the arithmetic‑data vector, `fiberCarrierFinite χ N y = ⟪waveVec y N, dataVec χ N⟫`
   (`fiberCarrierFinite_eq_inner`), so a carrier vanishing is the resonance where the real‑frequency
   eigenstate is Gram‑orthogonal to the arithmetic vector
   (`fiberCarrierFinite_eq_zero_iff_orthogonal`).

The four are collected in `frobenius_local_spectral_mechanism`.

**Scope / honesty.**  Each statement is unconditional and *local* (per height `y`, per site `n`, per
truncation `N`).  Gram positivity (`DeBranges.gram_quadratic_form_nonneg`) places the mechanism
inside the de Branges / Hermite–Biehler positivity grammar, whose reality/discreteness conclusions
are conditional on the Hermite–Biehler hypothesis; for a `Λ`‑built structure that hypothesis — no
off‑line zeros — is the Riemann Hypothesis, and is **neither assumed nor proved** here.  Mathlib‑only.
-/

open Complex
open scoped Real Matrix
open CriticalLinePhasor

namespace CriticalLinePhasor.FrobeniusSimilitude

noncomputable section

/-! ## 1. The Frobenius similitude — prime multiplication as a self‑similarity -/

/-- **The Frobenius multiplier** of the integer `m`: the complex number `√m · wind θ m`, the radial
area‑law factor `√m` times the unit‑modulus winding rotation `wind θ m`. -/
noncomputable def frobeniusMultiplier (θ : ℕ → ℝ) (m : ℕ) : ℂ :=
  (Real.sqrt m : ℂ) * (HelixLogFree.wind θ m : ℂ)

/-- **The Frobenius similitude** of `m`: the ℂ‑linear self‑map `w ↦ (√m · wind θ m) · w` of the
carrier line `ℂ`.  Multiplication `n ↦ m·n` acts on the carrier by this similitude. -/
noncomputable def frobeniusSimilitude (θ : ℕ → ℝ) (m : ℕ) : ℂ →ₗ[ℂ] ℂ :=
  (frobeniusMultiplier θ m) • LinearMap.id

@[simp] theorem frobeniusSimilitude_apply (θ : ℕ → ℝ) (m : ℕ) (w : ℂ) :
    frobeniusSimilitude θ m w = frobeniusMultiplier θ m * w := by
  simp [frobeniusSimilitude]

/-- **Prime multiplication is a similitude (self‑similarity).**  Multiplication `n ↦ m·n` scales the
carrier point radially by `√m` (the area‑law factor) and rotates it by the unit winding `wind θ m`:
`helixPt θ (m·n) = (√m · wind θ m) · helixPt θ n`. -/
theorem helixPt_mul (θ : ℕ → ℝ) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    HelixLogFree.helixPt θ (m * n)
      = frobeniusMultiplier θ m * HelixLogFree.helixPt θ n := by
  rw [HelixLogFree.helixPt, HelixLogFree.helixPt, frobeniusMultiplier,
    HelixLogFree.wind_mul θ hm hn, Circle.coe_mul, Nat.cast_mul,
    Real.sqrt_mul (Nat.cast_nonneg m)]
  push_cast
  ring

/-- The geometric action: `helixPt θ (m·n) = frobeniusSimilitude θ m (helixPt θ n)`. -/
theorem helixPt_eq_similitude (θ : ℕ → ℝ) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    HelixLogFree.helixPt θ (m * n)
      = frobeniusSimilitude θ m (HelixLogFree.helixPt θ n) := by
  rw [frobeniusSimilitude_apply, helixPt_mul θ hm hn]

/-- **The similitude ratio is the area‑law radial factor `√m`.**  The Frobenius multiplier has
modulus `√m`: the winding rotation is unit‑modulus, so all the scaling is the radial `√m`. -/
theorem norm_frobeniusMultiplier (θ : ℕ → ℝ) (m : ℕ) :
    ‖frobeniusMultiplier θ m‖ = Real.sqrt m := by
  rw [frobeniusMultiplier, norm_mul, Complex.norm_real,
    Real.norm_of_nonneg (Real.sqrt_nonneg _), Circle.norm_coe, mul_one]

/-- **The winding rotation is unimodular.** -/
theorem norm_wind_coe (θ : ℕ → ℝ) (m : ℕ) : ‖(HelixLogFree.wind θ m : ℂ)‖ = 1 :=
  Circle.norm_coe _

/-- **The similitude scales every length by `√m`** — a genuine similarity transformation of the
carrier line. -/
theorem norm_frobeniusSimilitude (θ : ℕ → ℝ) (m : ℕ) (w : ℂ) :
    ‖frobeniusSimilitude θ m w‖ = Real.sqrt m * ‖w‖ := by
  rw [frobeniusSimilitude_apply, norm_mul, norm_frobeniusMultiplier]

/-- **Self‑similarity is multiplicative.**  The Frobenius multipliers compose:
`frobeniusMultiplier θ (m·n) = frobeniusMultiplier θ m · frobeniusMultiplier θ n`. -/
theorem frobeniusMultiplier_mul (θ : ℕ → ℝ) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    frobeniusMultiplier θ (m * n) = frobeniusMultiplier θ m * frobeniusMultiplier θ n := by
  rw [frobeniusMultiplier, frobeniusMultiplier, frobeniusMultiplier,
    HelixLogFree.wind_mul θ hm hn, Circle.coe_mul, Nat.cast_mul,
    Real.sqrt_mul (Nat.cast_nonneg m)]
  push_cast
  ring

@[simp] theorem frobeniusMultiplier_one (θ : ℕ → ℝ) : frobeniusMultiplier θ 1 = 1 := by
  simp [frobeniusMultiplier]

/-- **The similitudes compose** (`n ↦ (m·k)·n` is `frobeniusSimilitude θ m ∘ frobeniusSimilitude θ k`):
the carrier is **self‑similar** under the whole multiplicative monoid generated by the primes — the
Frobenius maps. -/
theorem frobeniusSimilitude_mul (θ : ℕ → ℝ) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    frobeniusSimilitude θ (m * n) = frobeniusSimilitude θ m ∘ₗ frobeniusSimilitude θ n := by
  refine LinearMap.ext fun w => ?_
  simp only [frobeniusSimilitude_apply, LinearMap.comp_apply, frobeniusMultiplier_mul θ hm hn]
  ring

theorem frobeniusSimilitude_one (θ : ℕ → ℝ) : frobeniusSimilitude θ 1 = LinearMap.id := by
  refine LinearMap.ext fun w => ?_
  simp

/-- **The similitude rotation is the analytic spin (the bridge).**  With the bridge prime‑angle
assignment `θ p = −y·log p`, the unit winding rotation is exactly the analytic spin
`e^{−iy·log m}`, so `frobeniusMultiplier (−y·log) m = √m · spin y m`. -/
theorem frobeniusMultiplier_bridge (y : ℝ) {m : ℕ} (hm : m ≠ 0) :
    frobeniusMultiplier (fun p => -y * Real.log p) m
      = (Real.sqrt m : ℂ) * LFunctionPhasor.spin y m := by
  rw [frobeniusMultiplier]
  congr 1
  rw [HelixLogFree.wind, Circle.coe_exp, Faithful.windAngle_glog (-y) hm, LFunctionPhasor.spin]
  congr 1
  push_cast
  ring

/-! ## 2. Conjugate chirality and the determinant‑one *unitary* transverse block -/

/-- **`z · z̄ = |z|² = 1`** — the two chiral eigenphases are reciprocal; their product collapses the
scale to unity. -/
theorem spin_mul_conj (y : ℝ) (n : ℕ) :
    LFunctionPhasor.spin y n * (starRingEnd ℂ) (LFunctionPhasor.spin y n) = 1 := by
  simp only [LFunctionPhasor.spin]
  rw [← Complex.exp_conj, ← Complex.exp_add,
    show (-(↑y * ↑(Real.log n)) * Complex.I)
        + (starRingEnd ℂ) (-(↑y * ↑(Real.log n)) * Complex.I) = 0 from by
      simp only [map_neg, map_mul, Complex.conj_I, Complex.conj_ofReal]; ring]
  exact Complex.exp_zero

/-- The **transverse chiral block** at height `y`, site `n`: the diagonal `diag(z, z̄)` of the right
spin `z = spin y n` and the left (conjugate) spin `z̄`. -/
noncomputable def frobeniusBlock (y : ℝ) (n : ℕ) : Matrix (Fin 2) (Fin 2) ℂ :=
  Matrix.diagonal ![LFunctionPhasor.spin y n, (starRingEnd ℂ) (LFunctionPhasor.spin y n)]

/-- **Determinant one.**  `det diag(z, z̄) = z · z̄ = |z|² = 1`: the chiral block is
volume/orientation‑preserving on the transverse plane. -/
theorem frobeniusBlock_det_one (y : ℝ) (n : ℕ) : (frobeniusBlock y n).det = 1 := by
  rw [frobeniusBlock, Matrix.det_diagonal, Fin.prod_univ_two]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]
  exact spin_mul_conj y n

/-- **The transverse block is unitary** (`Mᴴ M = 1`): the two unimodular chiral phases make the
chiral block an isometry of the transverse plane. -/
theorem frobeniusBlock_unitary (y : ℝ) (n : ℕ) :
    (frobeniusBlock y n)ᴴ * frobeniusBlock y n = 1 := by
  rw [frobeniusBlock, Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
    ← Matrix.diagonal_one]
  congr 1
  funext i
  fin_cases i <;>
    simp only [Pi.mul_apply, Pi.star_apply, Fin.mk_zero, Fin.mk_one, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.head_cons, Pi.one_apply, ← starRingEnd_apply, Complex.conj_conj]
  · rw [mul_comm]; exact spin_mul_conj y n
  · exact spin_mul_conj y n

/-! ## 3. Real eigenphase, von Neumann reality, and the one‑parameter unitary group -/

/-- **The spectral wave is a one‑parameter unitary group** (Stone form):
`ψ_y(s+t) = ψ_y(s) · ψ_y(t)`.  The real spectral parameter `y` generates a flow of unit‑modulus
phases. -/
theorem spectralWave_add (y s t : ℝ) :
    UnconditionalFrobenius.spectralWave y (s + t)
      = UnconditionalFrobenius.spectralWave y s * UnconditionalFrobenius.spectralWave y t := by
  simp only [UnconditionalFrobenius.spectralWave]
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

@[simp] theorem spectralWave_zero (y : ℝ) : UnconditionalFrobenius.spectralWave y 0 = 1 := by
  simp [UnconditionalFrobenius.spectralWave]

/-! ## 4. Arithmetic orthogonality — the accumulation as an ℓ² inner product

The ℓ² inner product is the one from `UnconditionalFrobenius` on `ℕ →₀ ℂ`:
`⟪f, g⟫ = ∑ₙ conj(f n) · g n`.  We split the critical‑line phasor `χ(n)·n^{-(½+iy)}` into the
**arithmetic data** `χ(n)·n^{-½}` (the spinless coefficient) and the **eigenwave sample**
`conj(spin y n) = spectralWave y (log n)`, and read the accumulation as their pairing. -/

/-- The **arithmetic‑data vector** `dataVec χ N`: the spinless coefficients `χ(n)·n^{-½}` placed at
the sites `n < N`. -/
noncomputable def dataVec {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (N : ℕ) : ℕ →₀ ℂ :=
  Finsupp.onFinset (Finset.range N)
    (fun n => if n ∈ Finset.range N then χ (n : ZMod q) * (((n : ℝ) ^ (-(1 / 2 : ℝ)) : ℝ) : ℂ)
      else 0)
    (fun n hn => by by_contra h; exact hn (if_neg h))

/-- The **eigenwave‑sample vector** `waveVec y N`: the self‑adjoint eigenstate `spectralWave y`
sampled at the carrier log‑heights `log n` (equivalently the left/conjugate chirality
`conj(spin y n)`), at the sites `n < N`. -/
noncomputable def waveVec (y : ℝ) (N : ℕ) : ℕ →₀ ℂ :=
  Finsupp.onFinset (Finset.range N)
    (fun n => if n ∈ Finset.range N then UnconditionalFrobenius.spectralWave y (Real.log n) else 0)
    (fun n hn => by by_contra h; exact hn (if_neg h))

theorem dataVec_apply {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) {N k : ℕ}
    (hk : k ∈ Finset.range N) :
    dataVec χ N k = χ (k : ZMod q) * (((k : ℝ) ^ (-(1 / 2 : ℝ)) : ℝ) : ℂ) := by
  rw [dataVec, Finsupp.onFinset_apply, if_pos hk]

theorem waveVec_apply {y : ℝ} {N k : ℕ} (hk : k ∈ Finset.range N) :
    waveVec y N k = UnconditionalFrobenius.spectralWave y (Real.log k) := by
  rw [waveVec, Finsupp.onFinset_apply, if_pos hk]

/-- **The accumulation is an inner product `⟨eigenwave, arithmetic data⟩`.**  The finite phasor
accumulation on the critical line is the ℓ² pairing of the sampled self‑adjoint eigenwave
`waveVec y` with the arithmetic‑data vector `dataVec χ`:
`fiberCarrierFinite χ N y = ⟪waveVec y N, dataVec χ N⟫`. -/
theorem fiberCarrierFinite_eq_inner {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (y : ℝ) (N : ℕ) :
    FiberHarmonic.fiberCarrierFinite χ N y
      = (inner ℂ (waveVec y N) (dataVec χ N) : ℂ) := by
  have hin : (inner ℂ (waveVec y N) (dataVec χ N) : ℂ)
      = ∑ k ∈ Finset.range N,
          (starRingEnd ℂ) (waveVec y N k) * dataVec χ N k :=
    UnconditionalFrobenius.inner_eq_sum_of_subset _ _ Finsupp.support_onFinset_subset
  rw [hin, FiberHarmonic.fiberCarrierFinite]
  refine Finset.sum_congr rfl fun k hk => ?_
  rw [waveVec_apply hk, dataVec_apply χ hk, ← Faithful.conj_spin_eq_spectralWave,
    Complex.conj_conj, FiberHarmonic.fiberPhasor, LFunctionPhasor.spin]
  ring

/-- **Vanishing is arithmetic orthogonality.**  The accumulation vanishes exactly when the sampled
eigenwave is ℓ²‑orthogonal to the arithmetic data.  A located carrier vanishing is the resonance
where the real‑frequency eigenstate is orthogonal to the arithmetic vector. -/
theorem fiberCarrierFinite_eq_zero_iff_orthogonal {q : ℕ} [NeZero q]
    (χ : DirichletCharacter ℂ q) (y : ℝ) (N : ℕ) :
    FiberHarmonic.fiberCarrierFinite χ N y = 0
      ↔ (inner ℂ (waveVec y N) (dataVec χ N) : ℂ) = 0 := by
  rw [fiberCarrierFinite_eq_inner]

/-- **The pairing is the partial Dirichlet phasor sum.**  The eigenwave/data pairing equals the
finite phasor carrier `G_{χ,N}(½+iy) = ∑_{n<N} χ(n)·n^{-(½+iy)}`, tying the inner‑product reading to
the analytic accumulation (which converges to `L(½+iy,χ)`). -/
theorem inner_eq_finiteCarrier {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (y : ℝ) (N : ℕ) :
    (inner ℂ (waveVec y N) (dataVec χ N) : ℂ)
      = DirichletPhasorCarrier.finiteCarrier χ ((1 / 2 : ℂ) + (y : ℂ) * Complex.I) N := by
  rw [← fiberCarrierFinite_eq_inner, FiberHarmonic.fiberCarrierFinite,
    DirichletPhasorCarrier.finiteCarrier]
  refine Finset.sum_congr rfl fun n hn => ?_
  rcases Nat.eq_zero_or_pos n with h0 | hpos
  · subst h0
    have hs0 : ((1 / 2 : ℂ) + (y : ℂ) * Complex.I) ≠ 0 := by
      intro h
      have := congrArg Complex.re h
      simp [Complex.add_re, Complex.mul_re, Complex.I_re, Complex.I_im] at this
    have hL : FiberHarmonic.fiberPhasor χ 0 y = 0 := by
      simp only [FiberHarmonic.fiberPhasor, Nat.cast_zero, Real.zero_rpow (by norm_num : -(1/2:ℝ) ≠ 0),
        Complex.ofReal_zero, mul_zero, zero_mul]
    have hR : DirichletPhasorCarrier.phasorTerm χ ((1 / 2 : ℂ) + (y : ℂ) * Complex.I) 0 = 0 := by
      simp only [DirichletPhasorCarrier.phasorTerm, Nat.cast_zero,
        Complex.zero_cpow (neg_ne_zero.mpr hs0), mul_zero]
    rw [hL, hR]
  · rw [FiberHarmonic.fiberPhasor_eq_cpow χ n hpos, DirichletPhasorCarrier.phasorTerm]

/-! ## 5. Gram positivity — the bridge into the de Branges positivity grammar (conditional) -/

/-- **Gram positivity (the de Branges background).**  Any finite family of carrier vectors has a
positive‑semidefinite Gram form `∑ᵢⱼ conj(cᵢ)·cⱼ·⟨vᵢ,vⱼ⟩ = ‖∑ cᵢvᵢ‖² ≥ 0` — the positive‑kernel
fact underlying a de Branges / Hermite–Biehler space.  The *global* Hermite–Biehler condition for a
`Λ`‑built structure (no off‑line zeros) is **not** proved here; it is RH‑level and left open. -/
theorem carrier_gram_nonneg {n : ℕ} (v : Fin n → (ℕ →₀ ℂ)) (c : Fin n → ℂ) :
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * (inner ℂ (v i) (v j))).re :=
  DeBranges.gram_quadratic_form_nonneg v c

/-! ## 6. The compact local spectral mechanism, assembled -/

/-- **The compact local spectral mechanism.**  At every height `y` and site `n` (with modulus data
`χ` and truncation `N`), the four ingredients hold simultaneously and unconditionally:

1. **Frobenius similitude (self‑similarity).**  `helixPt θ (m·n) = frobeniusSimilitude θ m (helixPt θ n)`,
   with multiplier modulus `√m` and unimodular rotation `wind θ m`, and the similitudes compose.
2. **Conjugate chirality, determinant‑one unitary transverse block.**  `det diag(z,z̄) = 1` and the
   block is unitary — the orientation/volume‑preserving chiral invariant.
3. **Real eigenphase (von Neumann reality).**  `z = spin y n` is a value of the unit‑modulus
   eigenstate `spectralWave y` of `D = −i d/dt`; the generator is symmetric and every eigenvalue is
   real.
4. **Arithmetic orthogonality.**  the accumulation is `⟪waveVec y N, dataVec χ N⟫`, so a carrier
   vanishing is orthogonality of the real‑frequency eigenstate to the arithmetic data.

No off‑line / Hilbert–Pólya / RH claim is made (see the module docstring). -/
theorem frobenius_local_spectral_mechanism
    (θ : ℕ → ℝ) (y : ℝ) {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0)
    {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (N : ℕ) :
    -- (1) Frobenius similitude
    (HelixLogFree.helixPt θ (m * n) = frobeniusSimilitude θ m (HelixLogFree.helixPt θ n)
      ∧ ‖frobeniusMultiplier θ m‖ = Real.sqrt m
      ∧ ‖(HelixLogFree.wind θ m : ℂ)‖ = 1
      ∧ frobeniusSimilitude θ (m * n) = frobeniusSimilitude θ m ∘ₗ frobeniusSimilitude θ n)
    -- (2) determinant‑one unitary transverse block
    ∧ ((frobeniusBlock y n).det = 1 ∧ (frobeniusBlock y n)ᴴ * frobeniusBlock y n = 1)
    -- (3) real eigenphase / von Neumann reality
    ∧ (LFunctionPhasor.spin y n = UnconditionalFrobenius.spectralWave y (-Real.log n)
      ∧ (∀ t : ℝ, -Complex.I * deriv (UnconditionalFrobenius.spectralWave y) t
          = (y : ℂ) * UnconditionalFrobenius.spectralWave y t)
      ∧ (∀ t : ℝ, ‖UnconditionalFrobenius.spectralWave y t‖ = 1)
      ∧ (UnconditionalFrobenius.vonNeumannOp y).IsSymmetric
      ∧ (∀ μ : ℂ, Module.End.HasEigenvalue (UnconditionalFrobenius.vonNeumannOp y) μ → μ.im = 0))
    -- (4) arithmetic orthogonality
    ∧ (FiberHarmonic.fiberCarrierFinite χ N y = (inner ℂ (waveVec y N) (dataVec χ N) : ℂ)
      ∧ (FiberHarmonic.fiberCarrierFinite χ N y = 0
          ↔ (inner ℂ (waveVec y N) (dataVec χ N) : ℂ) = 0)) :=
  ⟨⟨helixPt_eq_similitude θ hm hn, norm_frobeniusMultiplier θ m, Circle.norm_coe _,
      frobeniusSimilitude_mul θ hm hn⟩,
    ⟨frobeniusBlock_det_one y n, frobeniusBlock_unitary y n⟩,
    ⟨Faithful.spin_eq_spectralWave y n, UnconditionalFrobenius.spectralWave_eigen y,
      UnconditionalFrobenius.spectralWave_norm y, UnconditionalFrobenius.vonNeumannOp_isSymmetric y,
      fun _ hμ => UnconditionalFrobenius.vonNeumannOp_spectrum_real y hμ⟩,
    ⟨fiberCarrierFinite_eq_inner χ y N, fiberCarrierFinite_eq_zero_iff_orthogonal χ y N⟩⟩

/-! ## 7. No native off‑axis support — the admissible state space is the critical line

The sharper, intrinsically geometric statement (weaker than RH, and defensible without it): the
carrier *admits* a scale‑balanced double‑ended Frobenius‑compatible state **only** on `Re s = ½`.
The abscissa `½` is not chosen — it is the unique exponent compatible with the arclength area law
(`Geometry.sigma_half_is_scale_critical`); off‑axis abscissae are *inadmissible* (not
scale‑normalized to the carrier), and the functional‑equation reflection closes the double‑ended
carrier exactly on the fixed line.  This is the carrier's internal state space; it makes **no** claim
that every analytic zero must arise from an admissible state (that global question — equivalently
RH/GRH — is left open). -/

/-- A real abscissa `σ` is a **scale‑balanced (admissible) state** of the carrier `(p,r)` when the
fiber amplitude `n^{-σ}` reciprocates the area‑law radius `carrierRadius ~ √n` to a *positive finite*
scale: `∃ L > 0, n^{-σ}·carrierRadius → L`.  (For `σ` too large the fiber decays faster than the
carrier grows and the product `→ 0`; for `σ` too small it outruns the carrier and `→ ∞`; neither is a
stable scale‑normalized fiber.) -/
def ScaleBalanced (p r : ℝ) (σ : ℝ) : Prop :=
  ∃ L : ℝ, 0 < L ∧ Filter.Tendsto (fun n : ℕ => (n : ℝ) ^ (-σ) * Geometry.carrierRadius p r n)
    Filter.atTop (nhds L)

/-- **The admissible‑state exponent is forced, not chosen.**  `σ` is a scale‑balanced admissible
state iff `σ = ½`: the critical abscissa is the *unique* exponent compatible with the arclength area
law `r_n ~ √n` (re‑export of `Geometry.sigma_half_is_scale_critical`), so it is derived from the
geometry rather than posited — and it is gauge‑independent in `(p,r)`. -/
theorem scaleBalanced_iff (p r : ℝ) (hr : 0 < r) (σ : ℝ) :
    ScaleBalanced p r σ ↔ σ = 1 / 2 :=
  Geometry.sigma_half_is_scale_critical p r hr σ

/-- **Off‑axis abscissae are inadmissible — no native off‑axis support.**  For `σ ≠ ½` the fiber is
*not* a scale‑balanced state of the carrier: its amplitude `n^{-σ}` is not scale‑normalized to the
area‑law radius.  (A statement about the carrier's admissible states, not about where zeros lie.) -/
theorem not_scaleBalanced_of_ne (p r : ℝ) (hr : 0 < r) {σ : ℝ} (hσ : σ ≠ 1 / 2) :
    ¬ ScaleBalanced p r σ := fun h => hσ ((scaleBalanced_iff p r hr σ).mp h)

/-- **The carrier's admissible state space is exactly the critical line:**
`{σ | ScaleBalanced p r σ} = {½}`. -/
theorem scaleBalanced_setOf_eq (p r : ℝ) (hr : 0 < r) :
    {σ : ℝ | ScaleBalanced p r σ} = {1 / 2} := by
  ext σ
  rw [Set.mem_setOf_eq, Set.mem_singleton_iff, scaleBalanced_iff p r hr]

/-- **The functional‑equation reflection fixes exactly the critical line.**  The dualizing map
`s ↦ 1−s` (which pairs the two chiral fibers) has `Re(1−s) = Re s` iff `Re s = ½`: off‑axis it sends
an abscissa imbalance `σ` to the opposite imbalance `1−σ` (a dual *pair*, not a self‑conjugate
state), so the double‑ended carrier closes only on the fixed locus `Re s = ½`. -/
theorem reflection_fixes_iff (s : ℂ) : (1 - s).re = s.re ↔ s.re = 1 / 2 := by
  rw [Complex.sub_re, Complex.one_re]
  constructor <;> intro h <;> linarith

/-- **No native off‑axis support — the intrinsic on‑axis state space, assembled.**  At any carrier
`(p,r)` (`r>0`), height `y`, site `n`, the hierarchy holds:

1. **Area law** `carrierRadius² / m → r·(π/3)/π` (`r_n ~ √n`), derived from the arclength geometry.
2. **Unique scale balance**: `σ` is a scale‑balanced admissible state iff `σ = ½` — forced, not chosen.
3. **Off‑axis inadmissibility**: every `σ ≠ ½` is *not* a scale‑balanced state.
4. **Unitary chiral block at the balanced axis**: the two chiral fibers `z, z̄` form a
   determinant‑one unitary transverse block.
5. **Functional‑equation duality**: `s ↦ 1−s` fixes exactly `Re s = ½`, on which the on‑line de
   Branges variable is real — the locus where the double‑ended carrier closes.

This is the model's admissible internal state space.  It is **not** the claim that all analytic zeros
lie there (RH/GRH), which is left open. -/
theorem no_native_offaxis_support (p r : ℝ) (hr : 0 < r) (y : ℝ) (n : ℕ) :
    Filter.Tendsto (fun m : ℕ => (Geometry.carrierRadius p r m) ^ 2 / (m : ℝ)) Filter.atTop
        (nhds (r * (Real.pi / 3) / Real.pi))
      ∧ (∀ σ : ℝ, ScaleBalanced p r σ ↔ σ = 1 / 2)
      ∧ (∀ σ : ℝ, σ ≠ 1 / 2 → ¬ ScaleBalanced p r σ)
      ∧ (frobeniusBlock y n).det = 1
      ∧ (frobeniusBlock y n)ᴴ * frobeniusBlock y n = 1
      ∧ (∀ s : ℂ, (1 - s).re = s.re ↔ s.re = 1 / 2)
      ∧ (-(Complex.I * (((1 : ℂ) / 2 + (y : ℂ) * Complex.I) - 1 / 2))).im = 0 :=
  ⟨Geometry.carrierRadius_sq_div_tendsto p r hr,
    scaleBalanced_iff p r hr,
    fun _ hσ => not_scaleBalanced_of_ne p r hr hσ,
    frobeniusBlock_det_one y n,
    frobeniusBlock_unitary y n,
    reflection_fixes_iff,
    Faithful.criticalLine_deBranges_real y⟩

end

end CriticalLinePhasor.FrobeniusSimilitude
