import RequestProject.HelixResolventCapture
import RequestProject.Origination
import RequestProject.GradedModeDictionary
import RequestProject.HilbertPolya
import RequestProject.FocalResidualVanishes
import RequestProject.LimitDominance
import RequestProject.Faithfulness
import RequestProject.RoundTrip
import RequestProject.ShannonCascade
import RequestProject.FiniteWeightFiber
import RequestProject.FrobeniusSimilitude
import RequestProject.NoDoubleCancellation
import RequestProject.EulerMaclaurinDirichlet
import RequestProject.TransferContinuation
import RequestProject.ExportAdapter
import RequestProject.DifferencedResolvent

/-!
# The Riemann evidence dossiers

Two bundles of **unconditionally-proven facts**, one per reading of Hilbert–Pólya, assembled
by the author to hand the community the support base for each interpretation.  Each dossier is
a single theorem whose conjuncts are the supporting facts; the theorem's inhabitation
**certifies every fact is a theorem, no hypothesis** (`#print axioms` returns the standard
three).  Crucially, these are **evidence _for_ the readings, not proofs _of_ them** — the two
conditional hypotheses (`ThreeD_crossings_are_real_zeros`, `OneD_zeta_zero_correlated`) remain
in `HelixResolventCapture`, named and asserted by no one; proving either would resolve RH.

The author's assignment of evidence to readings, cast leads in **bold**:

* **`threeDRealEvidence`** — the *3D-real (identity)* reading: the operator's crossings are the
  genuine, exact article.  **Feynman's Quiver** (the crossings are prime-generated by FTA, and
  the phasor bank is *summable* — the finite carrier converges to `L`), **Deligne's Pairs**
  (the det-1 self-reciprocal local factor, the Frobenius conjugate `det = 1`, the fiber weight
  product `= 1` — purity at the finite places), the carrier's self-adjoint reality, 3D
  exhaustion (no state has an unsourced vanishing), the Hilbert–Pólya operator and its
  multiplicity structure, the exact vanishing at each eigenstate, and **Shannon Projection
  Dominance** (in projection geometry the highest level is the real one — the source
  dominates every projection).

* **`oneDCorrelationEvidence`** — the *1D-correlation (coincidence)* reading: the 1D chart zero
  faithfully corresponds to the 3D crossing.  **S(t)** (the global registration binding),
  the no-radial-drift fidelity, the on-circle placement and the lossless round-trip
  projection (**Shannon**: the collapse loses to the ledger but never counterfeits),
  **Riemann's Fold** (a real-axis projection crossing multiple dimensions lands at the real
  axis for all of them, and only the real axis does), the real-on-line faithful projection,
  the window-by-window coincidence, and residue = jump(S).

Nothing here is conditional; everything is machine-checked at the standard axioms.
-/

open Complex Filter Topology
open CriticalLinePhasor CriticalLinePhasor.SourceHolonomy CriticalLinePhasor.HilbertPolya
open CriticalLinePhasor.GradedModes CriticalLinePhasor.ResidueJump CriticalLinePhasor.CarrierScale
open Faithful

namespace CriticalLinePhasor.RiemannEvidence

/-- **Dossier — unconditional support for the 3D-real (identity) reading.**  The operator's
crossings are the genuine, exact article: the carrier is self-adjoint (reality), every 3D
event is sourced (exhaustion) with no spurious state zeros, the winding is generated by the
primes through FTA (**Feynman**), the Hilbert–Pólya operator is self-adjoint with eigenspace
dimension equal to multiplicity, and every eigenstate marks an exact zeta vanishing.  Each
conjunct is a compiled theorem; inhabiting this certifies all of them unconditionally.  It is
*evidence for* the identity reading, not a proof *of* it. -/
abbrev ThreeDRealEvidence : Prop :=
    (∀ γ : ℝ, (UnconditionalFrobenius.vonNeumannOp γ).IsSymmetric)
    ∧ (∀ E : ℂ → ℂ, ThreeDExhaustive E)
    ∧ (∀ F : ℕ →₀ ℂ, CriticalLinePhasor.CupIdentity.Cup F F = 0 ↔ F = 0)
    ∧ (∀ m n : ℕ, m ≠ 0 → n ≠ 0 →
        Origination.windFromPrimes (m * n)
          = Origination.windFromPrimes m * Origination.windFromPrimes n)
    -- **Feynman's Quiver**: summability of phasors — the finite phasor bank converges to `L`.
    ∧ (∀ {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q), χ ≠ 1 → ∀ (s : ℂ), 0 < s.re →
        Tendsto (DirichletPhasorCarrier.finiteCarrier χ s) atTop
          (nhds (DirichletCharacter.LFunction χ s)))
    -- **The phasor version of FTA**: all phasor heights are unique (distinct integers give
    -- distinct heights, `logGen` injective) — one unique phasor per integer, exactly as one
    -- prime factorization per integer.
    ∧ (∀ (m n : ℕ), m ≠ n → SelfAdjointGenerator.logGen m ≠ SelfAdjointGenerator.logGen n)
    -- **No split focus** (consequence of phasor-FTA): only one channel grows into reality at a
    -- time — at most one mode cancels at any spectral parameter, so the cancelled energy cannot
    -- split evenly at two distinct sites simultaneously.
    ∧ (∀ (s : ℂ), {n : ℕ |
        SelfAdjointGenerator.specOp SelfAdjointGenerator.Aχ s (Finsupp.single n 1) = 0}.Subsingleton)
    -- **Deligne's Pairs**: the det-1 self-reciprocal local factor — the `(λ, 1/λ)` pairing
    -- degenerating on the unit circle (purity at the finite places), with the Frobenius
    -- conjugate `det = 1` and the fiber weight product `= 1`.
    ∧ (∀ {ι : Type} [Fintype ι] (W : FiniteWeightFiber ι) (X : ℂ), X ≠ 0 →
        W.localPoly X = (-X) ^ (Fintype.card ι) * W.localPoly X⁻¹)
    ∧ (∀ (y : ℝ) (n : ℕ), (FrobeniusSimilitude.frobeniusBlock y n).det = 1)
    ∧ (∀ {ι : Type} [Fintype ι] (W : FiniteWeightFiber ι), ∏ i, W.weight i = 1)
    ∧ (∀ T : ℝ, (hpOperator T).IsHermitian)
    ∧ (∀ γ : ℝ, Module.finrank ℂ (ModeSpace γ) = eventOrder γ)
    -- **Exact harmonic vanishing**: the focal residual vanishes *exactly* iff the represented
    -- L-value does — the 3D cancellation is exact (residue-free), not approximate.
    ∧ (∀ {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q) (Z : ℝ),
        HarmonicCell.Dcell χ Z = 0
          ↔ DirichletCharacter.LFunction χ (HarmonicCell.reprPoint χ Z) = 0)
    ∧ (∀ {T : ℝ} (p : WindowIndex T), riemannZeta (line p.1.1) = 0)
    -- **Resolvent trace directly on the 3D modes**: the graded resolvent trace over the
    -- Hilbert–Pólya mode spaces equals the residue sum — the resolvent read on the 3D
    -- eigenspaces themselves, not through the chart.
    ∧ (∀ (w : ℂ) (T : ℝ), (∀ γ ∈ eventWindow T, w ≠ (γ : ℂ)) → ∀ (r : ℝ → ℂ),
        (∀ γ ∈ eventWindow T, Tendsto (fun s => (s - line γ) * logDeriv riemannZeta s)
            (𝓝[≠] line γ) (nhds (r γ))) →
        gradedResolventTrace w T = ∑ γ ∈ eventWindow T, r γ * ((γ : ℂ) - w)⁻¹)
    -- **Shannon Projection Dominance**: in projection geometry the highest level is the real
    -- one — every zero of a projection (the limit) is sourced from the higher level (the
    -- stages), so the source dominates and the 3D level is primary.
    ∧ (∀ (F : ℕ → ℂ → ℂ) (f : ℂ → ℂ) (U : Set ℂ), IsOpen U →
        TendstoLocallyUniformlyOn F f atTop U → (∀ n, DifferentiableOn ℂ (F n) U) →
        ∀ (z₀ : ℂ), z₀ ∈ U → f z₀ = 0 → ¬ (∀ᶠ z in nhds z₀, f z = 0) →
        ∀ (ε : ℝ), 0 < ε → ∀ᶠ n in atTop, ∃ z ∈ Metric.ball z₀ ε, F n z = 0)

/-- The 3D-real evidence holds unconditionally (proof of `ThreeDRealEvidence`). -/
theorem threeDRealEvidence : ThreeDRealEvidence := by
  refine ⟨UnconditionalFrobenius.vonNeumannOp_isSymmetric, threeD_exhaustive,
    threeD_metric_no_zeros, fun m n hm hn => Origination.windFromPrimes_mul hm hn,
    fun χ hχ _ hs => fiber_accumulates_to_L χ hχ hs,
    fun _ _ hmn => SelfAdjointGenerator.heights_distinct hmn,
    SelfAdjointGenerator.cancellation_modes_subsingleton,
    fun W X hX => W.localPoly_reciprocal hX,
    FrobeniusSimilitude.frobeniusBlock_det_one, fun W => W.fiber_det_one,
    hpOperator_isHermitian, finrank_modeSpace,
    fun χ Z => HarmonicCell.focal_residual_zero_iff_L_zero χ Z, ?_,
    fun w T hw r hr => gradedResolventTrace_eq_residue_sum w T hw r hr, ?_⟩
  · intro T p
    exact eigenheight_is_exact_vanishing p
  · exact fun _ _ _ hU hconv hdiff _ hz₀ hf0 hnz _ hε =>
      CriticalLinePhasor.LimitDominance.limit_dominance hU hconv hdiff hz₀ hf0 hnz hε

/-- **Dossier — unconditional support for the 1D-correlation (coincidence) reading.**  The 1D
chart zero faithfully corresponds to the 3D crossing: `S(t)` is the global registration link
and reads the operator's dimension; there is no radial drift and every ledger entry lands on
the unit circle; the round-trip projection is a lossless bijection with the midpoint charting
to `1/2` (**Shannon** — the collapse never counterfeits); the completed projection is real on
the line and vanishes exactly at the zeros; the chart zero coincides with an eigenstate window
by window; and the log-derivative residue equals the jump of `S`.  Each conjunct compiled;
*evidence for* the correlation reading, not a proof *of* it. -/
abbrev OneDCorrelationEvidence : Prop :=
    (∀ t : ℝ, N_pi3 (Real.exp t) - N_1 (Real.exp t) = S t)
    ∧ (∀ T : ℝ, (Fintype.card (WindowIndex T) : ℝ) = 1 + theta T / Real.pi + Smult T)
    ∧ (∀ c y₁ y₂ : ℝ, ‖Complex.exp (-(c : ℂ) * (((1/2 : ℝ) : ℂ) + y₁ * Complex.I))‖
        = ‖Complex.exp (-(c : ℂ) * (((1/2 : ℝ) : ℂ) + y₂ * Complex.I))‖)
    ∧ (∀ y : ℝ, ‖1 - (((1/2 : ℝ) : ℂ) + y * Complex.I)⁻¹‖ = 1)
    ∧ Function.Bijective ConeProjection.record
    -- **Riemann's Fold**: a no-drift real-axis projection crossing multiple dimensions
    -- (3D weld → 2D circle-midpoint → 1D `½`) lands at the real axis for *all* crossed
    -- dimensions — and only the real axis does: `pipeline x = ½ ↔ x = ½`.
    ∧ (∀ x : ℝ, ConeProjection.pipeline x = 1 / 2 ↔ x = 1 / 2)
    ∧ (∀ (γ : ℝ), (completedRiemannZeta (1 / 2 + (γ : ℂ) * Complex.I)).im = 0
        ∧ (EtaTrivial.Feta γ = 0 ↔ riemannZeta ((1 / 2 : ℂ) + (γ : ℂ) * Complex.I) = 0))
    ∧ (∀ (T γ : ℝ), 0 < γ → γ ≤ T →
        (riemannZeta (line γ) = 0 ↔ ∃ p : WindowIndex T, p.1.1 = γ))
    ∧ (∀ (γ : ℝ), 0 < γ →
        Tendsto (fun s => (s - line γ) * logDeriv riemannZeta s) (𝓝[≠] line γ)
          (𝓝 (eventOrder γ : ℂ)) ∧ HasJump Smult γ (eventOrder γ))
    -- **1D approximation via infinite analytic calculation**: the 1D partial sum only equals ζ
    -- up to `N^{1-s}/(1-s) + O(N^{-σ})` — the 1D chart value is an approximation demanding
    -- infinite continuation, correlating to (never equalling by finite means) the exact value.
    ∧ (∀ (s : ℂ), 0 < s.re → s.re < 1 → s ≠ 1 →
        ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 2 ≤ N →
          ‖GRH.SpiralInduction.S s N - riemannZeta s -
            (↑N : ℂ) ^ ((1 : ℂ) - s) / ((1 : ℂ) - s)‖ ≤ C * (↑N : ℝ) ^ (-s.re))
    -- **Faithful transport** (local correlation): Abel/growth transport continues the readout.
    ∧ (∀ (a : ℕ → ℂ) (Cc θ : ℝ), 0 ≤ θ →
        (∀ n : ℕ, ‖∑ k ∈ Finset.range n, a k‖ ≤ Cc * (n : ℝ) ^ θ) → ∀ (s : ℂ), θ < s.re →
        ∃ L : ℂ,
          Tendsto (fun N => ∑ n ∈ Finset.range N, a n * ((n + 1 : ℕ) : ℂ) ^ (-s)) atTop (nhds L))
    -- **Shannon Cascade**: an accumulation of stage features is a feature of the limit.
    ∧ (∀ (Cc : Cascade.MidpointCascade) (z : ℂ),
        (∀ ε > 0, ∀ᶠ n in atTop, ∃ w ∈ Metric.ball z ε, Cc.stage n w = 0) →
        XiChannel.xiSection z = 0)
    -- **S(t) detects every crossing**; every count-jump belongs entirely to S(t).
    ∧ (∀ (γ : ℝ), 0 < γ → (HasJump S γ 1 ↔ riemannZeta (line γ) = 0))
    ∧ (∀ (γ j : ℝ), HasJump (fun t => (zeroEventCount t : ℝ)) γ j ↔ HasJump S γ j)
    -- **The loss ledger**: radius/phase are genuinely lost (booked), yet the chart chain is
    -- injective — the DPI made literal, a lossless round-trip.
    ∧ (∃ f₁ f₂ : ConeProjection.Fiber, ConeProjection.radial f₁ ≠ ConeProjection.radial f₂ ∧
        ConeProjection.realize f₁ ≠ ConeProjection.realize f₂ ∧
        ConeProjection.geomProj f₁ = ConeProjection.geomProj f₂)
    ∧ Function.Injective (fun y : ℝ => 1 - (((1/2 : ℝ) : ℂ) + y * Complex.I)⁻¹)
    -- **Native identification**: the π/3 native count equals the zero-event count exactly.
    ∧ (∀ (t : ℝ), N_pi3 (Real.exp t) = (zeroEventCount t : ℝ))
    -- **Resolvent-trace `T→∞` limit (chart)**: the windowed differenced resolvent converges.
    ∧ (∀ (w : ℂ), Tendsto (fun T => windowedTrace (fun γ => ((γ : ℂ) - w)⁻¹ - (γ : ℂ)⁻¹) T)
        atTop (nhds (ResolventLimit.diffResolvent w)))

/-- The 1D-correlation evidence holds unconditionally (proof of `OneDCorrelationEvidence`). -/
theorem oneDCorrelationEvidence : OneDCorrelationEvidence := by
  refine ⟨carrier_scale_compensation_S, hpDimension_eq_registration,
    no_radial_drift_on_helix, midpoint_entry_on_circle,
    ConeProjection.record_bijective, ConeProjection.pipeline_midpoint_iff,
    Faithful.faithful_projection_zeta,
    fun T γ h0 hT => chartZero_iff_eigenheight h0 hT, residue_eq_Smult_jump,
    fun s hσ hσ1 hs1 => GRH.EulerMaclaurinDirichlet.euler_maclaurin_dirichlet s hσ hσ1 hs1,
    fun a Cc θ hθ hA s hs => TransferContinuation.transfer_tendsto a Cc θ hθ hA s hs,
    fun Cc z hacc => Cascade.limit_zero_of_stage_accumulation Cc hacc,
    fun γ hγ => S_jump_detects_event hγ,
    count_hasJump_iff_S_hasJump,
    ConeProjection.radial_lost,
    projection_bijective_loss_ledger,
    native_identification',
    ResolventLimit.windowedDiffResolvent_tendsto⟩

/-! ## Each reading, combined: its dossier with its conditional

The two supporting dossiers are combined here with their respective conditionals (the GRH/RH
branches of `HelixResolventCapture`).  Each theorem presents the reading whole: the
**unconditional evidence** (left — proven, its presence certifies every fact) together with the
reading's **conditional implication to RH** (right — the single first-of-kind hypothesis,
isolated and asserted by no one).  This lives here, not in `HelixResolventCapture`, because the
evidence is built *on* the capstone (the Shannon Cascade uses it), so it sits downstream. -/

/-- **The 3D-real (identity) reading, combined.**  `threeDRealEvidence` (unconditional) with the
conditional `ThreeD_crossings_are_real_zeros χ₁ → RiemannHypothesis` (`RH_of_resolvant_trace_3D_real`,
self-adjoint discharged). -/
theorem threeD_real_case :
    ThreeDRealEvidence
      ∧ (∀ (χ₁ : DirichletCharacter ℂ 1),
          HelixLimit.ThreeD_crossings_are_real_zeros χ₁ → RiemannHypothesis) :=
  ⟨threeDRealEvidence, HelixLimit.RH_of_resolvant_trace_3D_real⟩

/-- **The 1D-correlation (coincidence) reading, combined.**  `oneDCorrelationEvidence`
(unconditional) with the conditional `OneD_zeta_zero_correlated χ₁ → RiemannHypothesis`
(`RH_of_resolvant_trace_1D_correlation`, self-adjoint discharged). -/
theorem oneD_correlation_case :
    OneDCorrelationEvidence
      ∧ (∀ (χ₁ : DirichletCharacter ℂ 1),
          HelixLimit.OneD_zeta_zero_correlated χ₁ → RiemannHypothesis) :=
  ⟨oneDCorrelationEvidence, HelixLimit.RH_of_resolvant_trace_1D_correlation⟩

end CriticalLinePhasor.RiemannEvidence

#print axioms CriticalLinePhasor.RiemannEvidence.threeDRealEvidence
#print axioms CriticalLinePhasor.RiemannEvidence.oneDCorrelationEvidence
#print axioms CriticalLinePhasor.RiemannEvidence.threeD_real_case
#print axioms CriticalLinePhasor.RiemannEvidence.oneD_correlation_case
